### ISSUE TITLE
kendo integration strategy

### ISSUE THREAD

**Issue by cmichaelgraham** [aurelia/templating-resources#1]
please consider how to best integrate kendo components with Aurelia. 

Telerik has [created angular directives](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.angular.js) around the kendo controls.
[Here is an example](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.angular.js#L403) of how kendo “tears down” or “destroys” its widgets

#### how a kendo widget is configured
>here's a [data pager config example](https://github.com/technicalmedia/aurelia-kendo-spike2/blob/master/src/au-kendo-test-json.ts#L32-L34)
>here's a [list view config example](https://github.com/technicalmedia/aurelia-kendo-spike2/blob/master/src/kendo-test-json.ts#L30-L33)

if you [click on this link](http://demos.telerik.com/kendo-ui/), there are a zillion samples of using their controls. i feel like that richness would compliment Aurelia nicely :smile:
 
each control has samples, and if you scroll down it shows the html and javascript
it is a fast way to figure out how to use the controls and copy-paste to get running

you can almost do it today with the global syntax

`<div jquery.kendopager=“dataSource.bind:dataSource”></div>`
it follows the same pattern

the only thing preventing this from working now is the casing of the plugin name
we can solve that probably

(becuase html doesn’t guarantee casing of attributes, you can’t actually use the casing in the DOM)

**Comment by EisenbergEffect** [comment]
Ok. We will start by fixing up the global behavior with some ways to configure maps.  That should help make simple scenarios really easy. Probably, if you want things to be really nice, someone will have to put time into creating a set of custom element behaviors.

**Comment by EisenbergEffect** [comment]
As of  7453bb3 we have a more extensible mechanism for simple jQuery-ish behaviors. Beyond that it's expected that that one would create custom behaviors.

**Comment by iicaisin1** [comment]
What is the best strategy to dispose custom elements in Aurelia? I tried to use Detached() function but it is too late as the view had already been detached. Of course, it works on Deactivate() call, but is it doesn't seem the right place. It is almost begging for a new IsDetaching() call - not sure if this is over the top.

Here is what I used for testing kendo:
let widget = kendo.widgetInstance(element, kendo.ui);
widget.Destroy();

**Comment by EisenbergEffect** [comment]
Why is the `detached` callback to late?

**Comment by iicaisin1** [comment]
I am currently using just a view with the following template:

```
 <template>
    <section>
        <div id="scheduler"></div>
    </section>
</template>
``` 

<pre lang="javascript"><code>

import {IViewModel}   from  'framework/IViewModel';


export class Welcome implements IViewModel {
    constructor() { 
    }

    attached() {

        return new Promise((resolve, reject) => {
            $('#scheduler').kendoScheduler({
                date: new Date("2013/6/6"),
                allDaySlot: false,
                dataSource: [
                    {
                        id: 1,
                        start: new Date("2013/6/6 08:00 AM"),
                        end: new Date("2013/6/6 09:00 AM"),
                        title: "Interview"
                    }
                ]
            });
             
            resolve();
        });
    }
     
    detached() {  
        let scheduler = element.data('kendoScheduler');
        console.log(widget);

        console.log('detached called');
    }
};
</code>
</pre>


I believe the problem is here in the view.slot.js:

<pre lang="javascript"><code>
children.forEach(child => {

      var element = child.firstChild ? child.firstChild.nextElementSibling : null;
      if(child.firstChild &&
         child.firstChild.nodeType === 8 &&
         element &&
         element.nodeType === 1 &&
         element.classList.contains('au-animate')) {
        rmPromises.push(this.animator.leave(element).then(() => {
          child.removeNodes();
        }));
      } else {
        child.removeNodes();
      }
    });

    var removeAction = () => {
      if(this.isAttached){
        for(i = 0; i < ii; ++i){
          children[i].detached();
        }
      }

      this.children = [];
    };
</code>
</pre>
 
It seems that based on the logic above, the nodes are removed and then the detached method is called. This eliminates the ability to call element.data('kendoScheduler') which returns an instance of the kendo control in question which cannot be properly disposed now.

**Comment by EisenbergEffect** [comment]
This can't really be changed because it's meant to model Web Components behavior. It's also important for performance reasons. What I would recommend is that you store the instance of the kendo scheduler control in a property of your class and then use that later on to destroy things. That would also be slightly better performance-wise.

Another quick note: The attached callback doesn't support returning a promise, so you can remove that part from the code.

**Comment by gentledepp** [comment]
Hi! Integrating kendo ui is a key-concern for me. I tried to integrate kendo ui with durandal.js but failed although I was using http://rniemeyer.github.io/knockout-kendo/
Problem is, that I did not manage to get the templates of the kendo ui widgets to work with knockout bindings as that was not supported for all widgets by knockout-kendo, and so I implemented it myself.
Main problem of this approach was that knockout uses functions (observables) to get/set fields as you surely know.

So does anyone of you have an idea of how complex the integration with aurelia would be? (As kendo ui is partially open source supporting it would seem like a right step as cmichaelgraham also mentioned)

**Comment by tsjishan** [comment]
+10 Kendo integration with Aurelia

**Comment by JeroenVinke** [comment]
@tsjishan Keep an eye on [this plugin](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin). We are currently working on our first release, which will contain the Grid, Autocomplete, Menu and Button control. Parallel to this, we are working on documentation, so we can get wrappers for more controls out there faster.
