### ISSUE TITLE
Value not passed into activate outside of repeat.for

### ISSUE THREAD

**Issue by PWKad** [aurelia/templating-resources#10]
From user - souldrinker

I haven't learned to use the markup of Gitter properly so sorry about the format, but I have like this in my TypeScript model:

this.stuff = { id: boardId, view: "views/portal/board/board-model" };
this.stuffHolder = new Array<any>(this.stuff);

And then this works (board-model gets the id in activate):

<div repeat.for="stuff of stuffHolder">
<compose model.bind="stuff.id" view-model.bind="stuff.view"></compose>
</div>

...but this doesn't (board-model gets undefined in activate:

<div>
<compose model.bind="stuff.id" view-model.bind="stuff.view"></compose>
</div>

**Comment by Souldrinker** [comment]
I might have been a bit unclear about the issues in the chat yesterday, but I created a copy of the latest skeleton-navigation project with some added compose bindings and tried to explain what I did and what I expected to happen in the readme file there. It's my first time uploading something to GitHub (we usually use TFS at work), so I hope I've done things right: https://github.com/Souldrinker/compose-issue

**Comment by EisenbergEffect** [comment]
Thanks for catching that. It appears to have been an oversite. Probably the result of late night coding ;)
