### ISSUE TITLE
Iterating Map gives unexpected results

### ISSUE THREAD

**Issue by CharlesPockert** [aurelia/templating-resources#104]
When iterating a map with the following:

```
<li repeat.for="item of someMapProperty">
```

I'd expect that the map value would be placed into the local `item` property in the context of each repeat in the template. 

At worst I'd expect something to sit in the `item` local - maybe `item.key`/`item.value`, but it appears that when a binding context is generated `key` and `map` properties are created instead - this defeats the purpose of having a local in the `repeat.for` for Maps.

A more intuitive usage would be to push the value of the map item onto the local specified in the repeat and create a special `$key` property for maps (much like `$index` etc)

Something like:

```
createBaseExecutionKvpContext(key, value){
    var context = {};
    context[this.local] = value;
    context.$key = key;
    context.$parent = this.bindingContext;
    return context;
  }
```

This means usage is more intuitive:

```
<li repeat.for="item of someMap">
    Item: ${ item }
    <br />
    Key: ${ $key }
</li>
```

Though it looks like a tweak to `updateBindingContext(s)` may also be needed

Thoughts?

**Comment by jdanyow** [comment]
Need to be consistent with whatever the js equivalent- I think `for(let x of map)` results in `x` being an array (`[key, value]`).

The current version works like this:

```html
<template>
  <ul>
    <li repeat.for="[k, v] of map">${k} = '${v}'</li>
  </ul>
</template>
```
```javascript
export class App {
  constructor() {
    this.map = new Map();
    this.map.set(0, 'foo');
    this.map.set(1, 'bar');
    this.map.set(2, 'baz');
    
    for(var x of this.map) {
      console.log(x);
    }
  }
}
```

**Comment by jdanyow** [comment]
here's the plunker where I was testing the `repeat.for="[,item]" of map"` stuff:
http://plnkr.co/edit/wpJGlSxHXsq9sOAXQ2i3?p=preview

mdn had some good examples of iterating maps with for..of:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

**Comment by petrroll** [comment]
That makes sense. Is there any way to contribute to the documentation (would like to mention it there since while it's logical it's not really obvious)?

**Comment by jdanyow** [comment]
yep- please edit this file (and any of the other language files) and submit a PR:

https://github.com/aurelia/documentation/blob/master/English/docs.md

much appreciated!

**Comment by EisenbergEffect** [comment]
Closing this issues. Will look for a docs PR :)

**Comment by petrroll** [comment]
Ok, found out it actually is mentioned in the docs. Will think about how to improve it so people like me won't miss it (as I did).

**Comment by CharlesPockert** [comment]
Ah right missed this in the docs, @jdanyow is there any merit in having the framework warn or throw an error in the case that a single local is specified? Repeat does this if you get the syntax wrong for the `of` part

**Comment by petrroll** [comment]
Looking into the sourcecode I don't really see where such warning should (or even could) originate. It could theoretically be either in:

1. [processMapEntries()](https://github.com/aurelia/templating-resources/blob/master/src/repeat.js#L139) but then there'd be no way of distinguishing between people forgetting to specify their own variables and people specifying variables named 'key' and 'value'.

2. [SyntaxInterpreter.prototype['for']](https://github.com/aurelia/templating-binding/blob/master/src/syntax-interpreter.js#L162) but then syntax-interpreter would have to inspect product of `this.parser.parse(parts[1]),` (not 100 % sure) and based on its type look at `keyValue[0]` & `keyValue[1]` which hold variable names for key and value. And that feels like it's really too much of an implementation detail for SyntaxInterpreter.

Unfortunately these two modules communicate via binding (or it seems to me, didn't study the code thoroughly) so there's no other place where such check could occur.

**Comment by CharlesPockert** [comment]
@petrroll agree with 2, it can't be outside the repeat attribute as the check for `Map` is done inside after evaluating the bindings... however, I can't see anywhere the defaults for the "local name" properties are required so leaving `key`, `value` and `local` as undefined would allow a check just before `processMapEntries` (or in it) to see if `this.local` had a value. 

If it did we can assume the user specified a local rather than a `key`/`value` pair.

Here: https://github.com/aurelia/templating-resources/blob/master/src/repeat.js#L114

Could go something simple like:

 } else if (items instanceof Map) {
      if(this.local) throw new Error("Incorrect repeat form specified for Map - should be in the form [k,v] of mapProperty")   
      this.processMapEntries(items);
    } else if ((typeof items === 'number')) {

**Comment by petrroll** [comment]
Yep, removing the default values and then checking against them should work. Thought about that as well but wasn't sure the defaults are really not needed.

**Comment by CharlesPockert** [comment]
Tried and tested, seems to work ok with the rest of my app (which is quite repeat-heavy) working too
