### ISSUE TITLE
CSS loader and 404 CSS font URLs

### ISSUE THREAD

**Issue by bchavez** [aurelia/templating-resources#105]
Hi there,

I updated to the latest Aurelia dist. I'm using `<require from="bootstrap.css"></require>` inside my views. There seems to be a major issue with the CSS loader and font URLs.

Bootstrap and others usually use relative URLs for loading glyph resources. It turns out, using the latest distribution of Aurelia, I'm getting 404s for font resources.

For example, what I'm getting now:
```
http://localhost:11865/fonts/fontawesome-webfont.woff2?v=4.4.0
```
What I should be getting:
```
http://localhost:11865/pkg/github/lipis/bootstrap-social@4.10.0/assets/fonts/fontawesome-webfont.woff2?v=4.4.0
```

I think the problem stems from the CSS loader using `injectStyles` which loads the CSS inline. Ex:
```
<html>
    <head>
          <style>CSS content here... using url(../font) relative</style>
    </head>
</html>
```
Inline CSS URLs would be relative to the document in which the Aurelia app is mounted from; which in this case leads to the wrong relative path.

Instead, if we used:
```
<html>
    <head>
          <link rel="stylesheet" href="path to css on server" />
    </head>
</html>
```
**Link** will respect the *relative-ness* of the path defined inside the CSS.

Thoughts?

**Comment by EisenbergEffect** [comment]
We can't use link because that won't work either with shadow dom or with bundling. What we will have to do is use regex to patch up the style urls so they are based on the location that the styles were loaded from.

**Comment by EisenbergEffect** [comment]
Regex notes

```
let matcher = /url\(\'?\"?([\S]*)\'?\"?\)/g;
```

I think this will match all urls with parens and with or without single or double quotes. The capture group should allow replacement.

**Comment by EisenbergEffect** [comment]
I can reproduce the issue in the skeleton. I'll investigate using the technique above to see if I can get this fixed soon.

**Comment by bchavez** [comment]
No worries. Enjoy the weekend; and thanks, just glad you were able to reproduce the issue and log it as a bug. :+1:

**Comment by EisenbergEffect** [comment]
Almost got it I think. Regex isn't correct. That's not my strong point. Working on it now :)

**Comment by EisenbergEffect** [comment]
Pushed release out. Run `jspm update` to get v0.15.1

**Comment by bchavez** [comment]
Thanks @EisenbergEffect , updated and it's working :+1: . Thank you. I did see a significant bump in loading. FWIW:
![screen457](https://cloud.githubusercontent.com/assets/478118/9707661/c79bd928-54c3-11e5-9582-bbb7913d903c.png)

But I think this would only apply when the app it's not bundled.

**Comment by JamesReate** [comment]
Does this work automatically if in a view I do for example:
`<require from="summernote/dist/summernote.css"></require>`
ie. the regex will execute to replace the font src path? Or do i need do to something extra to tell aurelia to re-write the css font src...
