### ISSUE TITLE
Compose paths are working relative to src root instead of relative to the file in which they are used 

### ISSUE THREAD

**Issue by hobbit125** [aurelia/templating-resources#107]
This demonstrates the issue:
https://github.com/hobbit125/aurelia-compose-issues/tree/master/src

Specifically here:

https://github.com/hobbit125/aurelia-compose-issues/blob/master/src/pages/welcome.html

What's committed is working, but the path is written relative to the src root instead of relative to the file.

**Comment by EisenbergEffect** [comment]
Release coming in a just a minute...

**Comment by EisenbergEffect** [comment]
aurelia-templating v0.15.3 is released. You can use `jspm udpate` to get the fix. Apologies for the issue!
