### ISSUE TITLE
TypeError in repeat.js when iterating over an integer

### ISSUE THREAD

**Issue by reinholdk** [aurelia/templating-resources#108]
this.lastBoundItems is undefined and causes a TypeError in line 66 of repeat.js

```javascript
var splices = _aureliaBinding.calcSplices(items, 0, items.length, this.lastBoundItems, 0, this.lastBoundItems.length);
```

This happens when iterating using repeat.for="i of count" where count evaluates to an integer.

**Comment by EisenbergEffect** [comment]
@martingust Do you have time to look into this?

**Comment by martingust** [comment]
@EisenbergEffect can take a look tomorrow
