### ISSUE TITLE
Issue with binding `$index` in custom attribute in a `repeat.for` on incremental changes

### ISSUE THREAD

**Issue by peisenmann** [aurelia/templating-resources#109]
This is a very specific edge case. Reproduction plunk: http://plnkr.co/edit/fguuz4

After loading the plunk, three data items will be listed and a custom attribute will be bound up and attached to each. This works as expected. Three lines are displayed with correct indices and three log entries with correct indices.

5 seconds later, a timeout fires, adding a single item to the end of the data array. The index displays correctly on screen and is interpolated correctly into the `class` attribute on the element. However, the `$index` is bound as undefined as declared in the custom attribute.

Another 5 seconds later, another timeout fires that unshifts an item to the front of the list. All indices on screen are correctly updated, The bound $index inside the custom attribute is incorrectly undefined.

Finally, 5 more seconds later, the list is completely replaced. The indices are correct on screen and are bound correctly.

It appears to be only an issue for incremental changes.

**Comment by EisenbergEffect** [comment]
@martingust Can you take a look at this?

**Comment by martingust** [comment]
@peisenmann @EisenbergEffect Found the issue, will get a fix in.
