### ISSUE TITLE
Value appears to not be binding properly in compose

### ISSUE THREAD

**Issue by PWKad** [aurelia/templating-resources#11]
https://github.com/PWKad/skeleton-navigation

You see that welcome.html composes a modal and passes in a `showing` property which should be bound two-way between the two.  What I have noticed - 

1. If I bind to the value of `false` (a proper boolean) the value is definitely only one-way, unless I use it inside of a repeater.
2. If I bind to a random string value such as `'blue'` and test against that on the modal's show.bind I get an undefined is not a function error, but stepping through the debugger I can't figure out where it is being thrown.

**Comment by EisenbergEffect** [comment]
Ok. I believe one issue was in the framework. I just pushed a fix for that. But the other issue is in your code. You can't use compose to compose a custom element. You use that to compose plain view models. Your bug is coming from that. Remove the metadata and the error will go away.
