### ISSUE TITLE
HTML Extension "repeat" contextual values (ie. first/last/index) not updating.

### ISSUE THREAD

**Issue by aidesigner** [aurelia/templating-resources#110]
The code below seems to show an issue with HTML Extension "repeat" contextual values (ie. first/last/index). Note I added Aurelia debug technique view-spy to the anchor element. When the viewModel result in a longer myArray the variable "last" works correctly and view-spy shows stages created/bind/attached. Now if viewModel results in a shorter myArray then "last" is not true for any element, and view-spy shows stages detached/unbind. The key seems to be shorting the bound array does not go through the bind stage and thus the contextual values first/last/odd/even/index are not updated. Note the viewModel updates the array by setting length=0 and the inserting the new items..

Potentially related to the following issues:
https://github.com/aurelia/binding/issues/145
https://github.com/aurelia/templating-resources/issues/109

```
<!--View snippet-->
<li class="au-animate" repeat.for="row of myArray">
      <span style="display:flex;">
              <a view-spy class="" href.bind="row.href">${row.title}</a>
              <span if.bind="$last">***</span>
     </span>
</li>

// ViewModel snippet
onNavComplete(message: any) {
      this.myArray.length = 0;
     // Just know myArray becomes longer or shorter due to loop
      while (Something) {
             this.myArray.unshift(newItem);
       }
}
```

**Comment by martingust** [comment]
This will get fixed with https://github.com/aurelia/templating-resources/issues/112
