### ISSUE TITLE
$index in nested repeats behaves strange in Firefox

### ISSUE THREAD

**Issue by Souldrinker** [aurelia/templating-resources#111]
It seems like there's an issue with $index and Firefox. I have an ```<li repeat.for="subItem of item.items" if.bind="$index < 3">``` inside another repeat which works perfectly fine in Opera/Chrome/IE etc, but not in Firefox. In FF in my "real" app (TS/VS2015) it works fine until I run into an item.items list with more than three elements. Then it shows all (not only three) and in the following instances nothing is shown. I see no errors in the console.

I tried to recreate it in the skeleton app (0.18.1) where I just did an npm update/jspm update/jspm dl-loader and did some minor additions to the welcome.js/html files to test this out and got strange behavior (although slightly different) also here in Firefox, but not in other browsers.

The issue I get here is that it seems to ignore the $index and show all four subItems for the first item in Firefox, but only the three I expect in the other browsers (Chrome, Opera, IE11, Edge).

To recreate the issue just add this activate method to the welcome.js:
```
  activate(){
    var subItems1 = ['Sub1','Sub2','Sub3','Sub4'];
    var subItems2 = ['Sub5','Sub6'];
    this.items = [{id: 1, subItems: subItems1}, {id: 2, subItems: subItems2}];
  }
```
...and this at the end of the section element in welcome.html:
```
    <div>
      <ul>
        <li repeat.for="item of items">
          <span>${item.id}</span>
          <ul>
            <li repeat.for="subItem of item.subItems" if.bind="$index < 3">
              <span>${subItem}</span>
            </li>
          </ul>
        </li>
      </ul>
    </div>
```

**Comment by jdanyow** [comment]
Tested this with the master versions of binding, templating, templating-binding and templating resources...  still an issue.  Switching from if.bind to show.bind resolves the issue.  Works fine in edge, IE11 and chrome.

**Comment by Souldrinker** [comment]
Ok, thanks. Yes, show.bind did work, I'll use that instead then. I just got an update to Firefox 41.0 this morning, but the issue is still there with if.bind, but it works with show.bind.

**Comment by jdanyow** [comment]
still an issue in the latest build.  

chrome on left, firefox on right:
![issue](http://i.imgur.com/8DYi0rA.png)

**Comment by Gheoan** [comment]
related https://github.com/aurelia/templating/issues/123

**Comment by EisenbergEffect** [comment]
I believe it relates to the fact that ordering of attributes in the DOM is not consistent across browsers. So, in one browers the repeat attr is first and results in something that works, but in another browser the if is first and results in something that fails. That's just a guess.

**Comment by Gheoan** [comment]
Explaining this to myself here, it may help someone.
```html 
<template>
  <div>
    <ul>
      <li repeat.for="item of ['a']">
        <ul>
          <li repeat.for="subItem of ['a', 'b', 'c']"
              if.bind="$index === 0">
            <span>${subItem}</span>
          </li>
        </ul>
      </li>
    </ul>
  </div>
```

Chrome is is probably respecting attributes order of the view
`repeat` then `if === true` then `if === false` then `if === false`

`a`

 Firefox is probably sorting attributes alphabetically
`if === true` then `repeat`
```
a
b
c
```

**Comment by valichek** [comment]
Looks like I have related issue:
```
<th repeat.for="column of columns" if.bind="column.visible"></th>
```
good for Chrome (osx), and bad in Firefox (osx), no `<th>` added to DOM.

Here is a plunker
http://plnkr.co/edit/lUf9se?p=preview

**Comment by valichek** [comment]
having `if` synonym like `repeat-if` could be solution
like 
```
<th repeat-if.for="column of columns; column.visible"></th>
```
Strange? Sure

**Comment by EisenbergEffect** [comment]
You can't place two TemplateControllers on the same element. In this case `if` and `repeat`. They are both trying to control the creation of the th. It works in Chrome...accidentally...somehow. It should not work. To solve this, you should nest them. (Consider that the framework can't tell whether you want the whole list to be conditional or whether you want individual rows to be conditional.)

**Comment by devmai** [comment]
Good to know Rob. I have a slightly same issue.
My table row array look like `[10,10,10, , ]` So only the last column will not be appended into DOM. When last index got an value with 10 it will be rendered. Without last value only 4 <td>'s are there. Same issue in FF, Chrome and IE.

**Comment by valichek** [comment]
@EisenbergEffect yes, nesting is the best option, sometimes using `template` solves the problem, but not for `<table>`, so if not two TemplateControllers, having one `repeat-if.for` could be a good replacement
```
<th repeat-if.for="column of columns; column.visible"></th>
```

**Comment by stoffeastrom** [comment]
Wouldn't it be easier just using a `get` that filters out the visible columns?

```javascript
get columns() {
  return this._columns.filter( c => c.visible );
}
```

**Comment by stoffeastrom** [comment]
All depends on your use case I guess. Maybe you don't want to create new arrays like that

**Comment by valichek** [comment]
@stoffeastrom not sure about perfomance in cases when I have 1000s of rows and 10 columns, and I want to hide/show 1 row

**Comment by EisenbergEffect** [comment]
A quick fix would be to switch your `if.bind` to `show.bind` That still creates the div, but it will hide it if that value is false. That may be the most efficient mechanism for your scenarios. If you do have 1000s of rows, you may also want to check out our ui-virtualization library. It provides a `virtual-repeat` which only renders what is visible an provides virtual scrolling support over the full list. We've tested it at rendering 1million rows with 60fps smooth scrolling. It's still undergoing some critical work, but you could try it out and provide some feedback to us on that if it matches your scenarios.

**Comment by valichek** [comment]
The main problem here I have is that I need to use `<table>`, I need headers, I need content with scrolling and footer, and headers should be of same width as columns, and cannot find good solution with `divs`

**Comment by jdanyow** [comment]
closing- this was due to multiple template controllers on the same element (if and repeat).

**Comment by atsu85** [comment]
> this was due to multiple template controllers on the same element (if and repeat)

@jdanyow, could Aurelia throw an error in this case to fail fast and let the developer know, that there is a problem, instead of producing inconsistent results on different browsers?
