### ISSUE TITLE
repeat.for="..." does not work on a custom element node.

### ISSUE THREAD

**Issue by andyshora** [aurelia/templating-resources#114]
Using the repeat.for attribute on a custom element node in the view does not work.

Works
```
<p repeat.for="i of 10">works</p>
```

**Does not work**
```
<my-element repeat.for="i of 10"></my-element>
```

The error is coming from the binding file, so not sure if this is a bug with templating or binding.
```
ERROR [app-router] TypeError: Cannot read property '0' of undefined
    at getKeyed (http://localhost:9000/jspm_packages/github/aurelia/binding@0.9.1/aurelia-binding.js:2079:17)
zzz

**Comment by andyshora** [comment]
Ok, working. Problem was an array was being repeated over in the view, but it was a bound variable, and hence has an extra aurelia-generated key stuck on it (the observer)

Which is gonna cause lots of problems. Arrays get converted to objects when they are passed into custom elements via bindings.

Question is, is this still a bug to log here?

**Comment by EisenbergEffect** [comment]
What did you do to get it working?

**Comment by andyshora** [comment]
@EisenbergEffect wow thanks for the speedy reply!

The problem was when an array was passed into a custom element which had a @binding on it, it converts the array to an object and adds the __array_observer__ property, which throws an error when the view attempts to iterate it.

What would be the correct way to bind an array which needs iterating within a custom element?

**Comment by andyshora** [comment]
Solved. I wasn't referencing $parent inside the repeat :-/

Closing, and sorry!

**Comment by EisenbergEffect** [comment]
Glad you got it solved!
