### ISSUE TITLE
repeat.for bound to a map within an if.bind throws exception when re-binding

### ISSUE THREAD

**Issue by DarienFord** [aurelia/templating-resources#120]
The ```repeat.for``` binds correctly the first time, but if you are re-binding, for example if you are selecting a different item from a list, the follow exception is thrown the second time the ```if.bind``` evaluates to true:
```
Uncaught TypeError: Cannot set property '$index' of null
updateBindingContext @ repeat.js:268
handleMapChangeRecords @ repeat.js:392
bind @ repeat.js:81
bind @ aurelia-templating.js:2706
bind @ aurelia-templating.js:802
bind @ aurelia-templating.js:2710
bind @ aurelia-templating.js:802
valueChanged @ if.js:55
BindableProperty.createObserver.selfSubscriber @ aurelia-templating.js:2937
call @ aurelia-templating.js:2809
flushMicroTaskQueue @ aurelia-task-queue.js:110
(anonymous function) @ aurelia-task-queue.js:60
```

**Comment by jdanyow** [comment]
@DarienFord can you confirm you have templating-resources 0.16.1?
https://github.com/aurelia/templating-resources/releases/tag/0.16.1

You should be able to execute `jspm update` and get all the bug fixes from today.  There's one more coming in binding, unrelated to this issue though

**Comment by DarienFord** [comment]
Confirmed, 0.16.1 does not fix this.

**Comment by martingust** [comment]
We are doing some big refactoring of the repeater to make it pluggable. Plan is to get that and fix for this in by the weekend.

**Comment by martingust** [comment]
Fixed in https://github.com/aurelia/templating-resources/commit/1d96e6eea42760fa78580fce4f6b26fa57ed8ba3
