### ISSUE TITLE
repeat.for bound to an array does not bind correctly to an object upon re-bind within if.bind

### ISSUE THREAD

**Issue by DarienFord** [aurelia/templating-resources#121]
Similar to #120, in this scenario assume you have a list of objects which you want to choose between to see details.  The details view is within an ```if.bind```.
The first time ```if.bind``` evals to true, the ```repeat.for``` works.  The subsequent times, it does not evaluate the string interpolations.  

e.g.
```html
<div if.bind="selectedItem">
  <ul >
    <li  repeat.for="sample of templateSamples">${sample.TemplateName}</li> 
  </ul>
</div>
```

**Comment by EisenbergEffect** [comment]
Do you have the patch update from today for templating-resource?

**Comment by DarienFord** [comment]
I do. 0.16.1 does not fix this.

**Comment by jdanyow** [comment]
here's a repro for this issue and the [related issue](https://github.com/aurelia/templating-resources/issues/120):

```html
<template>
  <h1>Array</h1>
  <label><input type="checkbox" checked.bind="show">show?</label>
  <div if.bind="show">
    <div repeat.for="item of array">
      ${item}
    </div>
  </div>

  <h1>Map</h1>
  <label><input type="checkbox" checked.bind="showMap">show?</label>
  <div if.bind="showMap">
    <div repeat.for="[k,v] of map">
      ${k}/${v}
    </div>
  </div>
</template>
```
```js
export class App {
  array = ['foo', 'bar', 'baz'];

  map;

  constructor() {
    let map = new Map();
    map.set('foo-key', 'foo-value');
    map.set('bar-key', 'bar-value');
    map.set('baz-key', 'baz-value');
    this.map = map;
  }
}
```

**Comment by BringerOD** [comment]
Not sure if this is the same issue.  I have a compose report.for and if.bind or show.bind issue.  I have a sample project here.  
https://github.com/BringerOD/skeleton-navigation/tree/master/src

Note: It works half the time.  Meaning when I toggle the binding expression half the time it works.  
Note: None of it works in IE or firefox.  Not sure why.

**Comment by BringerOD** [comment]
I have checked the recent patch update and now it works,  just not in the latest IE and Firefox.

Should it work in other browsers?

**Comment by martingust** [comment]
Memory leak work in templating made this bug crop up. The repeater needs to handle things differently during unbind/bind. Will look Into a fix. #120 is related.

**Comment by martingust** [comment]
@BringerOD If your issue is the same it wont work in non of the browsers. Where in your repo can I look to reproduce it?

**Comment by BringerOD** [comment]
@martingust  Here it is.  https://github.com/BringerOD/skeleton-navigation

**Comment by BringerOD** [comment]
Now with the latest none of it works.  See comments here.

https://github.com/charlespockert/aurelia-bs-grid/issues/65

**Comment by martingust** [comment]
We are doing some big refactoring of the repeater to make it pluggable. Plan is to get that and fix for this in by the weekend.

**Comment by martingust** [comment]
Fixed in https://github.com/aurelia/templating-resources/commit/1d96e6eea42760fa78580fce4f6b26fa57ed8ba3
