### ISSUE TITLE
repeat.for Map confilcts with babel Map

### ISSUE THREAD

**Issue by olanod** [aurelia/templating-resources#122]
`repeat.for` allows iterating Maps by checking if the instance of the collection is `Map` but babel adds a wrapper around Map instances making `myMap instanceof window.Map != true`

**Comment by jdanyow** [comment]
@olanod I think disabling [`core-js` aliasing](https://babeljs.io/docs/usage/runtime/#core-js-aliasing) will resolve this for you.
