### ISSUE TITLE
Binding sequence problem with if.bind

### ISSUE THREAD

**Issue by sylvain-hamel** [aurelia/templating-resources#127]
I have this in my view:

```
<span if.bind="!value">(none)</span>
<div if.bind="value">
    <a route-href="route: users; params.bind: { id: value }">
      <div>${user.firstName} ${user.lastName}</div>
    </a>
</div>
```
When the `value` changes from something to `undefined` I get this error coming from `RouteRecognizer.generate()`

```
A value is required for route parameter 'id' in route 'users'.
```
It seems like the binding for `route-href` kicked in before `if.bind` could remove the `<a>` element. This is why the route recognizer got `undefined` in its `segmentValue` (which is my `value`).

**Comment by EisenbergEffect** [comment]
@bryanrsmith Can you take a look at this?

**Comment by jdanyow** [comment]
fix was merged
