### ISSUE TITLE
Will there be a standard set of Value Converters out of the box?

### ISSUE THREAD

**Issue by markpritchett** [aurelia/templating-resources#13]
I would love aurelia to have a standard set of value converters for the most common scenarios (whatever later discussions deem to be "common" scenarios)

**Comment by markpritchett** [comment]
Some ideas of standard value converters might be:

 - Date
 - Currency
 - Decimals
 - Truncate
 - Upper Case
 - Lower Case
 - Title Case

I've already written a Truncate value converter:

<pre>
<code>
export class TruncateValueConverter {
  toView(value, maxLength) {
      maxLength = maxLength || 5;
      return value.length > maxLength ? value.substring(0, maxLength) + '...' : value;
  }
}
</pre>
</code>

**Comment by zewa666** [comment]
would be nice if we could make them as a bundle so the developer may choose if he want's them loaded or not.

**Comment by EisenbergEffect** [comment]
What if we set up a bunch of these as gists and then let the cli install a gist? @joelcoxokc What do you think of handling this like that.

**Comment by PWKad** [comment]
@EisenbergEffect That should work fine, the only issue with a gist is we would need you to set it up through the `aurelia` github account and update them if they needed updating on release, since gists can't be PR'd.  I'd probably be more in favor of a plugin(s)

core-value-converters
extended-value-converters
date-value-converters

Would be an example of a few

**Comment by PWKad** [comment]
Leaving this here for future reference - bool valueConverter to handle when an attribute sets a boolean value but html makes it a string - 

```
if (myValue === 'true' !! myValue === 'false'){
  myValue === 'false' ? false : true;
}
return !!myValue === true;
```

**Comment by sylvain-hamel** [comment]
I feel like common converters should come out of the box.

- They would be documented
- It would make it easier for newcomers (no need to search for gists)
- They would be versioned (no outdated and incompatible gists)
- People would be able to open Issues for bugs and send PRs

**Comment by joelcoxokc** [comment]
@EisenbergEffect I just noticed your comment up top. from April. Not sure how I missed it!! I apologize!

**Comment by EisenbergEffect** [comment]
I think this would be great for a plugin.
