### ISSUE TITLE
Changing the view attribute of the compose element causes view-model to be reset

### ISSUE THREAD

**Issue by AshleyGrant** [aurelia/templating-resources#136]
When I set both the `view` and the `view-model` attribute of the `compose` element, the view-model instance shouldn't be reinitialized when the `view` attribute changes.

This can be reproduced in the skeleton project by copying `welcome.html` to `welcome0.html` and then adding the following code to one of the other views:
```html
  <input type="checkbox" ref="useSecondView" /><br />
  <compose view-model="./welcome" view="./welcome${useSecondView.checked ? '2' : ''}.html" ></compose>
```

Change the value of the First Name text box, then check the checkbox to swap the view. The value in the First Name text box will revert back to its default value.

**Comment by EisenbergEffect** [comment]
Looks like this was fixed a little while back :)
