### ISSUE TITLE
au-class

### ISSUE THREAD

**Issue by yelvert** [aurelia/templating-resources#14]
I have created a simple ng-class style behavior

`<div au-class.bind="{active: active, inactive: !active}"></div>`

```
import {Behavior} from 'aurelia-templating';

export class AuClass {
  static metadata(){
    return Behavior
      .attachedBehavior('au-class')
      .withProperty('value', 'valueChanged', 'au-class')
    ;
  }

  static inject() { return [Element]; }
  
  constructor(element) {
    this.element = element;
  }

  bind () {
    this.valueChanged(this.value);
  }

  valueChanged(newValue){
    Object.keys(newValue).forEach(className => {
      this.element.classList[newValue[className] ? 'add' : 'remove'](className);
    });
  }
}
```

I would love some feedback as to whether this is the right way to do this, and also how it could be changed to support the above way as well as `<div au-class.bind="myClasses"></div>` where myClasses is a plain object (currently this doesn't fire `valueChanged` when `myClasses.someProperty` changes, `valueChanged` is only fired when the `myClasses` becomes a completely new object).

If interested, I'll create a PR for this and enhancements can be done there.

**Comment by zewa666** [comment]
The skeleton app already provides a way to setup class via properties. Take a look at the nav-bar.html with following code:

```
<li repeat.for="row of router.navigation" class="${row.isActive ? 'active' : ''}">
```

What would your Behavior do different?
I've also tested your Code and the initial binding via an object works but as you mentioned not the updates. So means that the binding is not performing a deep inspection of your object. Maybe you should file this as an separate issue.

**Comment by yelvert** [comment]
For a single class, or toggling between 2 classes, interpolation is fine, but for more than that it gets to be a pain, and rather ugly to have `${x.y ? 'someClass' : ''}` 3 or 4 times in a single element. Admittedly, its rare that it is needed for that many, but even for 1 or 2 classes, this is cleaner.

**Comment by yelvert** [comment]
I have changed around the AuClass behavior to support the above mentioned bindings as well as another.
https://gist.github.com/yelvert/0c66cb34f1d1ff6c3ea2

**Comment by yelvert** [comment]
Closing this issue for now since it has been added to https://github.com/joelcoxokc/aurelia-interface
