### ISSUE TITLE
Support ES6 Set in repeat

### ISSUE THREAD

**Issue by rquast** [aurelia/templating-resources#142]
Repeat supports ES6 maps, but it doesn't support ES6 sets. Can support for this be added?

**Comment by jdanyow** [comment]
yep- coming soon!
https://github.com/aurelia/templating-binding/issues/34

**Comment by martingust** [comment]
Implemented here https://github.com/aurelia/templating-resources/commit/dc0432a00920ee2f3b9fc44a6d0955f868d679a8
