### ISSUE TITLE
repeat.for Removing last element in array throws error

### ISSUE THREAD

**Issue by spi-ap** [aurelia/templating-resources#147]
Deleting the last element in an array throws an error (tested in chrome, templating-resoures@0.17.1).
The last element will not be removed (visually).

Error message: 
`Uncaught TypeError: Cannot read property 'firstChild' of undefined`

Here is a plunk: http://plnkr.co/edit/ZSXEB5?p=preview

(No value converters etc. used)

**Comment by martingust** [comment]
Bug in binding repo. Will get a fix in shortly.

**Comment by martingust** [comment]
@spi-ap This is fixed and released.
