### ISSUE TITLE
repeat.for + if.bind do not work

### ISSUE THREAD

**Issue by Exsilium122** [aurelia/templating-resources#148]
With this release of pre beta Aurelia has introduced a bug. Where can I find already listed bugs or where can I submit one? There are so many modules of the aurelia and I am not sure which one is causing the problem. I guess it is reapeat.for bug.
The problem: I display all elements of the array using rapeat.for two times. Eachlist can be hidden. One with if.bind, second with show.bind. After toggling them only show.bind list is visible. Toggling can be done with checkbox.

This is a working example: http://plnkr.co/edit/fVKHYsGauQB42jBPjj1W?p=preview
All the code is in that example.

**Comment by jdanyow** [comment]
Please update to the very latest (released last night).  It will fix the issue:

http://plnkr.co/edit/WrSbjzdnnONGu0ixvO4k?p=preview
