### ISSUE TITLE
InnerHtml binding broken in IE9?

### ISSUE THREAD

**Issue by philiphendry** [aurelia/templating-resources#152]
I've been doing some browser testing and have discovered that I can't get IE9 innerHtml binding to work. Specifically if I modify a basic application and add the following to `app.js`:

```
  plainText = "This is plain text";
  formattedText = "This is <b>formatted</b> text";
```

and then the following to `app.html`:

```
  plain : <div>${plainText}</div>
  innerText : <div innerText.bind="formattedText"></div>
  innerHtml : <div innerHtml.bind="formattedText"></div>
```

Then in Chrome/Firefox/IE11/IE10/Edge I see the plain text and html formatted text rendered fine. Interestingly I don't see the innerText but kinda expected it?!

However, if I switch IE11 to IE9 emulation I get the plain text but not html formatted (the `innerHtml.bind` doesn't work.) Unexpectedly the `innerText.bind` does work!

I came to debugging this because the `npm:sanitize-html` I had installed wouldn't work in IE9 - something to do with the node buffer not being injected into the string encoder ... but that's a different problem for another day :( 

Any clues to why innerHtml doesn't bind?

**Comment by ZapMyR** [comment]
`innerHTML` and IE (at least older versions) is a story of its own. It never worked properly and produced all kinds of weirdness. As far as I know it can only be properly used by directly working on the DOM and it might need an extra fallback implementation to correctly apply bindings from aurelia.

If you really need it I'd recommend implementing a custom attribute specially for this case á la IEinnerHTML so you can properly bind to it until there is an official solution provided.

**Comment by philiphendry** [comment]
Thanks @ZapMyR. I've written a very basic custom attribute which will work for me at the moment. I'll need to properly sanitise my HTML at some point but here's the code I'm using:

```
import {inject} from "aurelia-framework";

@inject(Element)
export class HtmlCustomAttribute {
  constructor(element) {
    this.element = element;
  }

  valueChanged(html) {
    var SCRIPT_REGEX = /<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi;
    while (SCRIPT_REGEX.test(html)) {
      html = html.replace(SCRIPT_REGEX, "");
    }
    this.element.innerHTML = html;
  }
}
```

I took the basic sanitisation from the [InnerHTML attribute](https://github.com/aurelia/templating-resources/commit/f6e28fe1e7e37b4f4b60ec066dddaff18dc6912b) and if I can figure out the attached behaviour code I'll extend further (since that regex sanitisation is probably as worthwhile as a chocolate teapot!)

Do you know if there will be an official solution for this?

**Comment by jdanyow** [comment]
@philiphendry it looks like your attribute is doing the same thing that the innerhtml binding does... assigns the element's `innerHTML` property.

What happens if you change your bindings from 
```js
<div innerText.bind="formattedText"></div>
<div innerHtml.bind="formattedText"></div>
```

to:

```js
<div textcontent.bind="formattedText"></div>
<div innerhtml.bind="formattedText"></div>
```

*note:  the attributes are in lowercase... the DOM automatically lower-cases all html element and attribute names*

http://aurelia.io/docs.html#innerhtml

**Comment by philiphendry** [comment]
@jdanyow, I shall hang my head in shame. That works and now that you've pointed out the docs it's clear as day.

**Comment by jdanyow** [comment]
ha- no worries- glad it's working!

**Comment by ZapMyR** [comment]
Oh nice, thanks for the hint - didn't know it already existed ^^
