### ISSUE TITLE
Signal binding behavior - error when inside if.bind

### ISSUE THREAD

**Issue by zebrooks** [aurelia/templating-resources#157]
When an element containing a binding with a signal is removed from and/or readd to a view (using an if.bind or similar) an error is thrown:
* Remove: `ReferenceError: signals is not defined`
* Readd: `Error: A binding behavior named "signal" has already been applied to ...`

Seems to be fixed by changing
```
let bindings = signals[name];
```
to
```
let bindings = this.signals[name];
```
on this line https://github.com/aurelia/templating-resources/blob/master/src/signal-binding-behavior.js#L27

**Comment by jdanyow** [comment]
thanks @zebrooks !
