### ISSUE TITLE
repeat: <template> with repeat- and if binding scope error

### ISSUE THREAD

**Issue by CasiOo** [aurelia/templating-resources#158]
The repeat binding seems to not play nicely with the template tag, when both a repeat- and if binding are present.
It's like the repeat scope is forgot about/never added. If you have nested loops, it will use the scope from the previous repeat instead.

Ran into the problem while coding a recursive tree structure

Recreating the issue:
```
<template>
    <template if.bind="show" repeat.for="element of elements">
        ${$index} - ${element}
    </template>
</template>
```
```
export class Welcome {
  show = true;
  elements = ['test'];
}
```

Expected view: `0 - test`
Actual view: `-` (just a dash)

Change the template tag to a div, and it outputs the expected result.

**Comment by EisenbergEffect** [comment]
You cannot use two template controllers on the same element/template. They will conflict with one another. Both if and repeat are template controllers. To solve this issue, use nested template tags, one with the repeat and then one with the show. The order of nesting does matter.

**Comment by CasiOo** [comment]
Thank you for the quick response :+1:
