### ISSUE TITLE
Correct relative CSS urls without period directory references

### ISSUE THREAD

**Issue by fmmich** [aurelia/templating-resources#163]
In app.html, if you require a module's CSS that includes a `url` reference, like for an image or a font, Aurelia does not determine the relative path if the link does not contain a period or double-period directory reference.  For example, in the module's CSS,

    background-image: url('images/background.jpg');

will not be translated, causing the application to look for an images directory in the root, but

    background-image: url('./images/background.jpg');

will correctly be translated, causing the application to look in the images directory relative to the module's js.  The problem can be "patched" in the `fixupCSSUrls` function of css-resource.js (https://github.com/aurelia/templating-resources/blob/master/src/css-resource.js#L16) by replacing

    return 'url(\'' + relativeToFile(p1, address) + '\')';

with

    return 'url(\'' + relativeToFile('./' + p1, address) + '\')';

However, I'm hesitant to perform a pull request here if the problem should be really be corrected in the `relativeToFile` function of https://github.com/aurelia/path/blob/master/src/index.js#L34 without breaking any of its other callers.

**Comment by jdanyow** [comment]
I think the `./` is required for relative urls.  Items without `./` could be an installed dependency eg `bootstrap/css/bootstrap.css`, the `./` helps make the distinction and keeps things explicit.

Closing- @EisenbergEffect please re-open if I have this wrong.
