### ISSUE TITLE
Add decorator indicating behavior doesn't need lifecycle

### ISSUE THREAD

**Issue by jdanyow** [aurelia/templating-resources#164]
Forked from https://github.com/aurelia/binding/issues/242#issuecomment-164303196 

One of the recent optimizations to the `repeat` template controller was to skip the composition lifecycle (detach, unbind, bind, attach) when the data backing the repeat changes. This optimization is enabled when the repeat's template doesn't use animation, and doesn't have any custom attributes or custom elements that use the lifecycle callbacks or are behaviors known to not require the lifecycle callbacks when the binding context changes. Known behaviors are tracked in [this list](https://github.com/aurelia/templating-resources/blob/master/src/analyze-view-factory.js#L5).
   
This issue is to add a html behavior decorator that will add the behavior to the list of behaviors that don't require lifecycle callbacks when the binding context changes.

Few details to nail down:

1. Should we switch the list from strings to types?
2. Struggling to think of a good decorator name...
  `@enableRepeatOptimizations` too specific?
  `@lifecycleOptional` not specific enough? 
  something else?
3. Should the decorator live in the templating repo (eg do we need to move [this code](https://github.com/aurelia/templating-resources/blob/master/src/analyze-view-factory.js) to templating first)?

**Comment by CasiOo** [comment]
Would `@OptionalTemplateLifecycle` be a fitting name?

**Comment by jdanyow** [comment]
closing, not needed.
