### ISSUE TITLE
repeat.for: exception thrown during splicing of array ("Cannot read property 'firstChild' of undefined")

### ISSUE THREAD

**Issue by ohjames** [aurelia/templating-resources#165]
My site has an array of like the "top 20 scored posts" and reads posts from many sources. As new posts come from different sources the array get spliced/unshifted as you'd expect. After I added four sources I started getting exceptions:

```javascript
  function getAnimatableElement(view) {
    var firstChild = view.firstChild;
```

Here `view` is `undefined`. Here's the stack:

```
getAnimatableElement	             @	aurelia-templating.js:1096
removeAt	                         @	aurelia-templating.js:1247
_standardProcessInstanceMutated	   @	array-repeat-strategy.js:109
instanceMutated	                   @	array-repeat-strategy.js:91
handleCollectionMutated	           @	repeat.js:113
call	                             @	repeat.js:65
callSubscribers	@	aurelia-binding.js:219
call	                             @	aurelia-binding.js:715
flushMicroTaskQueue	               @	aurelia-task-queue.js:110
(anonymous function)	             @	aurelia-task-queue.js:60
```

**Comment by ohjames** [comment]
Tracked the issue down to here:

```
    ViewSlot.prototype.removeAt = function removeAt(index, returnToCache, skipAnimation) {
      var _this = this;

      var view = this.children[index];
      if (! view) {
        console.log('view overflow', index, this.children.length)
      }
```

I added the `if (! view)` code there. There it passes an index of `14` and yet the length of the array is `14` so it retrievews a null element. From there everything goes wrong.

**Comment by ohjames** [comment]
When I log it and just `return` after the overflow... I see many overflow messages logged, and I also see that the final item is missing from the `repeat` (not matter how many times the message is logged, it's always one item missing at the end).

**Comment by ohjames** [comment]
It seems elements go missing from my array at some point, the `removeAt` `index` parameter then overflows the end of the array due to the missing elements. The missing elements don't correspond to the elements which should be removed unfortunately, if you ignore the overflows the view doesn't correspond to the state of the array.

**Comment by ohjames** [comment]
Okay, so splices/removes are interleaved in my application, after each tick aurelia-template usually plays back all the removes followed by the splices.

However when it plays back the splices followed by the removes, then for each remove that occurs I lose an element from the end of the array.

From that point on the view is out of sync with my array and chaos reigns ;) :baby_chick:

**Comment by ohjames** [comment]
Hm it seems to be more complicated than that, sometimes I seems elements in my array never get entered into the view, othertimes it seems elements get entered into the view then deleted when an array splice is registered twice. I've been debugging for hours but this issue is super tricky.

**Comment by EisenbergEffect** [comment]
I think we have this fixed in master. There's a patch release coming today. Hang out a bit longer and then try that to see if your problem goes away. If not, we can pick up here and see what the issue is.

**Comment by ohjames** [comment]
@EisenbergEffect I checked out aurelia-{binding,template,template-resources} commits but can't see any relevant fixes (I'm not using reverse/sort), maybe I missed something.

The updates here work even less well without the recent changes to animator-css, I have a feeling more changes might be needed there to fix this.

**Comment by ohjames** [comment]
Disabling animations (by removing the au-animate class on my repeater) avoids the issue. When the animations are enabled it's like one or two of the four change sets (each one happening in a single tick) get lost. Although the consequences go beyond that change set missing and also lead to the order of elements in the view not matching those in the array when accounting for the missing changesets.

This could be a bug with `animator-css` then, but not 100% sure on that.

I put some logging in the code and I see many of the `enter animation end` events go missing. I think maybe when the elements get moved around the view their `animationEnd` event fails to trigger.

I'd probably put a warning in the docs about the issues with `animator-css` and `repeat.for` combined. I don't think the combination is beta-quality yet. Before the recent changes to `animator-css` this combination of features was so broken it was easy to trigger bugs with the view state, now it's still easy if less so.

**Comment by EisenbergEffect** [comment]
Have you tried pulling down the master for animator-css? There is a major bug fix in that going out today as well. What you are reporting sounds similar to what was fixed.

**Comment by ohjames** [comment]
Okay the issue is *definitely* to do with missing the `animationend`/`webkitAnimationEnd` event when elements leave the page. I think it's triggered by a certain combination of splices to the underlying array during a leave animation.

It's also worth pointing out that this also affects detecting the same events on the `enter` event, (so the user wouldn't be able to rely on the API there... definitely worth documenting that for now). This event isn't used by the templating layer though so it shouldn't affect this issue.

It may be the event goes missing because the element is removed from the page? If that's the case, the fix shouldn't be too difficult.

**Comment by ohjames** [comment]
@EisenbergEffect Yeah I'm using the latest `animator-css`, I was the one who wrote that fix ;) Without it this issue is even worse.

**Comment by EisenbergEffect** [comment]
Doh! Sorry. I didn't realize this. So, you think this basically amounts to an issue with the animator again? I'm going to make a patch release today, with what we have. I can easily make another patch release at-will if you can help us track down and fix the issue. Thanks for drilling into this!

**Comment by ohjames** [comment]
@EisenbergEffect I think the error might be here: https://github.com/aurelia/templating/blob/master/src/view-slot.js#L204

The code waits for the "leave" animation to complete before splicing the `children` array. However inserts may occur against `children` while the animations are playing, if the inserts are at a lower index than the removal position then the splice will refer to the wrong elements.

Or maybe I'm reading things wrong, github shows me you wrote that bit of code so I'd really appreciate your input.

**Comment by ohjames** [comment]
Hm, that theory is wrong... but it could still be due to the timing there, maybe subsequent inserts pass an idx relying on the `leaving` elements already having left.

**Comment by EisenbergEffect** [comment]
The best people to address this issue today would be @martingust and @jdanyow They have the most recent experience working with the repeater.

**Comment by ohjames** [comment]
Discovered the issue now, opened the more coherent #167 with the information and closing this one.
