### ISSUE TITLE
repeat.for: loses sync between array and view when array updates happen during leave animation

### ISSUE THREAD

**Issue by ohjames** [aurelia/templating-resources#167]
When events are removed from the view, they remain in viewSlot.children until the animation completes, see https://github.com/aurelia/templating/blob/master/src/view-slot.js#L204

The `removing` state is accounted for here during the mutation: https://github.com/aurelia/templating-resources/blob/master/src/array-repeat-strategy.js#L115 (by taking into account `rmPromises.length`, this works as the splices are ordered).

Say this animation takes 1 second, and 200ms later an insert happens at the end of the array. At this stage `viewSlot.insert` is called with the index of the item in the array, yet the index within the `viewSlot` is different due to the animations not having completed (`viewSlot.children` now has a different number of elements to the array). Now `rmPromises.length` can't be used to factor in the indexes of the removed items from a previous set of splices and the indexes are all wrong.

This leads to the view going badly out of sync with the array, this is particularly bad if you are using say `splice(idx)`. This can end up splicing elements off of the end that should not be removed, then a later update can supply an index that should exist within `viewSlot.children` but doesn't, throwing the exception `Cannot read property 'firstChild' of undefined`.

**Comment by ohjames** [comment]
Calling @EisenbergEffect @martingust @jdanyow this is a serious issue with `repeat.for` affecting all `animator` libraries. It will affect any user where arrays update during animation leading to extremely bad results.

**Comment by ohjames** [comment]
The `+ rmPromises.length` correction factor also bothers me. I can see how it works to fix the offset of splices at a higher index, but what if the first splice is at a higher index than the second splice... in that case wouldn't the `+1` incorrectly be applied to the second splice (at the lower index)? It seems to me it should only affect splices at a higher index, (and after being corrected for intermediate additive spices). Would really appreciate some feedback on that point.

**Comment by EisenbergEffect** [comment]
@martingust @jdanyow Can you guys work s with @ohjames to see if we can resolve that. We may also need help from @zewa666 if this involves the css animator. You all know more about this code than I do at this point...

**Comment by martingust** [comment]
@ohjames I think you are right, the `rmPromises` should only affect splices at a higher index. Do you have an example project or plunker that shows the issue you described, that would help a lot to fully see the problem. 

However when trying this out I think I have found a related (or same) bug. 

Let's say I have an array of 4 items: `array = ['foo', 'bar', 'baz', 'qux'];` bound to a `repeat`.

Then trigger a splice, `this.array.splice(2, 1);` with a remove animation of 5 sec, then trigger the same splice again, within the 5 sec. This scenario should remove `baz` and then `qux`, but since `baz` is still in the `viewSlot`, it will incorrectly remove `baz` twice. 

Here is a plunker with this scenario: http://plnkr.co/edit/6JwgTr3ftzOx5Z8Alebp?p=preview

**Comment by ohjames** [comment]
I'm working on a small test for this now. I want to add some unit tests to `aurelia-templating-resources`, but first I'm adding some visual tests in a modified `aurelia-skeleton-app` to see if/how the splices are modified before making it to the array repeat strategy.

I've already tested `rmPromises` issue and it seems that it never breaks, this leads me to believe that the splices are re-ordered before they get to this point so that the lower indexes always come first. I think this process also coalesces the splices, given that the code processes removes before inserts, you'd expect removing an element in the same tick that it is added might lead to an orderering error and the wrong elements removed.

Any idea where this process happens? I think one approach to fix this might be:

1. On insert, if there is a pending animation wait until it has finished and queue the splice.
2. After animations have finished, if there are queued splices then coalesce them and apply them.

I also wonder if maybe there's an alternative... could `viewSlot.children` be changed before the animation completes rather than after (and remove the `rmPromises` correction factor?)

**Comment by ohjames** [comment]
Okay I've added a repository to demonstrate the issue. It uses all the dependencies from yesterday's patch release (the animator-css fix is key, otherwise this is even more broken). Anyway, here's the test repository:

https://github.com/ohjames/aurelia-bugs

Here's the key bit:

https://github.com/ohjames/aurelia-bugs/blob/master/src/welcome.js#L10-L24

The `leave` animation lasts 0.8 seconds.

**Comment by ohjames** [comment]
Running it here: http://chilon.net:9040/

You can see what's happening clearly with the visuals, the C is animated in during the removals of 'a, and 'c', so the index is wrong.

The error manifests for me in chrome but no in firefox. Not sure why at the moment. Maybe because chromium is using `Object.observe`?

**Comment by ohjames** [comment]
Correction: just as broken in firefox. Forgot `animation` to go with the `-webkit-animation`.

**Comment by martingust** [comment]
Awesome, thanks for the example project @ohjames. I think this and the issue I described could be solved by storing `rmPromises` on the repeat instance and clear it [here](https://github.com/aurelia/templating-resources/blob/master/src/array-repeat-strategy.js#L125) when the animations are finished. The second round of splice will then know if an animation is in progress and if so compensate and wait. But then `rmPromises` definitely need to only affect removed views with a higher index. This would need more testing though, I have only made some quick tests on these two scenarios.

**Comment by ohjames** [comment]
@martingust ATM `rmPromises.length` correction always works due to the normalise/coalesce process that happens before this code is called. If you have to wait on the `rmPromises` promise before applying a new set of splices then you'll need to normalise/coalesce the new splices following the same process so that the `rmPromises.length` correction can still work. This is probably for the best anyway... there's no need to replay additions that will be removed right after etc. I'm about to submit a PR with a test for this stuff.

**Comment by ohjames** [comment]
There added a PR with the test now. I'm working on a fix also which hopefully I'll push tonight in the same PR. If anyone could point at where the splice normalise/coalesce phase takes place that would be great :baby_chick:

**Comment by ohjames** [comment]
Closing this one due to my fixes but opening a very similar and very serious issue that manifests similar (but not quite as obvious and catastrophic) desync issues to this one.
