### ISSUE TITLE
Bug when using aurelia's <compose> element and binding to an existing viewmodel

### ISSUE THREAD

**Issue by lynchd6-emc** [aurelia/templating-resources#17]
This [gist](https://gist.github.com/lynchd6-emc/6d1287a58d86ab4c9731) demonstrates a bug when using aurelia's *compose* element and binding to an existing viewmodel

There is an exception thrown in BehaviorInstance when creating the custom element (which I assume is the Compose element). The root of the error is that the custom element doesn't have am observerLocator property.

So this:

```javascript
// custom-element.js
  create(container, instruction=defaultInstruction, element=null){
    var executionContext = instruction.executionContext || container.get(this.target),
        behaviorInstance = new BehaviorInstance(this, executionContext, instruction),
        host;
```
calls this:

```javascript
// behavior-instance.js
export class BehaviorInstance {
    constructor(behavior, executionContext, instruction){
        this.behavior = behavior;
        this.executionContext = executionContext;

        var observerLookup = behavior.observerLocator.getObserversLookup(executionContext),
```
which throws: "Cannot read property 'getObserversLookup' of undefined".

Is binding to an existing, already created view model supported?

```html
<compose view-model.bind="selectedViewModel">)
```

**Comment by matthy123** [comment]
I get the same error I think, see https://gist.github.com/matthy123/ce63170bcaa677da2384
I try to mimic the behaviour from Caliburn.Micro, but unfortunately it doesn't work.

**Comment by lynchd6-emc** [comment]
After much debugging I've determined that the root cause of this issue is that a view model that is created in a parent view model (instead of by the template+binding mechanism) is not processed by the ResourceCoordinator and thus has no ViewModelInfo.  

I've updated the [gist](https://gist.github.com/lynchd6-emc/6d1287a58d86ab4c9731) with a hacked copy of the Compose element (called Composer) that I use that calls the ResourceCoordinator for my locally created view model.  But I'm not sure what the best way for the framework to implement this fix.

**Comment by EisenbergEffect** [comment]
This stems from the fact that we can't currently tie into the ES6 loader in the right way to tag it with the module id we need for convention-based view location. I've submitted an issue to WHATWG in their loader repo and I'm hopeful that we can improve the standard before it is finalized. If that happens, this problem will go away. If not....we'll have to get creative.

I'll leave this issue open so I can report back on it. In the mean time, I recommend explicitly setting the `view` property on compose when you have an existing view model. Bear in mind that this can be bound, so you can use it to calculate different views based on the information you have.

**Comment by EisenbergEffect** [comment]
We *should* be able to make this work automatically in the future....however we are waiting on some additions to the ES6 loader spec as well as updated implementations of the polyfills. Until then, you will need to specify the view manually or databind it based on some property of your view model.

I'm keeping this issue open so I can update it once we finally get the capability in the ES6 spec and implementation. It should happen..we are just waiting on the external dependency.

**Comment by matthy123** [comment]
thanks for the update, would love seeing the view model binding in the future, that is what made your silverligth framework so incredibly strong!

**Comment by davismj** [comment]
I am seeing the same thing through a slightly different path, using the compose element as follows:

```html
<compose view="views/${currentView}.html"></compose>
```

First binding works great. Changing the `currentView` element results in the above error. FYI.

**Comment by EisenbergEffect** [comment]
Yes. The problem is that currently the ES6 loader spec doesn't support what we need to make this work 100%. They are supposed to be adding a module registry feature which would enable us to fix this. Can't do it until that is done and the polyfill is updated.

**Comment by EisenbergEffect** [comment]
The spec is still being developed, but guy gave me a workaround for module iteration using a private api for the mean time:

```javascript
for (var m in System._loader.modules) {
  System._loader.modules[m].module
}
```

**Comment by simonfox** [comment]
@EisenbergEffect does this mean this is available in the latest release via this workaround?

**Comment by EisenbergEffect** [comment]
The above fix has not yet been applied. I'm going to try to get it into the next release along with a few more core improvements.

**Comment by simonfox** [comment]
@EisenbergEffect cool thanks Rob

**Comment by EisenbergEffect** [comment]
Another note related to supporting require.js with the same feature. Notes from James:

There is no official API for this, but the internals to the set of export values at `requirejs.s.contexts._.defined` for the default context. Since this is getting into the internals, its API stability is not guaranteed. I have no plans to change it for 2.1.x, but also do not guarantee that. For almond its internal `defined` object is not exposed publicly, but you could fork that project and make it visible in that fork.

**Comment by EisenbergEffect** [comment]
Going out in the next release. This hasn't been tested with require.js. It does work with system.js. If you are using require.js, almond or dojo's loader, then please reach out and assist us in confirming that this works in those cases.

**Comment by simonfox** [comment]
:+1: thanks @EisenbergEffect!!

**Comment by davismj** [comment]
confirmed, works with my application

**Comment by Santosh-9890** [comment]
@EisenbergEffect 

Hello,
From last few days I’m facing one issue in promises while using Charles pocket grid.
Here is the screenshot of issue,

![image](https://cloud.githubusercontent.com/assets/11840497/10039928/6d576642-61f4-11e5-9e5f-58e35d427cb1.png)
