### ISSUE TITLE
No possibility to use multiple signal names

### ISSUE THREAD

**Issue by niieani** [aurelia/templating-resources#170]
@jdanyow asked for a use case, so here's an example:

HTML (`task.html`):
```html
<div if.bind="tags | containsTag: 'test' ">
    (...)
</div>
```
There are two things that can trigger a change of the `tags` property in the view model - either the `task` gets changed (somebody adds or removes a tag in it's view-model) or somebody renames one of the existing tags globally. In both of those instances I would like the binding to get reevaluated, because its value might have changed. I can send out signals in both instances (i.e. a signal for the specific task changing it's tags and a global app signal for the changes in tags). Therefore I'd like to be able to specify multiple signal names, lets say something like:

```html
<div if.bind="tags | containsTag: 'test' & signal: [ 'global-tags-renamed', 'task-change-' + id ] ">
    (...)
</div>
```

Now the binding should get reevaluated when either of those signals gets sent.

**Comment by EisenbergEffect** [comment]
@jdanyow Couldn't the signal behavior be used multiple times?

**Comment by niieani** [comment]
@EisenbergEffect No, this gives an error `A binding behavior named "signal" has already been applied`.

**Comment by EisenbergEffect** [comment]
@jdanyow Would it be possible to make multiple instances of signal possible? If not, could we enable the signal behavior to receive either a signal name or an array of signals? What are your thoughts?

**Comment by niieani** [comment]
I've made a non-breaking pull request that fixes this with rest parameters (all additional parameters are treated additional signal names). https://github.com/aurelia/templating-resources/pull/172

**Comment by jdanyow** [comment]
@EisenbergEffect / @niieani - I was thinking the same as @niieani: *update the behavior such that it accepts multiple name arguments.*

@niieani: thanks for the PR! Could you please make a few changes so we can merge it:

1. Please follow the commit message guidelines (in contributing.md).  This enables us to automate the production of release notes among other things.
2. Please change `...args` to the old-school `arguments` style. This is a hot code path so we can't afford the overhead of the transpiled `...args` code.  [Here's what I mean](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=function%20foo(...rest)%20%7B%0A%20%20let%20i%20%3D%20rest.length%3B%0A%20%20while(i--)%20%7B%0A%20%20%20%20console.log(rest%5Bi%5D)%3B%0A%20%20%7D%0A%7D%0A%0Afunction%20bar()%20%7B%0A%20%20let%20i%20%3D%20arguments.length%3B%0A%20%20while(i--)%20%7B%0A%20%20%20%20console.log(arguments%5Bi%5D)%3B%0A%20%20%7D%0A%7D%0A%0Afoo(1%2C%202%2C%203)%3B%0Abar('a'%2C%20'b'%2C%20'c')%3B)
3. Please update the tests for the SignalBindingBehavior.  The tests for the behaviors are kind of smelly, I can help with this if you get stuck or need a hand.

**Comment by niieani** [comment]
@jdanyow Sure, I'll do that when I get a moment. 
@EisenbergEffect I was looking for some contributing guidelines (in many places, such as a link in the main README.md and in the Docs) before sending the PR, but I couldn't find anything aside from the information that signing the License is required. Perhaps it could be made clearer in the docs and/or the main readme that there is something like `contributing.md` and where to find it?
