### ISSUE TITLE
DOM.Element is undefined

### ISSUE THREAD

**Issue by Mordred** [aurelia/templating-resources#173]
When `templating-resources` is loaded before application is bootstraped (aurelia-pal-browser initialized), all injections of `DOM.Element` are `undefined`.

![image](https://cloud.githubusercontent.com/assets/29232/11930907/303b7444-a7e8-11e5-8df2-cc039f17cdd2.png)

**Comment by Mordred** [comment]
This issue has started after upgrade `aurelia-i18n` to 0.4.4, which now loads `aureila-templating-resources`

**Comment by EisenbergEffect** [comment]
It's not a bug in this. It's a bug in i18n, but I'm not sure how this is possible. We need a repro.

**Comment by Mordred** [comment]
@EisenbergEffect OK, it seems that problem is only when using manual bootstrapping (`bootstrap` from `aurelia-bootstrapper`). Here is a demo http://plnkr.co/edit/IteJYiwfEXWs2cEV8aOI?p=preview
