### ISSUE TITLE
Dynamic composition with replaceable parts

### ISSUE THREAD

**Issue by genadis** [aurelia/templating-resources#175]
First posted on gitter, but without success..

I was successfully using compose like so:
```
// some-element.html
<!-- ..... -->

<template repeat.for="item of items">
  <compose view-model.bind="item"></compose>
</template>

<!-- ...... -->
```
Sometimes I find it is useful to use `replace part` functionality rather than changing the whole view.
Ideally combination of both would be perfect:
```
// some-html.html
<!-- ..... -->

<template repeat.for="item of items">
  <compose view-model.bind="item">
    <template replace-part="item-template">
      Replacement: ${someProperty}
    </template>
  </compose>
</template>

<!-- ...... -->
```
but it doesn't seem possible...

The idea is to have an array of custom object elements `foo1` and to compose them dynamically by adding/removing elements to array. this is the outer template with `repeat.for`.
Now imaging you want the generated view to change a bit depending on some configuration. One way would be to create another custom element `foo2` or create alternate view for `foo1`.
But I wanted to change a small peace of `foo1` view, so creating a whole new view seems not efficient. That's why I'm looking for a way to combine the compose and the replace part functionality.
The problem is that `repeat part` works with custom elements and with custom attributes, but didn't work for me with compose

Please suggest what would be the best approach.
Thanks!

**Comment by EisenbergEffect** [comment]
Closing this. We are working on a new way to enable specifying a layout for compose or router-view that would allow shadow dom slot projection to achieve similar results.
