### ISSUE TITLE
Error on combination of oneTime & signal binding behavior

### ISSUE THREAD

**Issue by genadis** [aurelia/templating-resources#176]
When trying to use onTime with signal binding as follows: 
```
<div>${date | fromNow & oneTime & signal:'my-date-signal'}</div>
```
an error is thrown:
```
Unhandled promise rejection Error: One-time bindings cannot be signaled
```

It is useful as explained in example in [aurelia-binding-behaviors](http://www.danyow.net/aurelia-binding-behaviors/)
"Value converter that uses the current time to convert a record's datetime to a "time ago" value:  posted ${postDateTime | timeAgo}. The moment this binding expression is evaluated it will correctly result in posted a minute ago. As time passes, it will eventually become inaccurate..."

So we can use signal to reavaluate the postDateTime that doesn't change.

From my understanding the signal is complementary to the binding and doesn't replace it.
I find it many times useful to manually reevaluate, so oneTime & signal seems like natural solution.

Is there a reason they cannot work together?

Thanks

**Comment by EisenbergEffect** [comment]
@jdanyow Isn't a signal automatically a one-time binding? How should this be handled.

**Comment by jdanyow** [comment]
The combination of signal + one-time was intentionally disabled:

>the signal binding behavior is not applicable to one-time bindings. Currently there is no reason to not support one-time bindings but I'm afraid supporting one-time bindings will prevent us from further optimizing one-time binding scenarios.
https://github.com/aurelia/templating-resources/pull/126#issuecomment-150813462

Time to reconsider this limitation... binding perf refactoring is complete. It should be safe to remove [this check](https://github.com/aurelia/templating-resources/blob/master/src/signal-binding-behavior.js#L16-L18) and allow one-time + signal.

Thoughts?

**Comment by EisenbergEffect** [comment]
Obviously, the fix is simple. You are the binding expert. It's your call.

**Comment by jdanyow** [comment]
Will add some tests and get this into the next release.

**Comment by EisenbergEffect** [comment]
Beautiful :)

**Comment by genadis** [comment]
works like a charm, Thanks!

**Comment by genadis** [comment]
It worked for the above case, but not with `repeat.for`:
```
        <template repeat.for="item of items & oneTime & signal:'my-signal">
          <li>
            <compose view-model.bind="item"></compose>
          </li>
        </template>
```
The list get's rendered once, If I add an `item` to `items` array and invoke `my-signal` the repeat.for is not re rendered.

Should I open separate issue?

**Comment by jdanyow** [comment]
please do- the repeat custom attribute handles oneTime differently than regular bindings
