### ISSUE TITLE
Feature suggestion: Bindable Hide attribute

### ISSUE THREAD

**Issue by dankraus** [aurelia/templating-resources#177]
Hello!

Is there any interest in adding a bindable "hide" attribute? It would simply function as the inverse of show. Obviously we can do `show.bind="!isShowing"`to effectively hide something. I always try to avoid `!`'s in conditionals and code to a "positive" convention. It's just one less mental hurdle to do inverses of booleans and determine what's showing or hiding.

It would add `aurelia-hide`when the value is true and remove when false.

I'd be willing to give it a shot myself and submit a PR but I wanted to make sure it wasn't in the roadmap or anything first.

Thoughts?

**Comment by jdanyow** [comment]
:+1: like

**Comment by dankraus** [comment]
For what it's worth, another clear use and what brought me the idea was doing something like:

    <span show.bind="isSaving">Saving Changes...</span>
    <button hide.bind="isSaving">Save</button>

**Comment by martingust** [comment]
Implemented in https://github.com/aurelia/templating-resources/commit/38760b6ba00774a7e75572baef0021d8c1c45096
