### ISSUE TITLE
repeat.for with oneTime behavior does not refresh on signal 

### ISSUE THREAD

**Issue by genadis** [aurelia/templating-resources#180]
Please consider the following use case:

```
<template repeat.for="item of items & oneTime & signal:'my-signal">
   <li>
       <compose view-model.bind="item"></compose>
   </li>
</template>
```
The list get's rendered once, If I add an item to items array and invoke my-signal the repeat.for is not re rendered.

**Comment by jdanyow** [comment]
Was looking into why it didn't work with oneTime- turns out it was intentional so changing this to an enhancement.  https://github.com/aurelia/templating-resources/pull/126#issuecomment-150813462

**Comment by jdanyow** [comment]
Not sure why I didn't catch this before- the binding is being signaled but nothing happens because the signaled value (the array) is the same as the original value (the array).  

one-time, signal and collection mutation aren't a supported scenario.
