### ISSUE TITLE
Add $first and $last (and possibly other) contextual items to the Map repeater

### ISSUE THREAD

**Issue by niieani** [aurelia/templating-resources#184]
The docs state that the repeaters have these contextual items available inside a repeat template:
```
$index - The index of the item in the array.
$first - True if the item is the first item in the array.
$last - True if the item is the last item in the array.
$even - True if the item has an even numbered index.
$odd - True if the item has an odd numbered index.
```
Even though Map doesn't have an inherent order, there is an order to the way it is iterated and therefore rendered. It would be great if these items were available inside the repeat template the same way they are for Arrays. Useful for generating datagrids from `Map<ID, Object>`.

**Comment by martingust** [comment]
All those should be available when iterating a Map. I just confirmed with the latest skeleton that it works. It doesn't work for you? Can you provide a repro?

**Comment by niieani** [comment]
My bad, I had a typo :astonished: in the code! 
The only thing left I guess is to correct the docs so they don't describe it's the index in the array, but the iteration of the repeater (since it does not need to be an Array).
