### ISSUE TITLE
No way to set rendering order (sorting) of Map repeaters without transforming the expression to an array

### ISSUE THREAD

**Issue by niieani** [aurelia/templating-resources#185]
Since Maps don't have an inherent way to set the iteration order like Arrays (unless by recreating the map by re-adding all the elements in order - not really reliable), this presents a problem in rendering them in a sorted way without resorting to hacks, like transforming them into Arrays first. This is hacky and can introduce performance problems, because every time the expression is evaluated, the whole Map has to be reiterated and converted to an Array.

So the current workaround is:
```html
<template repeat.for="entry of news | getArrayFromMapValues | sortByField:'date'>
```

Perhaps there a better solution to this problem that I'm not aware of?

**Comment by jdanyow** [comment]
you could replace the [MapRepeatStrategy](https://github.com/aurelia/templating-resources/blob/master/src/map-repeat-strategy.js).  Maybe you could enhance it with a convention that looks for a `sort` function on the map and use it to control the order.
