### ISSUE TITLE
Binding Behavior to filter keycodes on KeyboardEvent

### ISSUE THREAD

**Issue by heruan** [aurelia/templating-resources#186]
Given a binding like this:
```html
<input type="search" value.bind="query" keyup.delegate="search() & debounce">
```
would a custom Binding Behavior be able to trigger the `search()` function only for certain keycodes in the triggered `KeyboardEvent`? I know I could pass `$event` and then check the keycodes in the delegated function, but I'd prefer to leave that function uncoupled from the event and I thought a Binding Behavior would fit nicely for this purpose!

**Comment by jdanyow** [comment]
definitely!

something like this:

```js
export class KeyCodeBindingBehavior {
  bind(binding, scope, ...keyCodes) {
    binding.keyCodeFilteredCallSource = binding.callSource;
    binding.callSource = function(event) {
      if (keyCodes.indexOf(event.keyCode) !== -1) {
        this.keyCodeFilteredCallSource(event);
      }
    }
  }
  
  unbind(binding, scope) {
    binding.callSource = binding.keyCodeFilteredCallSource;
    binding.keyCodeFilteredCallSource = null;
  }
}
```

http://plnkr.co/edit/TJcVuD?p=preview

**Comment by heruan** [comment]
Great!
