### ISSUE TITLE
Dynamic replaceable templates

### ISSUE THREAD

**Issue by heruan** [aurelia/templating-resources#188]
I'm building a plugin to automatically create tables based on given properties array and row items. Simplifying:
```html
<table>
  <tr repeat.for="item of items">
    <td repeat.for="property of properties">
      <span>${item[property]}</span>
    </td>
  </tr>
</table>
```
This works like a charm, but it would be useful to let the plugin user to customize the rendering of some property with a template. For example, given items of type:
```json
{
  "id": 123,
  "name": "Aurelia",
  "description": "Awesome framework"
}
```
one may use a template to customize the rendering of `item.name` like this:
```html
<custom-table items.bind="items", properties.bind="properties">
  <template replace part="name">
    <strong>${item.name}</strong>
  </template>
</custom-table>
```
I've tried to bind the `part` attribute to the property name, this way:
```html
<table>
  <tr repeat.for="item of items">
    <td repeat.for="property of properties">
      <template replaceable part.bind="property"> <!-- also tried part="${property}" -->
        <span>${item[property]}</span>
      </template>
    </td>
  </tr>
</table>
```
with no success. Is it possibile in some way, or will it be?

**Comment by jdanyow** [comment]
seems to be working now: https://gist.run/?id=2fb02c423647ec726c5830461e13f7d8

**Comment by PhanindraKumar** [comment]
@jdanyow  the plunk you provided shows the router functionality but does not show any thing about making part bindable . Can you clarify how that solves the issue.
