### ISSUE TITLE
Exception with <template> and if.bind with nested custom elements

### ISSUE THREAD

**Issue by AlexanderDzhoganov** [aurelia/templating-resources#191]
The following code throws `ERROR [app-router] TypeError: Cannot read property 'length' of undefined`
on [line 104 @ templating/content-selector.js](https://github.com/aurelia/templating/blob/master/src/content-selector.js#L104) after clicking the button.

HTML
```html
<template>
  <my-element>
    <template if.bind="!this_does_not_exist">
      <div repeat.for="i of foo">
        <button type="button" click.delegate="click()">Click me!</button>
      </div>
    </template>
  </my-element>
</template>
```

JS
```es6
import {inject} from 'aurelia-framework';
import {Router} from 'aurelia-router';

@inject(Router)
export default class ViewA {
  
  foo = ['a', 'b', 'c'];
  
  constructor(router) {
    this.router = router;
  }
  
  click() {
    this.router.navigate('viewB');
  } 
}
```
where `my-element` is a trivial custom element and `click()` does a `router.navigate()` to any location.

Changing the `<template>` to a `<div>` (or likely any other container tag) seems to not trigger the issue. Also this issue was likely not present in Aurelia versions before and including 0.14 if that helps at all.

**Comment by rocknet** [comment]
I was able to fix the particular error you were getting by initializing this.foo in the constructor.  I don't think your syntax was correct for initializing in the body.  This eliminates the exception of foo being undefined.

```
import {inject} from 'aurelia-framework';
import {Router} from 'aurelia-router';

@inject(Router)
export default class ViewA {

  constructor(router) {
    this.foo = ['a', 'b', 'c'];
    this.router = router;
  }

  click() {
    this.router.navigate('viewB');
  } 
}
```

However, after that I was not able to bring up viewB by clicking on a button.  It just set the router-view to empty content.  I couldn't figure that part out for now, but figured I'd mention the class syntax issue.

**Comment by EisenbergEffect** [comment]
Closing this since content selectors are replaced by the new slot mechanism.
