### ISSUE TITLE
Changes break focus.bind

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/templating-resources#199]
@afmuller commented on [Sun Mar 06 2016](https://github.com/aurelia/bootstrapper/issues/37)

Hi

Some change in aurelia-bootstrapper between version 1.0.0-beta.1.1.1 and 1.0.0-beta.1.1.4 have caused "focus.bind" to stop working. 

I have a "focus.bind" on my form field to give focus to a field when the page loads. On version 1.0.0-beta.1.1.1 it worked perfectly. On version 1.0.0-beta.1.1.4 it does not. On 1.1.4, the event appears to fire before the page is displayed - causing the field to not get the focus.

I have reverted aurelia-bootstrapper back to 1.0.0-beta.1.1.1 (from 1.1.4) and it stated working again.

**Comment by EisenbergEffect** [comment]
@afmuller Can you create a simple repro and attach the source to this issue? That would help us to track down the source of the regression.

**Comment by afmuller** [comment]
Quite simple actually.
I downloaded the 'skeleton-es2016' from https://github.com/aurelia/skeleton-navigation.

Made the following changes to test setting the field focus:

**/src/welcome.js**
Added property: 
`firstNameHasFocus = true;`

**/src/welcome/html** (added focus.bind="firstNameHasFocus")
`<input type="text" value.bind="firstName" class="form-control" id="fn" placeholder="first name" focus.bind="firstNameHasFocus">`

When I run and view the page in the browser, firstName does not get the focus.

So I downgrade aurelia-bootstrap to v1.1.2 or v1.1.1: **jspm install aurelia-bootstrapper@1.0.0-beta.1.1.2**

Now I run and view the page in the browser and it works perfectly (firstName gets the focus after page load)

**Comment by EisenbergEffect** [comment]
Perfect. Thanks. We'll take a look shortly.

**Comment by jdanyow** [comment]
Looks like this works if the property is set to true in the attached stage:

```js
  attached() {
    this.lastNameHasFocus = true
  }
```

https://gist.run/?id=cfefc64b3a236d2ab4ef5570b7ef8e9e

Should the focus attribute wait to "give focus" until the attached stage instead of doing it during bind/self-subscriber?
https://github.com/aurelia/templating-resources/blob/master/src/focus.js

**Comment by EisenbergEffect** [comment]
Probably it needs to wait until attached. I'm not sure if it would reliably work when the focused element is outside of the document.
