### ISSUE TITLE
Remove TaskQueue usage in If template controller

### ISSUE THREAD

**Issue by jdanyow** [aurelia/templating-resources#200]
No longer needed:
https://github.com/aurelia/task-queue/issues/12#issuecomment-193186222

**Comment by EisenbergEffect** [comment]
Cool!

**Comment by martingust** [comment]
Awesome!

**Comment by atsu85** [comment]
@jdanyow, i'm curious, 
when should the TaskQueue be used, 
why was it used initially and 
why isn't it needed (any more)?

I guess taskqueue should be used to offload UI-updating actions from business logic "thread". 
Removing view from ViewSlot looks like UI-updating action and valueChanged sounds like callback for business logic, but i guess there is very good explanation why taskqueue is not needed in this case ;)

**Comment by jdanyow** [comment]
@atsu85 that info is in the discussion here: https://github.com/aurelia/task-queue/issues/12
