### ISSUE TITLE
Missing argument in type declaration for SignalBindingBehavior.bind

### ISSUE THREAD

**Issue by thomas-darling** [aurelia/templating-resources#206]
I'm doing essentially the same as what is being done here, in `TBindingBehavior`:
https://github.com/aurelia/i18n/blob/master/src/t.js

However, TypeScript complains because of a missing argument in the type declaration for the `bind` method of the `SignalBindingBehavior` class.

If I manually add it, it works perfectly :-)

```typescript
export class SignalBindingBehavior {
    bind(binding: any, source: any, ...name: string[]): any;
    ...
```

**Comment by thomas-darling** [comment]
Related: https://github.com/aurelia/binding/issues/352

**Comment by jdanyow** [comment]
there's no typing for the individual binding behavior implementations, only this:  https://github.com/aurelia/binding/blob/master/dist/aurelia-binding.d.ts#L280

**Comment by thesmallbang** [comment]
Here is an example of the workaround I ended up with to satisfy typescript.


    bind(binding, source) {
        (<any>this.signaler).bind(binding, source, 'aurelia-translation-signal');

        let sourceExpression = binding.sourceExpression;

        if (sourceExpression.rewritten) {
            return;
        }
        sourceExpression.rewritten = true;

        let expression = sourceExpression.expression;
        sourceExpression.expression = new (<any>ValueConverter)(expression,
            'df',
            sourceExpression.args,
            [expression, ...sourceExpression.args]);
    }


    unbind(binding, source) {
        this.signaler.unbind(binding, source);
    }
