### ISSUE TITLE
`repeat.for` breaks `touch` event listeners

### ISSUE THREAD

**Issue by stoffeastrom** [aurelia/templating-resources#209]
There is a [flaw](http://lists.w3.org/Archives/Public/public-webevents/2012OctDec/0023.html) in the touch specification which breaks event listeners. This worked a couple of months ago but there has been a lot of changes in this area :)

So when moving an item in an array the event flow will break since the item that got `touchstart` is removed. Instead of moving the element it will be removed and then added.

The work around discussing this with @martingust is to add `view-cache="*"` on the `repeat.for`.

@martingust @EisenbergEffect

**Comment by martingust** [comment]
The reason this worked a couple months ago is probably because `repeat`had its own (non optional) caching before `view-cache` was implemented. In order to make this work without view caching we need to track which views are moved instead of remove/add, which probably going to be difficult.

I think the view cache work around is alright, without any particular downsides. Perhaps we should include something in the docs about this, also this issue will help others that run into same issue.

@EisenbergEffect @jdanyow What do you guys think?

**Comment by stoffeastrom** [comment]
@martingust is there a way to set the *view-cache* from a *custom attribute*? So I can make sure my plugin works?

**Comment by martingust** [comment]
@stoffeastrom Not sure, does it work if you put view-cache on the custom attribute's template tag?

**Comment by stoffeastrom** [comment]
@martingust What do you mean? You mean in the definition?

```javascript
@customAttribute("oa-sortable")
```
?

**Comment by martingust** [comment]
@stoffeastrom Nvm, my bad, I was thinking custom element.

I think you can set it from your custom attribute though, by injecting the repeat instance and call `setCacheSize` on its `BoundViewFactory`.

```javascript
import {customAttribute} from 'aurelia-templating';
import {Repeat} from 'aurelia-templating-resources';

@customAttribute('my-attribute')
export class MyAttribute {
  static inject = [Repeat];
  constructor(repeat) {
    this.repeat.viewFactory.setCacheSize('*', true);
  }
}
```

There might be a better way to do this though, @EisenbergEffect would have to confirm.

**Comment by EisenbergEffect** [comment]
Yes

**Comment by martingust** [comment]
@stoffeastrom Any chance trying this out?

**Comment by stoffeastrom** [comment]
@martingust No, not yet but I'm sure it will work :)

**Comment by jdanyow** [comment]
@martingust / @stoffeastrom is the view-cache the solution? Or is there more work to do here?  Wondering if this can be closed.

**Comment by stoffeastrom** [comment]
Closing this for now
