### ISSUE TITLE
Binding Select With Dynamic Options Fails To Bind Initially

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/templating-resources#21]
The initial value isn't set when binding a select with generated options. I believe this is because the repeater executes after the value is bound. We can make the `selected-item` behavior smarter so that it can be used in place by using `value` if model is not present.

Need to investigate if there's a simple way to get this to work with the `value` property. We may need to hard code something to use a special behavior whenever we see a binding expression on a select.value.

**Comment by jdanyow** [comment]
The ViewSlot seems to be where the rubber hits the road in terms of changing a `select` element's set of options.  Would be a good spot to put the special behavior around select's and value bindings?

**Comment by EisenbergEffect** [comment]
Not sure just yet... Maybe it could go in the repeater? If you want to play around with a few ideas, please go ahead :)

**Comment by jdanyow** [comment]
As part of this change we could switch from using a behavior to having this be a special case when binding to a select element's value.  The solution would need to handle multi-select scenarios as well.  Also need to take into consideration https://github.com/aurelia/binding/issues/43 , there might be some logic we can share between these two issues.

**Comment by EisenbergEffect** [comment]
Yes. I very much want to push this logic down into the binding library. @jdanyow Are you interested in moving ahead to work on this along with the radio issue?

**Comment by jdanyow** [comment]
yep- I had already started it a while back before gearing up to work on benchmarking

**Comment by EisenbergEffect** [comment]
The new select implementation is in and going out in the next release. Thanks @jdanyow !
