### ISSUE TITLE
Aurelia does not setup a collection observer for arrays returned from ValueConverters

### ISSUE THREAD

**Issue by niieani** [aurelia/templating-resources#214]
I've tried implementing the @CasiOo's `repeatDiffFilter` idea from #213, but unfortunately I've stumbled onto this problem. Example here:
https://gist.run/?id=7f2a22cebf10db035017db0a656fa3c5

Expected behavior is that once the array returned from the ValueConverter changes, text "test" should appear (an additional element should be created every second).

**Comment by jdanyow** [comment]
This is intentional- the binding system observes the pre-converted value because the value coming out of the converter tends to be transient.  Value converters are singletons and shouldn't be stateful.
