### ISSUE TITLE
repeat.for doesn't iterate with <td> in view attached to <tr> with as-element when <require> is present

### ISSUE THREAD

**Issue by valichek** [aurelia/templating-resources#223]
Here is gist for the issue:
https://gist.run/?id=f52caf1613cb9d71970a830bf9d5eae5

When I remove `<require>` from `custom-view.html` it iterates as expected.

**Comment by valichek** [comment]
Well, looks like browser is mangling the <table>. Having `<require>` inside `<td></td>` looks to be tricky but workaround, does it? 
```html
<td if.bind="false"><require from="./stringify"></require></td>
```

**Comment by EisenbergEffect** [comment]
I'm not sure why that would make a difference. Also requires should be at the top of a view. We may enforce that in the future.

**Comment by valichek** [comment]
@EisenbergEffect but is it possible to bind parent resources for `custom-view` when adding 
```
<tr as-element="compose" view.bind="'./custom-view.html'"></tr>
```

**Comment by EisenbergEffect** [comment]
Views are encapsulated except for what you choose to globalize. The require statements should be the first thing in the template.

**Comment by valichek** [comment]
@EisenbergEffect and maybe it is possible to have `<!-- <require-hidden> -->` commented but parsed by aurelia. Maybe such syntax is redundant or even impossible. The idea is to hide it from browser but not from aurelia. Or maybe there is better solution than globalizing resources

**Comment by valichek** [comment]
@EisenbergEffect Do you suppose described problems with `<table>` elements to be actual dev issue or aurelia ideological?

**Comment by EisenbergEffect** [comment]
* No, require needs to be an element.
* Tables are a problem for html. You shouldn't use them if you don't have to. They have restrictions to their usage and cause reduced rendering performance.

We'll figure out the issue though.

**Comment by valichek** [comment]
So I've replaced `td` element with `div` styled with `display: table-cell;` and it works as expected

**Comment by EisenbergEffect** [comment]
Some investigation here indicates that somehow, when the require element is present the tds don't render at all. It's very odd. I'll need to revisit this later when I've got some more time.

**Comment by jdanyow** [comment]
Looks like browsers won't allow a <require> inside a <tr>. You can try wrapping the require with <template>, should fix the issue for the evergreen browsers but not for IE11.

http://i.imgur.com/wNK01m3.png

```js
var div = document.createElement('div');
div.innerHTML = `
<table>
  <tbody>
    <tr>
      <require></require>
      <td></td>
    </tr>
  </tbody>
</table>`;

div.innerHTML
```
