### ISSUE TITLE
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

### ISSUE THREAD

**Issue by jdanyow** [aurelia/templating-resources#224]
https://www.chromestatus.com/features/6750456638341120

![warning](http://i.imgur.com/36Z4Kbu.png)

```js
  if (FEATURE.shadowDOM) {
    DOM.injectStyles('body /deep/ .aurelia-hide { display:none !important; }');
  } else {
    DOM.injectStyles('.aurelia-hide { display:none !important; }');
  }
```
https://github.com/aurelia/templating-resources/blob/master/src/aurelia-templating-resources.js#L42

**Comment by EisenbergEffect** [comment]
@jdanyow Can you check to see if they replaced it with something else so that we can still make these styles work?

**Comment by jdanyow** [comment]
I don't think there's a replacement.  Could we use an inline-style instead?

>**Alternative implementation suggestion for web developers**
No direct alternative. There is on-going discussion to make these selectors available in static profile [5].
[--chromium](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/68qSZM5QMRQ/pT2YCqZSomAJ)

**Comment by EisenbergEffect** [comment]
Yes, we can do an Optional inject of the DOMBoundary. If there is shadow dom, we can check the boundary to see if a style tag has been injected in that boundary. If not we can inject one and then mark it  as injected.
