### ISSUE TITLE
show.bind doesn't change in custom component.

### ISSUE THREAD

**Issue by eliavmaman** [aurelia/templating-resources#225]
I've create spinner component:
```html
<template>
    <div class="splash" show.bind="bussy">
        <div class="message">Game info</div>
        <i class="fa fa-spinner fa-spin"></i>
    </div>
</template>`
```
Spinner.js-
```js
export class Spinner {
    constructor(){
        this.bussy=false;
    }
    show(){
        this.bussy=true;
    }
    hide(){
        this.bussy=false;
    }
}
```

then in the outer class, i want to display the spinner  when HTTP request is on so the code code there is:
`this.spinner.show();`

THE SPINNER IS NOT DISPLAYED... :(
when inspecting the element i still see:
`<spinner class="au-target" au-target-id="247">
    <div class="splash au-target aurelia-hide" show.bind="bussy" au-target-id="220">
        <div class="message">Game info</div>
        <i class="fa fa-spinner fa-spin"></i>
    </div>
</spinner>`

aurelia-hide class is still there.
why is that please?

**Comment by eliavmaman** [comment]
I've also noticed that `this.bussy` in the spinner class is not set to `true` after changing.. 
Any one please?

**Comment by jdanyow** [comment]
how is the outer class accessing the spinner element instance?

**Comment by eliavmaman** [comment]
`@inject(EventAggregator, WebAPI, Spinner)`

`export class XXX{
    constructor(eventAggregator, api, spinner) {
this.spinner=spinner;
}
}`

**Comment by jdanyow** [comment]
ah- you're getting a different spinner instance.

try using the `ref` attribute instead: `<spinner ref="spinner"></spinner>`- this will set/create the `spinner` property in your outer VM

**Comment by eliavmaman** [comment]
10x but now i get 
`Uncaught TypeError: this.spinner.show is not a function`

**Comment by jdanyow** [comment]
apologies- I gave you the code for grabbing an instance to the spinner DOM element- what you want is the spinner's view-model instance:

`<spinner view-model.ref="spinner"></spinner>`

**Comment by eliavmaman** [comment]
10x man that defenetly did the trick.
But the thing with aurelia is that there are many ways to do the data binding. Is there any docs that explains which to use where?
