### ISSUE TITLE
Issue with bindingSignaler combined with updateTrigger:'blur' and custom element in IE11/Edge

### ISSUE THREAD

**Issue by doeck** [aurelia/templating-resources#226]
I ran into something that looks like an timing issue in updating the model with the binding signaler in IE11 and Edge when using it inside a custom element and updateTrigger:'blur'.

I have two inputs with numeric values and a total calculated from these. When one of the values is changed I want the total to be calculated. (In my real world app this is more complex, I have more input fields and need formating into german number format so that there will be a valueconverter involved and that's why I chose to use a custom-element and the binding-signaler and need updateTrigger:'blur').

In Chrome this works as I expect it to do.
In IE11 / Microsoft Edge I get a different behaviour: after changing a value and "blurring", the total does'nt change. After the next blur, the first change will be reflected in the total, but not the second one, if something was changed there too. This second change could be seen after  the next change, and so on.
It looks like the calculation of the total is triggered correctly by the signal but the model still has the old value to calculate with.

I tried to narrow it down to a quite simple scenario and ended up with this code:
my-viewmodel.js

```
export class MyViewmodel {
    data = {
        val1: 100,
        val2: 200
    }

    total() {
        return parseFloat(this.data.val1) + parseFloat(this.data.val2);
    }
}
```

my-viewmodel.html
```
<template>
    <require from="./my-input"></require>

    <div style="margin-top: 100px;">
        <my-input type="text" val.two-way="data.val1"></my-input>
        <my-input type="text" val.two-way="data.val2"></my-input>
        Total: ${total() & signal:'mySignal'}
    </div>
</template>
```

and the custom element
my-input.js
```
import {bindable, inject} from 'aurelia-framework';
import {BindingSignaler} from 'aurelia-templating-resources';

@inject(BindingSignaler)
export class MyInputCustomElement {
 
    @bindable val;

    constructor(signaler) {
        this.signaler = signaler;
    }
}
```

my-input.html
```
<template>
    <input type="text" value.bind="val & updateTrigger:'blur'" blur.trigger="signaler.signal('mySignal')" />
</template>
```

Here's a link to a plunker with a little more real world app like scenario showing the issue:
http://plnkr.co/edit/ZdiXFOS3huYhqT3CC7i1?p=preview

Is this a bug or is there something wrong in my code?
Any suggestions what I could do?

**Comment by EisenbergEffect** [comment]
@jdanyow Can you look into this? Perhaps the signaler needs to schedule on the task queue?

**Comment by jdanyow** [comment]
closing- will answer in http://stackoverflow.com/questions/37528390/delayed-action-of-aurelia-bindingsignaler-in-ie11-edge
