### ISSUE TITLE
Unhandled rejection Error: Cannot find module './aurelia-templating-resources/

### ISSUE THREAD

**Issue by priyankawadhwa** [aurelia/templating-resources#235]
I recently started facing an issue with running my Aurelia app without making any code changes. The error that i am facing in my development console is -- **Unhandled rejection Error: Cannot find module './aurelia-templating-resources/compose'** . Can anyone help me out with the same.
I have successfully run the npm update and npm install commands, It updated my bluebird dependency, but still facing with the same issue when having my aurelia-templating-resources dependency already existing in my package.json.

![aurelia-issue](https://cloud.githubusercontent.com/assets/6416938/16185623/cab0e0e8-36e2-11e6-977f-67ee5f617875.png)

**Comment by EisenbergEffect** [comment]
This looks like a problem with an earlier version of the webpack skeletons. All this should be solidly worked out in the latest skeletons.
