### ISSUE TITLE
Custom 'if' attribute with content recreation?

### ISSUE THREAD

**Issue by krostkowski** [aurelia/templating-resources#236]
I wanted to create custom 'hard-if', which causes element to be created from scratch. 

After I had read https://github.com/aurelia/templating-resources/blob/master/src/if.js
I copied code and tried to set view = null when hiding (line 75) element. It even worked for simple nested elements, but when I used my 'hard-if' on router-view element  it stopped working (first appearance works, subsequent not).

Is there a way to handle such situation:
```
<form-login if.bind="sessionExpired"></form-login>
<router-view if.bind="!sessionExpired></router-view>
```

In the route module I'm loading data (loader shown), I intercept a response error (session expired), show form-login. After successfull log in, router-view is back but with the loader (constructor is not invoked). 

Is there a way to hide and show element like it was rendered for the first time?

**Comment by jdanyow** [comment]
this question and answer might help:  http://stackoverflow.com/questions/33458274/how-to-switch-between-login-page-and-app-with-aurelia

**Comment by jdanyow** [comment]
@krostkowski are you all set?  Can this be closed?

**Comment by krostkowski** [comment]
Yes, thank you. It worked like a charm:)
