### ISSUE TITLE
css attribute doesn't work without bind or interpolation

### ISSUE THREAD

**Issue by vegarringdal** [aurelia/templating-resources#237]
Is this a bug?

https://gist.run/?id=28368d0649a8af90180046525b698b2e

I would would have expected both to work.

**Comment by EisenbergEffect** [comment]
I suppose it is a bug...though it doesn't make any sense to do that.
@jdanyow Would this be easy to fix?

**Comment by vegarringdal** [comment]
Only reason why I noticed it was because in my grid I have a option where you pass in the style you want to add in a ```col-css``` attribute for the "simple html" column option.
So when someone tried to use just regular styling like I do in the box that fails, it didnt work, and they told me I had a bug :smile: 

Was kinda unsure if it was a bug or just me, the hack works fine and they where happy, so isnt really a problem, just wanted to report it in case you guys didnt know.

**Comment by EisenbergEffect** [comment]
It's "technically" a bug :) We will fix it. If it isn't a quick fix we may prioritize other issues higher for now though.

**Comment by vegarringdal** [comment]
Np, focus on the important stuff, if anyone get a issue they can use the hack I used :-)
Keep up the good work, Aurelia made web programming fun  :+1:

**Comment by Alexander-Taran** [comment]
could be: won't fix

**Comment by EisenbergEffect** [comment]
Yeah. I don't think we're planning to fix this since the `css` attribute is really only for when you need to bind styles. It technically only exists because of a bug in IE (and maybe Edge too, can't remember anymore) that prevents using interpolation directly within the `style` attribute.
