### ISSUE TITLE
enhance not working since RC was released

### ISSUE THREAD

**Issue by tzimmerer** [aurelia/templating-resources#242]
Hello,
I am working on a project where we insert a view in a screen and I need to enhance this view to bind the data with it. 
Everything seemed to work before I update to the last version

What's happen now :
If there is a single tag in the view, nothing happen  : 
![not working](https://cloud.githubusercontent.com/assets/20720313/17242378/200a7e84-5577-11e6-82c6-1fb8274e286c.png)

And when there is no tag : 
![working](https://cloud.githubusercontent.com/assets/20720313/17242361/0ced6938-5577-11e6-81d9-bea37f501152.png)

Here is the code of the enhancement (find on the Internet)

```
import { inject, TemplatingEngine, createOverrideContext, ViewResources } from "aurelia-framework";

@inject(TemplatingEngine, ViewResources)
export class AureliaCompilationService{
  
 constructor(templatingEngine, viewResources) {
    this._templatingEngine = templatingEngine;
    this._viewResources = viewResources;
  }

  compileView(element, ctx) {
    if (element != null) {
      let view = $(element).data('viewInstance');
      if (element.querySelectorAll('.au-target').length === 0) {
        if (this._viewResources) {
          view = this._templatingEngine.enhance({
            bindingContext: ctx,
            overrideContext: createOverrideContext(ctx, ctx.$parent),
            element: element,
            resources: this._viewResources
          });
        } else {
          view = this._templatingEngine.enhance({
            bindingContext: ctx,
            overrideContext: createOverrideContext(ctx, ctx.$parent),
            element: element
          });
        }

        $(element).data('viewInstance', view);

      } else {
        if(view.bind) {
          view.bind(this, createOverrideContext(ctx, ctx.$parent));
        }
      }

      if(view.attached) {
        view.attached(); // attach it to the DOM
      }
    }
  }


}
```
Any idea ?

**Comment by jdanyow** [comment]
please create a reproduction of what you are seeing using https://gist.run/?id=7542e061bc940cde506b

**Comment by tzimmerer** [comment]
Here it is : 

https://gist.run/?id=2d00b06ba86c518db9f219ca917846f3

Clicking on the enhance button only bind the htmlSource1 but not the 2nd one

**Comment by tzimmerer** [comment]
I found a solution to this problem : I used a reference (ref="htmlHolde2") and the aurelia binding ("innerhtml.bind='htmlSource2 ' ) at the same time. By removing the innerhtml.bind in the .html and writing " this.htmlHolder2.innerHTML = "<p>" + "${toto}" + "</p>"; " in the .js, it works correctly.
