### ISSUE TITLE
proposal: add `stopPropagation` binding behavior

### ISSUE THREAD

**Issue by jdanyow** [aurelia/templating-resources#243]
In the last release we fixed an issue where the delegate binding command didn't match the trigger binding command or vanilla addEventListener with regards to event bubbling.

I would like to propose we add a convenience binding behavior to enable developers to stop an event from bubbling more easily.

Usage:
```html
<button click.delegate="doSomething() & stopPropagation">Do Something</button>
<button click.trigger="doSomething() & stopPropagation">Do Something</button>
```

Live Example:
https://gist.run/?id=bf3b166a2cc18332f560b4e6b48bfe86

Code:
```js
export class StopPropagationBindingBehavior {
  bind(binding, source) {
    binding.standardCallSource = binding.callSource;
    binding.callSource = function(event) {
      this.standardCallSource(event);
      event.stopPropagation();
    };
  }
  
  unbind(binding, source) {
    binding.callSource = binding.standardCallSource;
    binding.standardCallSource = null;
  }
}
```

**Comment by jdanyow** [comment]
https://github.com/aurelia/framework/issues/499
https://github.com/aurelia/binding/pull/468
https://github.com/aurelia/binding/issues/467

**Comment by stoffeastrom** [comment]
Will this break other frameworks that utilises event bubbling? I have always been against using `stopPropagation` and I wonder in which use cases you actually need to use it..

I think we have had a similar discussion long time ago where my gesture framework broke where an `event.stopPropgation` was added in the framework.

**Comment by jdanyow** [comment]
Generally, no, because usage of the proposed binding behavior is optional.

When used in conjunction with the `delegate` binding command, there is no potential to impact other frameworks or vanilla js.  By the time delegate bindings act the event has already propagated.

When used in conjunction with `trigger`, it would potentially impact other things.

**Comment by jdanyow** [comment]
closing this- people don't seem to be having a ton of issues with the recent changes around delegated event propagation.  This probably isn't needed.

**Comment by gooeyideas** [comment]
This is really useful and it should be added as the default example for [Creating a Custom Binding Behavior
](https://aurelia.io/docs/binding/binding-behaviors#custom-binding-behaviors) in the documentation!

This creates a conversion pattern for Knockout's `eventBubble: false` binding.

**Comment by bigopon** [comment]
@gooeyideas Would be really awesome if you could help with the doc with this. Join us building Aurelia https://github.com/aurelia/aurelia/issues/318#issuecomment-441827326 😆
