### ISSUE TITLE
Firefox bug: if.bind="(row.config.type == 'common')" does not work, but chrome work fine.

### ISSUE THREAD

**Issue by xiwc** [aurelia/templating-resources#244]
Version: 45.0

**Comment by atsu85** [comment]
Adding two template comptrollers(such as if and for) to the same element, is not supposed to work (consistently). Put them to different elements. You might want to use template tag for repeat.for attribute

**Comment by atsu85** [comment]
You might want to use https://www.npmjs.com/package/gulp-aurelia-template-lint to detect such problems at build time
