### ISSUE TITLE
FR: Should the show binding additionally use the HTML5 'hidden' attribute?

### ISSUE THREAD

**Issue by AdamWillden** [aurelia/templating-resources#245]
**I'm submitting a feature request**
This is just a question/proposal (but not a support question)

* **Library Version:**
1.0.0

**Current behavior:**
show.bind="true" adds `display: none` CSS _only_

* **What is the expected behavior?**
show.bind="true" could add `display:none` CSS **AND** use the hidden attribute.

* **What is the motivation / use case for changing the behavior?**
Standards and Accessibility. I don't know how much accessibility is a concern here as I think screen readers do detect whether content is hidden using `display: none`. However is using the hidden attribute the _correct_ way to go? Has it been considered before?

**Comment by jdanyow** [comment]
MDN:

>The hidden global attribute is a Boolean attribute indicating that the element is not yet, or is no longer, relevant. For example, it can be used to hide elements of the page that can't be used until the login process has been completed. Browsers won't render elements with the hidden attribute set.
>
>The hidden attribute must not be used to hide content that could legitimately be shown in another presentation. For example, it is incorrect to use hidden to hide panels in a tabbed dialog, because the tabbed interface is merely a kind of overflow presentation — one could equally well just show all the form controls in one big page with a scrollbar. It is similarly incorrect to use this attribute to hide content just from one presentation — if something is marked hidden, it is hidden from all presentations, including, for instance, screen readers.
>
>Note: Changing the value of the CSS display property on an element with the hidden attribute overrides the behavior. For instance, elements styled display: flex will be displayed despite the hidden attribute's presence.
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden

DWB:

>When applied to an element, the hidden attribute acts very much like CSS' display: none;  the element disappears from view and its dimensions collapse.  It's as simple as:
  ```html
  <div hidden>
    You can't see me!
  </div>
  ```
If a given browser didn't support this attribute, you could likely style it via:
`*[hidden] { display: none; }`
So why use the hidden attribute?  It's more semantically correct and should more efficiently aid screen readers.  You'll even save a few characters on the display:none
https://davidwalsh.name/html5-hidden

**Comment by AdamWillden** [comment]
Thank you for those links. 

I'm not sure I've ever understood what the original intention was regarding having both show AND if bindings. 

Similarly I'm unsure if others may have used the show binding for tabbed browsing, in which case we should follow the advice of MDN and **not** apply the hidden attribute as that would in fact break an existing site's accessibility.

**Comment by jdanyow** [comment]
>I'm not sure I've ever understood what the original intention was regarding having both show AND if bindings.

Flexibility, parity with knockout's `visible` and `if` bindings. `show` is more lightweight but it leaves the hidden element in the DOM.  `if` removes the element from the DOM.  I tend to use `if` when hiding larger chunks of elements, especially if they contain bindings.  I use `show` for single elements, especially if they are shown frequently.

**Comment by AdamWillden** [comment]
@jdanyow thanks for the feedback, that makes sense. I probably overuse `if.bind` these days and will keep this in mind. I remember using them both a lot in knockout

**Comment by jdanyow** [comment]
If we go by what the MDN docs say it seems like there's a judgement call that needs to be made when deciding to use the hidden attributes in conjunction with aurelia show custom attribute. Definitely was worth considering but it doesn't seem black and white enough to change `show`s behavior post RTM. Devs could copy the code for the `show`/`hide` custom attribute and add the `hidden` attribute logic if they wanted.
