### ISSUE TITLE
loader in html-resource-plugin configure() not implement addPlugin()

### ISSUE THREAD

**Issue by ivanK-someCode-repo** [aurelia/templating-resources#247]
* **Operating System:**
Windows 8

* **Node Version:**
4.4.7

* **NPM Version:**
3.10.6

* **Webpack AND Version**
2.1.0-beta.20

* **Browser:**
Chrome  51.0.2704.103 m

* **Language:**
ESNext

**Current behavior:**

When **"aurelia-framework"** tryind to load module **"aurelia-templating-resources"**, it calls the `configure(config)`  function of this module. 

Then inside of `configure()` calls `viewEngine.addResourcePlugin` :

`ViewEngine.prototype.addResourcePlugin = function addResourcePlugin(extension, implementation) {
    var name = extension.replace('.', '') + '-resource-plugin';
    this._pluginMap[extension] = name;
    this.loader.addPlugin(name, implementation);
};`

And as I see in Chrome debugger, `this.loader`  is object `{"templateRegistry":{}}`, not `WebpackLoader`   object which used in `loadPlugin()` function of **"aurelia-framework"**

Maybe becous of this **"aurelia-loader"** throws error:

*Uncaught (in promise) Error: Loader must implement addPlugin(pluginName, implementation).*

with stack trace:
![default](https://cloud.githubusercontent.com/assets/13942835/17554746/132b0376-5f15-11e6-9cc3-e72243a96960.jpg)

**Expected/desired behavior and motivation / use case for changing the behavior:**

The problem may be in **"html-resource-plugin"**  - when I add `viewEngine.loader = config.aurelia.loader;` to `config()` function of this plugin and rebuild project, "aurelia-templating-resources" module has been configured without any errors - 

![default](https://cloud.githubusercontent.com/assets/13942835/17555969/498047c4-5f1a-11e6-8ae8-5934b9f86c94.jpg)

"html-resource-plugin" `config()` function:

````
function configure(config) {
  var viewEngine = config.container.get(_aureliaTemplating.ViewEngine);
  viewEngine.loader = config.aurelia.loader;
  var loader = config.aurelia.loader;

  viewEngine.addResourcePlugin('.html', {
    'fetch': function fetch(address) {
.....
}
````

**Comment by ivanK-someCode-repo** [comment]
The problem may be in **"html-resource-plugin"**  - when I add `viewEngine.loader = config.aurelia.loader;` to `config()` function of this plugin and rebuild project, "aurelia-templating-resources" module has been configured without any errors - 

![default](https://cloud.githubusercontent.com/assets/13942835/17555969/498047c4-5f1a-11e6-8ae8-5934b9f86c94.jpg)


"html-resource-plugin" `config()` function:

````
function configure(config) {
  var viewEngine = config.container.get(_aureliaTemplating.ViewEngine);
  viewEngine.loader = config.aurelia.loader;
  var loader = config.aurelia.loader;

  viewEngine.addResourcePlugin('.html', {
    'fetch': function fetch(address) {
.....
}
````

**Comment by ivanK-someCode-repo** [comment]
The problem was resolved after update to new version of npm (3.10.7) and reinstall all modules

**Comment by ernstc** [comment]
I am having the same issue. Below my dependencies:

"devDependencies": {
    "@types/node": "^9.4.7",
    "@types/globalize": "0.0.30",
    "@types/webpack-env": "^1.13.5",
    "aspnet-webpack": "^2.0.3",
    "aurelia-webpack-plugin": "2.0.0-rc.5",
    "css-loader": "^0.28.11",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^1.1.11",
    "html-loader": "^0.5.5",
    "json-loader": "^0.5.7",
    "less": "^3.0.1",
    "less-loader": "^4.1.0",
    "style-loader": "^0.20.3",
    "ts-loader": "3.5.0",
    "typescript": "^2.7.2",
    "url-loader": "^1.0.1",
    "webpack": "3.11.0",
    "webpack-hot-middleware": "^2.21.2"
  },
  "dependencies": {
    "aurelia-bootstrapper": "^2.2.0",
    "aurelia-cookie": "^1.0.10",
    "aurelia-fetch-client": "^1.3.1",
    "aurelia-framework": "^1.1.5",
    "aurelia-i18n": "^2.1.2",
    "aurelia-ion-rangeslider": "^0.2.0",
    "aurelia-loader-webpack": "^2.1.0",
    "aurelia-pal": "^1.7.0",
    "aurelia-plugins-tabs": "^2.5.2",
    "aurelia-router": "^1.5.0",
    "aurelia-history": "^1.1.0",
    "aurelia-validation": "^1.1.3",
    "aurelia-event-aggregator": "^1.0.1",
    "aurelia-history-browser": "^1.1.1",
    "aurelia-logging-console": "^1.0.0",
    "aurelia-pal-browser": "^1.7.0",
    "aurelia-polyfills": "^1.3.0",
    "aurelia-route-recognizer": "^1.1.1",
    "aurelia-templating-binding": "^1.4.1",
    "aurelia-templating-resources": "^1.6.0",
    "aurelia-templating-router": "^1.3.1",
    "bluebird": "^3.5.1",
    "bootstrap": "^3.3.7",
    "cldr-data": "^32.0.1",
    "d3": "^4.13.0",
    "font-awesome": "^4.7.0",
    "globalize": "^1.3.0",
    "globalize-webpack-plugin": "^2.1.0",
    "i18next-xhr-backend": "^1.5.1",
    "iana-tz-data": "^2017.1.0",
    "isomorphic-fetch": "^2.2.1",
    "jquery": "^3.3.1",
    "jquery-ui": "^1.12.1",
    "moment": "^2.21.0",
    "numeral": "^2.0.6"
  }

npm version: 5.6
reinstalling the modules does not fix

**Comment by Alexander-Taran** [comment]
@ernstc  you probably use npm and you have package.lock.json
Delete that file and node_modules and reinstall dependencies.

It is an npm issue 

It was discussed a lot @ https://discourse.aurelia.io/
and in https://gitter.im/aurelia/Discuss

**Comment by ernstc** [comment]
@Alexander-Taran problem resolved. Thanks!
