### ISSUE TITLE
Css property does not show background image with base64 encoded image

### ISSUE THREAD

**Issue by dtaalbers** [aurelia/templating-resources#248]
**I'm submitting a bug report**

* **Library Version:**
major.minor.patch-pre

**Please tell us about your environment:**
* **Operating System:**
OSX 10.11.6

* **Node Version:**
5.12.0

* **NPM Version:**
3.8.6

* **JSPM Version**
JSPM 0.16.39 

* **Browser:**
all 

* **Language:**
TypeScript

**Current behavior:**
 https://gist.run/?id=f3f54bda42707dfbbf59263c5b5d0a35

**Expected/desired behavior:**
Show my image.

* **What is the expected behavior?**
Show my image.

**Comment by jdanyow** [comment]
@z-brooks any chance you could take a look at this? It's similar to https://github.com/aurelia/binding/issues/301

![](http://i.imgur.com/R0erxqG.png)

**Comment by z-brooks** [comment]
@jdanyow pull request open. Should hopefully cover most anything...

**Comment by dtaalbers** [comment]
@jdanyow  Any idea when this is getting merged? I kinda need it :)

**Comment by snicky** [comment]
me too :+1:

**Comment by jdanyow** [comment]
closing because the PR was merged- thanks again @z-brooks!
