### ISSUE TITLE
repeat.for instance changed bug with primitive values

### ISSUE THREAD

**Issue by stsje** [aurelia/templating-resources#250]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 8.1

* **Browser:**
Chrome

* **Language:**
ESNext

**Current behavior:**
https://gist.run/?id=c1974c523772771e0496bdc77ae2000a
The first `Clear` click renders the new array instance, but fills it with empty values.
The second `Clear` click correctly renders a new empty array instance.

**Expected/desired behavior:**
The first `Clear` click should render an empty array and remove all the previous input fields.
It is like the bindings are updated after the views have been cleared, and therefore rerenders the array with empty values.

It correctly clears the array if `splice` is used, but it should also work for instance changing.

**Comment by CasiOo** [comment]
Might be related https://gist.run/?id=2a357564af55860aa4fe1f8a8cfc9a05
Trying to build dynamic input fields. The old properties are being attached to the new object.
@singledigit mentioned the above example in gitter, it might be related to this issue.

**Comment by hlj** [comment]
+1

**Comment by jdanyow** [comment]
we're tracking this issue here:
* https://github.com/aurelia/binding/issues/444
* https://github.com/aurelia/binding/issues/205
