### ISSUE TITLE
Css property doesn't render background color

### ISSUE THREAD

**Issue by stsje** [aurelia/templating-resources#251]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 8.1

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **Browser:**
Chrome 53

* **Language:**
ESNext

**Current behavior:**
https://gist.run/?id=b086ab1e5a9be3a9c65422848b2cca2b

**Expected/desired behavior:**
It should apply the black background-color on the elements.
In earlier Aurelia versions `#000` would be translated to `rgb(0, 0, 0)`, and you didn't have the possibility to add `!important` at the end. Lets fix this one as well.

**Comment by Gheoan** [comment]
There are some typos in that gist: https://gist.github.com/Gheoan/b086ab1e5a9be3a9c65422848b2cca2b/revisions#diff-0

Here is the correct gist: https://gist.run/?id=b086ab1e5a9be3a9c65422848b2cca2b

Still, there are some bugs:
- `css` attribute without interpolation in the value does not translate to `style` attribute
- `!important` does not work because `element.style.background` is set to `#000 !important` which is not a valid value. For `!important` to work `element.setAttribute('style', ...)` or `element.style.setProperty('background', '#000', 'important')`(not sure about browser support) must be used.

**Comment by stsje** [comment]
Thanks, updated to the correct gist.

**Comment by z-brooks** [comment]
@stsje 
The current gist bundle isn't up to date with the recent changes (from what I can see). Setting the `#000` will work once that gets updated but I don't think `!important` will. The translation to `rgb` is a browser thing afaik. 

Using you're suggestion I've removed the regex stuff. This [pull request](https://github.com/aurelia/binding/pull/497) will allow `!important`
@jdanyow If that solution doesn't work I could stick with the regex stuff and just check for `!important` [gist](https://gist.run/?id=c410c1f0f221ffb119c104e1c6ae93dd).

**Comment by stsje** [comment]
@z-brooks Appreciate the time you have been putting into it. I commented on your pull request.

**Comment by jdanyow** [comment]
@stsje I've updated the gist- can you confirm/deny the issue is resolved. (it's an in-place update, your existing gist should work).

**Comment by stsje** [comment]
@jdanyow You have updated the gist Aurelia version? If that's the case, then there seems to be no differences from the previous version.

**Comment by z-brooks** [comment]
[benchmark](https://gist.run/?id=19d7a99852957195ad5dac3b88a9bb24) for different methods.

**Comment by CasiOo** [comment]
Interesting benchmarks. Seems using `cssText` isn't performant.
I thought `cssText` would be doing close to the same as the regex, which is parsing styles from a string.

**Comment by khenderick** [comment]
I lost a few hours on this change as apparently I did not use a correct notation, which now hit the surface. I want to add this for reference, so people that might Google for the issue might find the solution as well.

```
css.bind="{opacity: !output.inUse ? 0.65 : 1}"
```

Causes follow error: ```TypeError: value.indexOf is not a function```. Following notation is correct:

```
css.bind="{opacity: !output.inUse ? '0.65' : '1'}"
```

**Comment by CasiOo** [comment]
@khenderick You should probably open an issue about it.
Aurelia should be able to handle the number use case. Either by throw a "Not a String" error, or by supporting numbers.
