### ISSUE TITLE
@computedFrom('dependencyProp') triggers property evaluation twice for each change in dependencyProp

### ISSUE THREAD

**Issue by m-andrew-albright** [aurelia/templating-resources#253]
**I'm submitting a bug report**
- **Library Version:**
  1.0.0

**Please tell us about your environment:**
- **Operating System:**
  Windows 8.1
- **Node Version:**
  6.4.0
- **NPM Version:**
  3.10.3
- **JSPM OR Webpack AND Version**
  JSPM 0.16.39
- **Browser:**
  all
- **Language:**
  ESNext

**Current behavior:**
Each time the dependency property changes, the dependent getter is evaluated twice.

**Expected/desired behavior:**
- **What is the expected behavior?**
  The property should/could only be evaluated once.
- **What is the motivation / use case for changing the behavior?**
  Optimization!
- **GistRun Repro:**
  https://gist.run/?id=ca6a1fdea3fac12f14e239207e3395b7

**Comment by m-andrew-albright** [comment]
@AshleyGrant

**Comment by jdanyow** [comment]
What's happening is the property it depends on is updated, triggering the computed logic to read the property (execution 1) to find out if the property changed. 

If it did change, the computed logic publishes the change to it's subscribers (the interpolation binding). The interpolation binding evaluates it's expression (execution 2) to render the interpolated text.

**Comment by ISkomorokh** [comment]
Seems like this one should be close and @jdanyow 's explanation could be added to the docs.

**Comment by atsu85** [comment]
If i remember correctly, someone implemented caching, that prevented the double evaluation - not sure if it worked flawlessly or had some cornercases.

**Comment by Alexander-Taran** [comment]
not sure if it should be added to documentation. unless there are side effects like i++ 

maybe can be closed

**Comment by Alexander-Taran** [comment]
Time tested.. can be closed (-:
@bigopon

**Comment by bigopon** [comment]
The Aurelia deep computed plugin offers caching to handle this https://www.npmjs.com/package/aurelia-deep-computed
