### ISSUE TITLE
error on compose with interpolated or bound value

### ISSUE THREAD

**Issue by qraynaud** [aurelia/templating-resources#256]
**I'm submitting a bug report**
- **Library Version:**
  1.1.1

**Please tell us about your environment:**
- **Operating System:**
  Linux (KUbuntu 16.10)
- **Node Version:**
  6.9.1
- **NPM Version:**
  3.10.8
- **Browser:**
  all
- **Language:**
  all

**Current behavior:**

I wrote a simple view like this:

``` pug
template
  compose(view="user/account/${route.name}.html")
```

If I set route to `null` in the `deactivate()` method I get an error of the composer trying to load the view `user/account/.html`.

I also tried to `view.bind` instead of interpolating to see if it would make a difference but it did not.

I also added a if.bind="user" on an element wrapping the compose with the same results.

This suggest there is a rendering taking place after `deactivate()` which is not logical to me. I have other cases where I put empty objects instead of null in `deactivate()` to prevent error messages.

For example if I do:

``` pug
input(type="text" value.bind="user.firstname")
```

and I set user to null in `deactivate` I get a warning message telling me "user in user.firstname evaluates to null instead of an object". The warning would be very useful if the view was supposed to be live but deactivate already triggered and cleaned up!

**Expected/desired behavior:**
- **What is the expected behavior?**

The view should not "refresh" after deactivation to prevent error/warning messages from being emitted on a deactivated module.
- **What is the motivation / use case for changing the behavior?**

It would be cleaner and prevent users from allocating empty objects instead of using null to clean up memory at deactivation time.

**Comment by EisenbergEffect** [comment]
Deactivate is different from detached. Deactivate relates to the router lifecycle, not the component lifecycle. Can you confirm which one you mean?

**Comment by qraynaud** [comment]
Yes you're right. I really meant `deactivate` but I see your point. If there is no replacement happening, you could have a `deactivate/activate` lifecycle happening without the view actually detaching from the DOM.

That makes sense on every part.

But even knowing this, I find it counter intuitive that changes are reflected on a view that is not active anymore. When you add data on activate in the view, you intuitively clean up in its counterpart (deactivate) instead of `detached`.

**Comment by qraynaud** [comment]
I just tried with `detached` and I have no problem with the compose element that works has intended.

But in the case of the `user.firstame` acess, setting `this.user = null` in deactivate causes the warning `The 'user' part of 'user.username&validate' evaluates to null instead of an object.` to throw instead of emitting a warning. That completely breaks my navigation.

**Comment by jdanyow** [comment]
@qraynaud try using bind and unbind for this kind of cleanup. Detached happens before unbind, if you start nulling things out while things are still bound you'll run into edge cases like this.

The warning from validation will be resolved if you make the suggested change. The next release of validation has https://github.com/aurelia/validation/commit/d57f09ff35de4a2d95cef037ba008678e2d01636 which might resolve it without any changes on your end.

**Comment by qraynaud** [comment]
Ok I understand. I'll do that.

Is there a valid reason while unbind happens after detached and not before?

This seems counter intuitive to me. You should be able to clean up things loaded in a event in its counterpart safely.

**Comment by jdanyow** [comment]
`bind` happens before `attach` to ensure the dom elements take their initial state they are attached to the DOM and transitioned into view. Likewise, `detach` happens before `unbind` to ensure the elements don't mutate before they are transitioned out of view and detached from the DOM. The composition lifecycle is symmetrical in this sense.

**Comment by qraynaud** [comment]
Ok. This makes sense too. I think it would be great if this was pointed out more strongly in the documentation though. The lifecycle is described properly, what I mean is a more pratical appraoch as to what each part should be used for in a functional way.

This is pretty easy to understand once you get the sense of it, but it is not easy to get the right stuff in the right method from a beginner perspective.

**Comment by jdanyow** [comment]
good point, I've added this info to the docs: https://github.com/aurelia/framework/commit/5be6d08cbf8c6bc9c458b34eaa5df5844f1009b0

**Comment by qraynaud** [comment]
Thanks :-).
