### ISSUE TITLE
Dirty detection on form/model, i.e., $dirty

### ISSUE THREAD

**Issue by don-bluelinegrid** [aurelia/templating-resources#257]
**I'm submitting a feature request**

**Current behavior:**
I read a closed issue regarding supplying a mechanism to detect a dirty state on a form/binding:
https://github.com/aurelia/templating-resources/issues/160#issuecomment-164277649

This issue was closed, with what seemed to be an unsatisfactory answer, because it is suggested that a developer should either integrate the "quick and dirty" sample code within their *application*, or find a plugin that adds some quasi dirty-checking behavior to the framework.

Explicit indication of the dirty/changed state of a bound object is a basic and core feature of most binding frameworks.  As an AngularJS user, I know that this is well baked-in to that framework, with a $dirty flag on any form object.  This is key for a number of use cases  - only doing validation if the model object is dirty; disabling a submit button until the model object is dirty; etc.

**Expected/desired behavior:**

Since Aurelia provides a mature binding framework, that framework should include, out-of-the-box, the ability to communicate the dirty/changed state of bound objects in a view.  This is basic binding functionality.

The optimal behavior would be to provide this flag on *every* bound object, without the requirement to add anything special in code - no special view attribute, plugin, etc.  By declaring a binding, the binding should then observe and communicate the dirty state.

* **What is the motivation / use case for changing the behavior?**

See above, in expected behavior.

**Comment by KamBha** [comment]
I would go further and suggest that it would be nice to have touched and have the ability to specify sub forms where we can bind state touched and dirty state on sub forms would be nice.

I know the approach for Aurelia validation is different to angular, but having this sub form model is very useful when dealing with forms with hierarchical data.

**Comment by jods4** [comment]
The plumbing and configurability of a dirty flag is very much the same as validation.

Personally I would suggest to implement this (and move this issue) to `aurelia-validation`.

**Comment by don-bluelinegrid** [comment]
> The plumbing and configurability of a dirty flag is very much the same as validation.
> Personally I would suggest to implement this (and move this issue) to aurelia-validation.

Yes, it is.  In fact, the validator from Angular 1 provides a `$dirty` property in the validator instance.  That is critical to many validation use cases.

Don

**Comment by ppn2** [comment]
This is a very import requirement and we would expect that any mature framework handles this out of box.

**Comment by don-bluelinegrid** [comment]
@EisenbergEffect @jdanyow 

Rob, Jeremy,

I submitted this issue about four months ago, after reading through a nearly identical request that had been closed.

I'm curious if there has been any thought on this, as it is a very basic requirement for an MVX framework - most JavaScript frameworks offer this, as do Java frameworks going back to the initial version of Struts.

I have the impression that some of the team, and some of the design, of the project is based on learnings from Angular; I'd suggest taking a look at the similar functionality in AngularJS:
https://github.com/aurelia/templating-resources/issues/257#issuecomment-286502855

In AngularJS, the rendered forms/models have a number of properties that help with this - $dirty, $pristine, and also $valid.  'dirty' and 'valid' properties are intimately related requirements, because we should generally only ever check validity on an object that is 'dirty' - an object that has been modified from its initial known state.

This seems like a significant omission in a framework, and this omission has required me to create my own (admittedly limited and rudimentary) dirty-checking code in specific objects.  We really should not need to resort to this when using an advanced framework.  So, I'm wondering if there's any status update on these issues.

Thanks much,
Don

**Comment by don-bluelinegrid** [comment]
@jods4 

jods,

I would disagree with the statement:

> Personally I would suggest to implement this (and move this issue) to aurelia-validation.

Dirty detection is specifically related to the state of modification of a model object.  This is different than the state of validity of an object, because the notion of validity depends on a set of author/developer-defined rules; and, all model objects have a notion of 'modification', while not all model objects have a notion of 'validity'.

With this, there may be reasonable use cases for needing a 'dirty' flag that do not involve validation.  For example, we may want to only enable a "Save/Update" button if a model object has been changed; this has nothing to do with validation, but has everything to do with the model's state of modification.  For this reason, it doesn't seem to make sense to tightly couple this functionality with a validation module.  It should be available to be used *in conjunction with* a validation module.

Thanks,
Don

**Comment by EisenbergEffect** [comment]
I think that @jdanyow has a prototype of this built as an extension of sorts at one time.

**Comment by jods4** [comment]
@don-bluelinegrid 
> there may be reasonable use cases for needing a 'dirty' flag that do not involve validation. 

This does not preclude the fact that this functionality could be included in `aurelia-validation` and can be used without defining validation rules at all.

The fact is, implementation of validation and dirtiness share some concepts and infrastructure. For example you need to define the scope you want to validate/dirty-track. It can be one object, or several. It could include nested objects or arrays. There might be properties you'd like to ignore.

Validation builds on top of dirtiness since, as you mention, good validation feedback needs to act differently whether a property is pristine or dirty. You also need to be able to reset the pristine set of the whole scope, or property by property, and that should directly impact the matching validation.

In the end, the two are linked -- or at least validation is an extension of dirty-tracking.
We could lift the dirty parts into `aurelia-binding` (which would seem more appropriate than `aurelia-templating-resources`, this repo is meant to contain a collection of standard behaviors: custom elements, attributes, value converters, binding behaviors) or we could put the whole thing inside `aurelia-validation`, that can be discussed by the lead of each library.

**Comment by jdanyow** [comment]
@don-bluelinegrid - I'd like to flesh out the requirements a bit more- couple questions for you:

1. Can you flesh this idea out a little bit more- provide some pseudo code that would illustrate what the API looks like in practice:

    >The optimal behavior would be to provide this flag on every bound object, without the requirement to add anything special in code - no special view attribute, plugin, etc. By declaring a binding, the binding should then observe and communicate the dirty state.

2. When you tried https://github.com/aurelia/templating-resources/issues/160#issuecomment-164277649  , where does it fall down for you? Where does it work well?

*please keep in mind many of us are not Angular users so we've come at dirty tracking in different ways then what your experience may have been.*

**Comment by jods4** [comment]
> The optimal behavior would be to provide this flag on every bound object, without the requirement to add anything special in code

I am not sure "optimal" is the right word here. 

In a typical Aurelia application there are _tons_ of bindings. Adding even a single `bool` to _every one of them_ is very wasteful.
Is this a price we want to pay? Is there a way to merge those bits into existing binding state?

The typical use case is a form model, which could be "dirty-tracking enabled" by an API. That model probably needs validation rules anyway, so it's not adding much to the user code, if at all: dirty-tracking could be automatically enabled when validation is used.

**Comment by ppn2** [comment]
Is there any progress on this. It has been six months since this issue has been opened. I can not stress enough the importance of this feature in any serious enterprise application.

**Comment by jdanyow** [comment]
@ppn2 we haven't committed to implementing this feature. There are open questions on how this should work and the perf implications (see my comments and @jods4's comments above).

Like I said in https://github.com/aurelia/templating-resources/issues/257#issuecomment-287257951, part of the challenge with this is I've never seen this $dirty pattern in use. I've never been an angular developer. In the apps I've worked on (serious enterprise apps :wink:) , validating the model and tracking whether the model is unchanged/modified/new were not the responsibility of the forms/data-bindings.

**Comment by mryellow** [comment]
> mature framework handles this out of box
...
>  very basic requirement for an MVX framework 
...
>  It has been six months since this issue has been opened. 

There are about 10-20 different ways you could decide to do it depending on your use-case. All of them more efficient then a global *"dirty checking is done for you"*.

**Comment by mryellow** [comment]
>  has required me to create my own (admittedly limited and rudimentary) dirty-checking code in specific objects

@don-bluelinegrid See how that is more efficient? You only needed a specific type of checking in a specific area, no need to tax every other part of your code with this burden.

**Comment by Alexander-Taran** [comment]
Should be closed

**Comment by EisenbergEffect** [comment]
Closing this since we're not planning on adding a dirty flag. Using existing plugin points, such as binding behaviors, this could be built as an addon.
