### ISSUE TITLE
Correct dependencies in 1.1.X?

### ISSUE THREAD

**Issue by don-bluelinegrid** [aurelia/templating-resources#258]
In the latest version of templating-resources (v1.1.1) the package.json shows a dependency on templating v1.0.0; however, latest version of templating is v1.1.2.

Is this correct, or should the 1.1.X version of templating-resources depend on a 1.1.X version of templating?  If so, templating-resources package.json needs to be corrected.

**Comment by EisenbergEffect** [comment]
templating-resources doesn't *require* anything beyond 1.0.0.
