### ISSUE TITLE
require scss files in templates fails with errors when working with webpack

### ISSUE THREAD

**Issue by florinspataru1** [aurelia/templating-resources#262]
While working with webpack, if you use require to include partial scss files I am getting errors:

1. When using webpack-dev-server: `Error: No module factory available for dependency type: ContextElementDependency`
2. When bundling, the final bundle will throw errors loading "<scss_file_path>.scss.html" files.

To solve this I've made a PR #261 that solves the issue. Thanks to @sickboy and Overpass.com Team

**Comment by EisenbergEffect** [comment]
Closing this since we've got the broader issue tracked as a feature request.
