### ISSUE TITLE
Concurrent enter/leave transitions

### ISSUE THREAD

**Issue by mroseboom** [aurelia/templating-resources#264]
**I'm submitting a feature request**

**Current behavior:**
I read a closed issue on the animator-css branche regarding concurrent enter/leave transitions between the outgoing and incoming views:
[issue](https://github.com/aurelia/animator-css/issues/7)

Rob mentioned also the following within this issue.
> This is supported now in the router-view and we'll add it to the compose element as well. See the latest release blog post for more information.

**Expected/desired behavior:**
Am wondering if it would be possible to implement this feature also for the compose method.

Within the aurelia-router plugin this feature is already implemented:
> The router-view has a new property swap-order which lets you control the swaping order of views. By default, it is set to "before" which adds the new view before removing the old view. It can also be set to "with" and "after".

`<router-view swap-order="with"></router-view>`

* **What is the motivation / use case for changing the behavior?**
See above, in expected behavior.

**Comment by EisenbergEffect** [comment]
This might make a nice contribution as well, if you are interested.

**Comment by mroseboom** [comment]
Sure, i will take a look and see if i can make a PR that implements this feature.

**Comment by mroseboom** [comment]
@EisenbergEffect  Hi Rob, I think i've implemented this feature. Yesterday i tried to create a gist, but (still) have some trouble to use the custom version of both plugins.

Only the implementation covers both the following branches:
- aurelia-templating [`composition-engine.js`](https://github.com/mroseboom/templating/commit/6a7704366a9ab211302398bf90e863b3abf711af)
- aurelia-templating-resources [`compose`](https://github.com/mroseboom/templating-resources/commit/68b52e5ae115bf34e65a6d3ec23213dd05fb45c2)

Furthermore there are no unit tests created yet. Because I didn't see any unit tests within the templating-router branche relating to the `swap-order` attribute.

Would you like to take a look at the code? If the implementation is done the correct way.

**Comment by EisenbergEffect** [comment]
Absolutely. Go ahead and submit a pull request and we can do a code review. Thanks!
