### ISSUE TITLE
Error when using reflect-metadata as metadata target is a string

### ISSUE THREAD

**Issue by timfish** [aurelia/templating-resources#267]
The implementation of `Reflect.getOwnMetadata` differs in `reflect-metadata` vs `aurelia-polyfills`

In `reflect-metadata` `target` must be an object or it throws:

```
    export function getOwnMetadata(metadataKey: any, target: Object, targetKey?: string | symbol): any {
        if (!IsObject(target)) throw new TypeError();
        if (!IsUndefined(targetKey)) targetKey = ToPropertyKey(targetKey);
        return OrdinaryGetOwnMetadata(metadataKey, target, targetKey);
    }
```
This isn't checked in `aurelia-polyfills`
```
  Reflect.getOwnMetadata = function(metadataKey, target, targetKey) {
    if (target.hasOwnProperty(metadataContainerKey)) {
      return (target[metadataContainerKey][targetKey] || emptyMetadata)[metadataKey];
    }
  };
```

The following code in `show.js` causes an exception as `DOM.boundary` is a string:
```
@customAttribute('show')
@inject(DOM.Element, Animator, Optional.of(DOM.boundary, true))
export class Show {
```

Should `target` always be an object?

**Comment by timfish** [comment]
The [spec says](https://github.com/rbuckton/ReflectDecorators/blob/master/spec/metadata.md#reflecthasownmetadata--metadatakey-target--propertykey-):
```
If Type(target) is not Object, throw a TypeError exception.
```

**Comment by EisenbergEffect** [comment]
I'm not following why DOM.Boundary would relate to this.

**Comment by timfish** [comment]
when I debug the exception `targe

**Comment by timfish** [comment]
when I debug the exception the parameters for `Reflect.getOwnMetadata` are
- `metadataKey` = `'aurelia:registration'` 
- `target` = `'aurelia-dom-boundary'`

**Comment by timfish** [comment]
And the call stack looks like: 

![image](https://cloud.githubusercontent.com/assets/1150298/21215378/1dddf45a-c2a1-11e6-82ee-6d84d90284f8.png)

**Comment by altenstedt** [comment]
I see the same issue after updating all packages.  I see the problem in IE only.  The issue is that in aurelia-metadata/metadata.js:65, we call Object.getPrototypeOf(target) with a target string value of "aurelia-dom-boundary".

**Comment by 4nderss** [comment]
Any solution for this? Kinda broke our builds and can't get our system up for IE.

**Comment by EisenbergEffect** [comment]
I believe this is a bug in metadata that is only now surfaces after we fixed a bug in dependency injection. Can you try revering only aurelia-dependency-injection back one version to see if the problem goes away?

**Comment by altenstedt** [comment]
I can confirm that installing aurelia-dependency-injection@1.2.0 solves the issue for me, and allows me to run our app in IE.

**Comment by 4nderss** [comment]
Yep, that works
