### ISSUE TITLE
Latest 1.3.0 release throws self-binding-behavior missing

### ISSUE THREAD

**Issue by ghiscoding** [aurelia/templating-resources#274]
**I'm submitting a bug report**

* **Library Version:**
1.3.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.6.0

* **NPM Version:**
3.10.10

* **Webpack**
webpack 2.1.0-beta.27

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
Since version `1.3.0` of the `templating-resources`, I get an error thrown in the console. I tried with `yarn` and then deleted the `node_modules` and retried with `npm install` to get same result.

> Cannot find module './aurelia-templating-resources/self-binding-behavior'.

**Expected/desired behavior:**

I found the error being the latest version `1.3.0` and if I revert back to using `1.2.0` then all is good. 
* **Step to reproduce**
Install package dependencies as `"aurelia-templating-resources": "^1.3.0"` will create the bug, however fixing the version to `"aurelia-templating-resources": "~1.2.0"` removes the problem. You could also clone a simple skeleton to showcase some [Aurelia Bootstrap Plugins](https://github.com/ghiscoding/Aurelia-Bootstrap-Plugins) that I made available publicly, you can clone the [repo](https://github.com/ghiscoding/Aurelia-Bootstrap-Plugins) then go under `client-wp` and change the `package.json` to install the version `1.3.0` or `aurelia-templating-resources` then install/run to see the error thrown in the console.
* **What is the expected behavior?**
No error in the console.
* **Extra comments** 
~~Please note that Aurelia-CLI does not seem to be affected by this issue.~~

**Comment by EisenbergEffect** [comment]
Looking into it.

**Comment by EisenbergEffect** [comment]
What do you mean that the CLI isn't affected?

**Comment by ghiscoding** [comment]
Sorry I just realized after your comment that this is not part of the Aurelia-CLI, hence there's no issue there. Sorry about the confusion

**Comment by EisenbergEffect** [comment]
Try doing an NPM update. I'm not sure if NPM correctly pulled in the other version changes. It's working fine for me in my tests.

**Comment by ghiscoding** [comment]
Did an NPM update and still get same issue. However, NPM update doesn't seem to always work. So I went manually and updated all packages including `webpack` itself to `2.2`

Perhaps you can try cloning my [simple repo](https://github.com/ghiscoding/Aurelia-Bootstrap-Plugins/tree/master/client-wp).

Note that again, if I revert to the older version of `"aurelia-templating-resources": "~1.2.0"` it works as expected.

Here's the complete list
```javascript
"dependencies": {
    "aurelia-bootstrap-datetimepicker": "^0.3.2",
    "aurelia-bootstrap-tagsinput": "^0.3.2",
    "aurelia-bootstrapper-webpack": "^1.1.0",
    "aurelia-event-aggregator": "^1.0.1",
    "aurelia-fetch-client": "^1.1.1",
    "aurelia-framework": "^1.1.0",
    "aurelia-history-browser": "^1.0.0",
    "aurelia-http-client": "^1.0.4",
    "aurelia-loader-webpack": "^2.1.0",
    "aurelia-logging-console": "^1.0.0",
    "aurelia-pal-browser": "^1.1.0",
    "aurelia-polyfills": "^1.2.0",
    "aurelia-route-recognizer": "^1.1.0",
    "aurelia-router": "^1.2.1",
    "aurelia-templating-binding": "^1.3.0",
    "aurelia-templating-resources": "^1.3.0",
    "aurelia-templating-router": "^1.1.0",
    "babel-polyfill": "^6.23.0",
    "bluebird": "^3.4.7",
    "bootstrap": "^3.3.7",
    "eonasdan-bootstrap-datetimepicker": "^4.17.46",
    "font-awesome": "^4.7.0",
    "isomorphic-fetch": "^2.2.1",
    "jquery": "^3.1.1",
    "moment": "^2.17.1"
  },
  "devDependencies": {
    "@easy-webpack/config-aurelia": "^2.2.4",
    "@easy-webpack/config-babel": "^4.0.2",
    "@easy-webpack/config-common-chunks-simple": "^2.0.3",
    "@easy-webpack/config-copy-files": "^1.1.2",
    "@easy-webpack/config-css": "^4.0.2",
    "@easy-webpack/config-env-development": "^2.1.6",
    "@easy-webpack/config-env-production": "^3.0.0",
    "@easy-webpack/config-external-source-maps": "^3.1.0",
    "@easy-webpack/config-fonts-and-images": "^3.0.0",
    "@easy-webpack/config-generate-index-html": "^2.1.1",
    "@easy-webpack/config-global-bluebird": "^2.1.0",
    "@easy-webpack/config-global-jquery": "^2.1.1",
    "@easy-webpack/config-global-regenerator": "^1.3.0",
    "@easy-webpack/config-html": "^3.1.0",
    "@easy-webpack/config-json": "^3.1.0",
    "@easy-webpack/config-test-coverage-istanbul": "^3.2.0",
    "@easy-webpack/config-uglify": "^2.2.3",
    "@easy-webpack/core": "^2.0.1",
    "aurelia-protractor-plugin": "^1.0.1",
    "aurelia-tools": "^1.0.0",
    "babel-plugin-transform-class-properties": "^6.23.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-env": "^1.1.10",
    "babel-register": "^6.23.0",
    "concurrently": "^3.3.0",
    "cross-env": "^3.1.4",
    "del-cli": "^0.2.1",
    "eslint": "^3.16.1",
    "http-server": "^0.9.0",
    "jasmine-core": "^2.5.2",
    "karma": "^1.5.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.1.0",
    "karma-mocha-reporter": "^2.2.2",
    "karma-remap-istanbul": "^0.6.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^2.0.2",
    "protractor": "^4.0.11",
    "wait-on": "^2.0.2",
    "webpack": "2.2.1",
    "webpack-dev-server": "2.4.1"
  }
```

**Comment by stoffeastrom** [comment]
I just [compared](https://github.com/aurelia/templating-resources/compare/1.2.0...1.3.0) the tags and it looks like `self-binding-behavior` was added. I think we missed to add it into the `package.json` build resources.. 

![image](https://cloud.githubusercontent.com/assets/682243/23352482/9ecaa0a8-fcc7-11e6-9343-2ad4b54d644a.png)

**Comment by marktaling** [comment]
I've noticed the same issue and came to the same conclusion as @stoffeastrom.

**Comment by devteamexpress** [comment]
Same Issue here, all is broken with the latest release. Downgrading to 1.2.0 fixes it

**Comment by EisenbergEffect** [comment]
Try release 1.3.1

**Comment by ghiscoding** [comment]
Thanks, the latest `1.3.1` fixed the issue.
