### ISSUE TITLE
Add $length to the repeat.for utilities

### ISSUE THREAD

**Issue by gpetrioli** [aurelia/templating-resources#276]
**I'm submitting a feature request**

* **Library Version:**
1.3.1

* **Language:**
all

**Current behavior:**
In the utilities for `repeat.for` we have `$first`,`$index`, `$last`, `$middle`, `$odd` and `$even`. 

**Expected/desired behavior:**
Could we add a `$length` which contains the usable length (*after applying valueConverters that filter the iterable items*)

----

My understanding is that we only need to add the `overrideContext.$length = length;` in the 
https://github.com/aurelia/templating-resources/blob/master/src/repeat-utilities.js#L54-L65 since the `length` in there is already the filtered one.

**Comment by gpetrioli** [comment]
@EisenbergEffect i can provide the PM if you wish to add this enhancement.

**Comment by EisenbergEffect** [comment]
Go for it! :)

**Comment by gpetrioli** [comment]
Look like it requires to remove some optimizations from the array-repeat-strategy file. 

When mutating the array (*`push`/`pop`/`splice`*) the current code identifies the lowest index that was mutated and updates the `overrideContext` only for the elements from that point on.

To allow for `$length` we need to update the `overrideContext` for all elements in the array since it affects all of them (*other wise the new tests i added fail*).

In my commits (https://github.com/gpetrioli/templating-resources/blob/add-length-to-repeat-utilities/src/array-repeat-strategy.js#L227-L235) i have `updateOverrideContexts(repeat.views(), 0);` instead of `updateOverrideContexts(repeat.views(), spliceIndexLow);` but i want to ask if i should remove the whole splice index calculation since they are not used anywhere else (*and these functions are not exported*)

**Comment by jdanyow** [comment]
this might be a better fit for the "let" element we've been planning:

```html
<let filtered="myArray | filter | sort | etc"></let>
<ul>
  <li repeat.for="item of filtered">${$index} of ${filtered.length}</li>
</ul>
```

https://github.com/aurelia/templating-resources/issues/171

**Comment by gpetrioli** [comment]
@jdanyow  wasn't aware of this. That is pretty cool.

Can/will it support multiple attribute/variables ?  `<let a="something | filter | sort" b="somethingelse | filter" c="..."></let>` ?

Also any estimation on when this feature might be available ?

**Comment by Alexander-Taran** [comment]
I think @gpetrioli comment points to why .sort() mangles stuff.
https://github.com/aurelia/framework/issues/721

Other than that - stale issue

**Comment by EisenbergEffect** [comment]
Will close this since we have a `let` implementation in progress that seems like it should be able to handle this scenario.

**Comment by saqibn** [comment]
any status on this?
