### ISSUE TITLE
Require stylesheets other than CSS

### ISSUE THREAD

**Issue by jods4** [aurelia/templating-resources#277]
Support for CSS in `<require from="style.css">` is currently hardcoded here:
https://github.com/aurelia/templating-resources/blob/fe7a836504a0ee0fdc8e53480cd9f3d6c9dc4f7e/src/aurelia-templating-resources.js#L66

Today lots of people use pre-processors, like LESS or SASS.

In a webpack build, `<require from="style.less">` would do just what you expect (great!)... except that it would fail at runtime without some hardcore configuration because the module extension is not `.css`.

A quick easy fix that would help 90% of our users can be to hardcode a few more values, I suggest adding `.scss`, `.sass`, `.less`. That's very reasonable defaults.

Of course going the extra mile would be exposing a configuration api for exotic preprocessors, but that's a lot more work for less benefits (few users, if any, that could use other work-arounds).

The fix should also be applied in HMR, where this is duplicated CC @niieani

**Comment by niieani** [comment]
I'm ok with this. Small fixes with large impact is what we should be looking for.

**Comment by jods4** [comment]
PR #279 does that.

Of course the PR only enables the `<style>` behavior for more extensions, but it assumes the module contents are proper CSS. It would have been compiled at build time.

For example, in a Webpack build one can set up the following loader:
```js
module: {
  rules: [
    { test: /\.less$/i, use: ["css-loader", "less-loader"] },
  ]
}
```
Then do this in a view:
```html
<require from="nav-bar.less"></require>
```
And it works as expected.
