### ISSUE TITLE
Focusing element via binding doesn't always work

### ISSUE THREAD

**Issue by mmalek06** [aurelia/templating-resources#281]
I'm submitting a bug report

Library Version:
1.3.1

Operating System:
Windows 10

NPM Version:
3.10.8

JSPM 0.16.48

Browser:
all

Language:
ESNext

Current behavior:

Given following view model:

```
export class ExpandingInput {  
    // ctor
    constructor() {
        this.expanded = false;
    }

    // actions
    toggle() {
        this.expanded = !this.expanded;
    }
}
```

and template:

```
<template>

    <div class="expanded-input wrapper">
        <input focus.trigger="toggle()" />

        <textarea if.bind="expanded"
                  focus.bind="expanded"
                  blur.trigger="toggle()"
                  rows="4">
        </textarea>
    </div>

</template>
```

The behavior is that when I first click/tab into/otherwise focus the input element, the textarea element shows up and is focused. Then I click somewhere else, so that the textarea looses focus. Now when I again click on the input, the textarea shows up but is not focused (input element is).

Expected/desired behavior would be for the html elements to always behave consistently, not only on the first time :).

Two notes: if I remove the `if.bind` expression, it works. I went around this problem by not using `if.bind` and instead binding css classes to hide/show element like that `class="${expanded ? 'show' : 'hide'}"` but I don't think the former should work as it is now.

**Comment by jdanyow** [comment]
What happens if you remove the blur.trigger binding?

Can you provide a gist? https://gist.run/?id=7542e061bc940cde506b

**Comment by mmalek06** [comment]
https://gist.run/?id=0b41930fcb35e226faacd7cf2e0003d1

I don't understand why, but after removing blur.trigger it started working properly :). Anyway - with the provided code you can recreate my issue 100% times.

**Comment by Alexander-Taran** [comment]
@jdanyow what did you had in mind about blur trigger?

**Comment by bigopon** [comment]
Workaround is to add a `debounce` to `blur.trigger`:

```html

      <textarea if.bind="expanded"
                focus.bind="expanded"
                blur.trigger="toggle() & debounce:1"
                rows="4">
      </textarea>
```

I think the reason is because binding doesn't have time to sync with the source. Sniping @fkleuver

**Comment by Alexander-Taran** [comment]
@bigopon 
close this maybe??
