### ISSUE TITLE
Strange behavior with sort order in lists - Dragula with Aurelia

### ISSUE THREAD

**Issue by radenkozec** [aurelia/templating-resources#282]
**I'm submitting a bug report**

* **Library Version:**
Aurelia Templating 1.1.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
JSPM 0.16.32

* **Browser:**
Chrome

* **Language:**
 ESNext

**Current behavior:**
I am using Dragula with Aurelia and everything works fine. However I did not called DragApi.cancel to cancel Dragula events like here https://github.com/jdanyow/aurelia-solitaire/blob/master/src/drag-and-drop.js#L41
because I need specific Dragula functionalities such as animations when drag-dropping, auto scrolling etc.

I have a weird behavior. I use server side sorting for items inside list.
When I drag-drop few items (change sort order of items) in list , save new sort order on server side and then refresh data like this:
` this.columnList = result;`
sort order of items in list I get from server side is changed on client side.
It seams like Aurelia try to re-apply drag and drop operations that previously happens and apply same operations.
This way sort order of items in list is changed.

**Expected/desired behavior:**
Not sure why is this happening. Why drag and drop can affects Aurelia behavior and how to prevent this?

**Comment by EisenbergEffect** [comment]
@jdanyow You've got some experience with Dragula. Any ideas?

**Comment by jdanyow** [comment]
If you allow Dragula to move a DOM element that is managed by the Aurelia repeat.for, things will get out of sync. The repeat.for has no knowledge of the things Dragula is doing to the DOM.

**Comment by radenkozec** [comment]
@jdanyow @EisenbergEffect  Any suggestion what to do? If I understand correctly Aurelia just don't play nice with popular Drag and Drop libraries like Dragula or Sortable right? I will try to create dummy empty project to reproduce this behavior.

**Comment by radenkozec** [comment]
@jdanyow @EisenbergEffect I managed to solve all issues by calling DragApi.cancel and removing / add elements from arrays manually. Just wanted to say keep up the good work. Aurelia is great.
