### ISSUE TITLE
Provide out-of-the box event-handler for specific key for convenience

### ISSUE THREAD

**Issue by atsu85** [aurelia/templating-resources#283]
**I'm submitting a feature request**
Consider providing a custom attribute or binding behavior that would allow to handle specific keyup events, such as pressing enter

* **Library Version:**
1.4.0

**Current behavior:**
Currently if i'd like to handle only for example enter keypress on textbox (and i don't want to bloat the event handler JS code to contain checks for event keyCode), I'd need to create a custom attribute or binding behaviour myself and use them smth like:
`keyup-enter.call="handleEvent()"` in case of custom attribute ([as show in Aurelia vs Angular 2 comparison vidoe](https://www.youtube.com/watch?v=bAYe1CmrCWg&feature=youtu.be&t=24m46s))
or 
`keyup.delegate="handleEvent() & onEnter` in case of enter specific binding behavior
or 
`keyup.delegate="handleEvent() & onKey:'enter'"` in case of generic  binding behavior (told to accept etner key press).
or perhaps even 
`keyup.enter="handleEvent()"`

**Expected/desired behavior:**
It would be nice, if Aurelia provided smth like that already out of the box, like Angular2 does (`(keyup.enter)="handleEvent()")`).

* **What is the expected behavior?**
Aurelia could include smth like that out of the box. I created [this gist](https://gist.run/?id=8cdcddb33969c7fbbbb7e29718a22c6b) that implements 
> `keyup.delegate="handleEvent() & onKey:'enter'"` in case of generic  binding behavior

(based @jdanyow's [example](https://github.com/aurelia/templating-resources/issues/186#issuecomment-181676759))

* **What is the motivation / use case for changing the behavior?**
Ease of development. [In a video comparing Angular2 with Aurelia](https://www.youtube.com/watch?v=bAYe1CmrCWg&feature=youtu.be&t=22m40s), it looks like Aurelia requires a lot of work for simple situation like binding event handler to enter keypress.

@jdanyow, @EisenbergEffect, wouldn't it be nice if Aurelia provided it out of the box?

**Comment by jdanyow** [comment]
A lot of times something like this is done by putting the input in a form
and binding to the form's submit event so that the semantics are correct
and the enter key handling is done by the browser, it's accessible, etc

**Comment by atsu85** [comment]
@jdanyow, actually that is what i also suggested (through the video comment) yesterday as an easier alternative for that specific case (even created a gist to demonstrate it) where he only had one input element. 

However it seemed that the video author wanted to be able to write Aurelia app in the same style that he wrote Angular app (without having to add special markup only needed for Aurelia). I suspect that lack of this functionality might trouble others new to Aurelia as well in similar situation. Or perhaps there could be more than one element that could take advantage of input-field specific key handler.

Just wanted to know Aurelia core team thoughts on this subject - clearly he was in trouble with Aurelia as he thought he felt had to create a [KeyupEnterCustomAttribute](https://www.youtube.com/watch?v=bAYe1CmrCWg&feature=youtu.be&t=24m46s) himself instead of using smth from the framework. So perhaps smth could be added to the framework.

**Comment by jdanyow** [comment]
gotcha, makes sense.

My vote is to promote using `<form submit.trigger="...">` for the enter-key use-case because it's the semantically correct, accessible way to implement that UI pattern. I think a custom attribute or binding behavior for that use-case is a foot-gun. Could be useful in other use-cases. I think @bigopon had looked into something like this in the past.

**Comment by bigopon** [comment]
@jdanyow , @atsu85 

Hi yes I did look into implementation of this behavior, and was a bit stuck by it being generic enough ( a request from @EisenbergEffect ),

I've updated the gist and you can have a play at : [Keys updated](https://gist.run/?id=b289897836b10d2de99c2d395722b5ad)

**Comment by bigopon** [comment]
@jdanyow , @atsu85 , @EisenbergEffect 

[Gist](https://gist.run/?id=b289897836b10d2de99c2d395722b5ad)

I've tried to make it more generic by supporting both mouse and keyboard events in case user predefined clearly what keys should go in for the behavior. But couldn't figure out how to deal with the case where user bind the keys with another view model. I've prepared the view / input for dynamic keys binding so if anyone has an idea how to do it, can upgrade from there.

I think if this problem can be solved, the binding behavior is ready to be evaluated for baking into core.

**Comment by Alexander-Taran** [comment]
seems like a good candidate for contrib

this one seesm to not get into core

**Comment by EisenbergEffect** [comment]
I think we'll close this since I agree it doesn't need to be in the core of the framework and can be added via a plugin.

**Comment by Alexander-Taran** [comment]
Oh.. and to add ~~insult to the injury~~ some insight: there is a plugin for that already
https://github.com/tomtomau/aurelia-mousetrap
