### ISSUE TITLE
Loading arbitrary CSS files from views

### ISSUE THREAD

**Issue by diegohb** [aurelia/templating-resources#294]
**I'm submitting a bug report**

* **Library Version:**
aurelia-templating-resources: v1.4.0
aurelia-cli: 0.30.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.10.2

* **NPM Version:**
4.2.0

* **JSPM OR Webpack AND Version**
Using aurelia-cli w/ systemjs v0.20.13

* **Browser:**
Chrome 59.0.3071.115 

* **Language:**
TS v2.3.2

**Current behavior:**
from app.html view, 
<require from="styles/my_arbitrary_cssfile.css"></require>
throws error "failed loading ..." I also tried !text for SystemJS text plugin but that gives me an error about invalid "." or "{".. like it's trying to read css as JS.

```
function fixupCSSUrls(address, css) {
    if (typeof css !== 'string') {
      throw new Error('Failed loading required CSS file: ' + address);
    }
.....
```

**Expected/desired behavior:**
Should work without !text just like it does in latest version of skeleton projects on github. I think the !text plugin should work as well but i'm not sure..

**Comment by EisenbergEffect** [comment]
@JeroenVinke Can you check if referencing a css file from a view works with a cli-generated system.js configuration?

**Comment by JeroenVinke** [comment]
That seems to work ok:

app.html:
```
<template>
  <require from="./test.css"></require>
  <h1>${message}</h1>
</template>
```

test.css:
```
body { background-color: red; }
```

@diegohb I can't see the code you've provided in the issue to reproduce, can you show me what you're doing differently from what I do above?

**Comment by diegohb** [comment]
will try it again. thank you!

**Comment by diegohb** [comment]
loading external css files...  is what the title of this shouldve been.. but maybe that's not intended to work?

`<require from="https://cdn.jsdelivr.net/leaflet/1.0.2/leaflet.css"></require>`

**Comment by EisenbergEffect** [comment]
Ah. This is going to be loader dependent. If you are using Require.js for example, you need to make sure that you aren't stubbing out the text loader, or it won't be able to dynamically load the css at runtime.

**Comment by diegohb** [comment]
I'm using SystemJS, might need the css plugin if the text plugin can't handle it.. thanks!
