### ISSUE TITLE
Matcher binding on repeat elements is only working the first time the element is attached

### ISSUE THREAD

**Issue by suneelv** [aurelia/templating-resources#295]
**I'm submitting a bug report**

* **Library Version:**
1.4.0

**Please tell us about your environment:**
* **Operating System:**
Same issue on both OSX and Windows10

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
webpack 3.3.0

* **Browser:**
all 

* **Language:**
ESNext

**Current behavior:**

Array repeat strategy is losing the matcher binding once the element is removed from the view. The function bound to `matcher` on repeat is only called when the element is rendered the first time. Once the parent element (element which contains repeat elements) is removed from dom (because of if binding/route change) and attached to the dom again, the matcher is not called from here on.

**Expected/desired behavior:**

https://gist.run/?id=fe857a95d87d2f07bd5a8ee86e1fd15e

When the element is attached for the first time, scope has a matcher
![image](https://user-images.githubusercontent.com/6492948/28590192-8f4d0952-7181-11e7-9cad-9f79f8119c41.png)

When the element is attached again later, scope has no matcher
![null matcher](https://user-images.githubusercontent.com/6492948/28994809-7974da16-79d7-11e7-927c-040b559c0933.png)

* **What is the expected behavior?**
The function bound to matcher should be called everytime

**Comment by suneelv** [comment]
I believe the culprit is 

```
  _captureAndRemoveMatcherBinding() {
    if (this.viewFactory.viewFactory) {
      const instructions = this.viewFactory.viewFactory.instructions;
      const instructionIds = Object.keys(instructions);
      for (let i = 0; i < instructionIds.length; i++) {
        const expressions = instructions[instructionIds[i]].expressions;
        if (expressions) {
          for (let ii = 0; i < expressions.length; i++) {
            if (expressions[ii].targetProperty === 'matcher') {
              const matcherBinding = expressions[ii];
              expressions.splice(ii, 1);
              return matcherBinding;
            }
          }
        }
      }
    }

    return undefined;
  }
```
in https://github.com/aurelia/templating-resources/blob/master/src/repeat.js
This is removing the matcher expression from the viewFactory if it is found. But I guess viewFactory is cached and the next time the element is bound, the `matcher` expression won't be there

**Comment by EisenbergEffect** [comment]
Should be fixed by this: https://github.com/aurelia/templating-resources/pull/372

**Comment by Seebiscuit** [comment]
I'm experiencing the same problem and it is not fixed by #372. The issues is that this line https://github.com/aurelia/templating-resources/blob/9d3be39948644990ba2755b3fb28b1a8329fb355/src/repeat.js#L227
removes the matcher expression from the view factory. So, if the parent view that implements the Repeater is removed from the DOM and then re-rendered, the second time `_captureAndRemoveMatcherBinding` is invoked, the expression has already been removed.

**Comment by bigopon** [comment]
@Seebiscuit thanks for the explanation. I think its potentially is the issues. Probably it wont be hard to fix, can you help create a small repro for this?

**Comment by Seebiscuit** [comment]
Thanks for looking into this @bigopon. I made a minimal repro here: https://gist.dumber.app/?gist=fc7be8c1f018dab0029267501c8a7c9e.

To debug the issue, open DevTools and open *aurelia-templating-resources.js*. Drop a breakpoint on line 1244 (as of the date of this post, it should be pointing to https://github.com/aurelia/templating-resources/blob/9d3be39948644990ba2755b3fb28b1a8329fb355/src/repeat.js#L223

You'll notice that when the app first loads `expressions` is truthy. Then, if you toggle the component with the repeater, the next time the code breaks here `expressions` is no longer available.
