### ISSUE TITLE
repeat.for weird binding behavior

### ISSUE THREAD

**Issue by Awaken6389** [aurelia/templating-resources#30]
I made a custom element that I pass two properties to (item and recommendations). Initially evetyhing works fine, but when I add another record to ValueRecommendation I get an error:

    Uncaught TypeError: Cannot read property 'undefined' of undefined ast.js:72
        
        
Here's a part of the template:
        
    <a href="#" class="selectable_item ${recVal.Selected ? 'active' : ''}" repeat.for="recVal of recommendations.NameRecommendation[item.Id].ValueRecommendation" click.delegate="$parent.selectItem($parent.item.Id, $index)" if.bind="!recVal.Disabled">
    <i class="fa fa-fw ${recVal.Selected ? 'fa-check-square-o' : 'fa-square-o'}" if.bind="$parent.recommendations.NameRecommendation[$parent.item.Id].ValidationRules.MaxValues > 1" ></i>
    <i class="fa fa-fw ${recVal.Selected ? 'fa-check' : ''}" if.bind="$parent.recommendations.NameRecommendation[$parent.item.Id].ValidationRules.MaxValues == 1"></i> ${recVal.Value}
    </a>
        
I tracked this down to:
        
    if.bind="$parent.recommendations.NameRecommendation[$parent.item.Id].ValidationRules.MaxValues > 1"
    if.bind="$parent.recommendations.NameRecommendation[$parent.item.Id].ValidationRules.MaxValues == 1"
        
If I remove those "ifs" then after item is added to ValueRecommendation it pops up on the list, but if put them back on I get the error and repeat.for does not refresh.

**Comment by martingust** [comment]
@Awaken6389 Is this still a issue? A couple fixes that might be related to this have been released.

**Comment by jdanyow** [comment]
@Awaken6389 can this be closed?

**Comment by jdanyow** [comment]
closing- no response.
