### ISSUE TITLE
repeat.spec.js tests repeat object from jspm package instead of one from the project source

### ISSUE THREAD

**Issue by Alexey1** [aurelia/templating-resources#300]
**I'm submitting a bug report**

* **Library Version:**
1.4.0

**Please tell us about your environment:**
* **Operating System:**
Windows 8

* **Node Version:**
6.9.2

* **NPM Version:**
4.3.0

* **JSPM OR Webpack AND Version**
Aurelia CLI 0.30.1

* **Browser:**
Chrome 60

* **Language:**
TypeScript 2.4.2

**Current behavior:**
repeat.spec.js tests file
jspm_packages/npm/aurelia-templating-resources@1.0.0-rc.1.0.2/repeat.js 
instead of file
src/repeat.js

STR:
1. Setup as described in Readme.md
2. Add "debugger;" line in one of the tests like so:
```
it('should do nothing if no items provided', () => {
      let didThrow = false;
      repeat.items = undefined;

      try {
        debugger;
        repeat.bind();
      } catch (e) {
        didThrow = true;
      }

      expect(didThrow).toBe(false);
    });
```
2. Run command ```karma start```

3. Open dev tools in karma browser

4. Refresh page if needed, wait until "debugger" line starts debug mode

5. Step into repeat.bind(); method

6. Notice the repeat.js file is from jspm package instead of the project source:
![image](https://user-images.githubusercontent.com/1244471/28925616-ff7265ea-786d-11e7-980f-4b3e86483481.png)

**Expected/desired behavior:**

Repeat object is loaded from src/repeat.js file.

**Additional observations**:
I guess the reason for this is that repeat object from Repeat class imported like this
```import {Repeat} from '../src/repeat';```
is never created. Instead one retrieved like this 
```component = StageComponent.withResources().inView('<div repeat.for="item of items"></div>').boundTo({ items: [] });```
```...```
```repeat = component.viewModel;```
is used and it comes from jspm package.

**Comment by huochunpeng** [comment]
It seems this is left unattended for too long. I just created a duplicated issue, with some unsuccessful attempts to fix.
