### ISSUE TITLE
bug(if-custom-attribute): If custom attribute tries to load html template

### ISSUE THREAD

**Issue by eriklieben** [aurelia/templating-resources#313]
**I'm submitting a bug report**

* **Library Version:**
1.5.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.1.1

* **NPM Version:**
4.0.3

* **JSPM OR Webpack AND Version**
Aurelia-CLI with RequireJS

* **Browser:**
Chrome 61, (but think it exists in all)

* **Language:**
TypeScript 2.0.7

**Current behavior:**
When performing ```au new``` for a fresh project it retrieves ```1.5.0``` which throws an error on performing ```au run --watch``` and opening the default page in Chrome.

```
vendor-bundle.js:4879 Uncaught TypeError: plugin.load is not a function
```

```
vendor-bundle.js:1395 Unhandled rejection Error: Load timeout for modules: template-registry-entry!aurelia-templating-resources/if.html_unnormalized2,template-registry-entry!aurelia-templating-resources/if.html,text!aurelia-templating-resources/if.html_unnormalized3,text!aurelia-templating-resources/if.html
```

```
vendor-bundle.js:1395 Unhandled rejection Error: Load timeout for modules: template-registry-entry!aurelia-templating-resources/if.html_unnormalized2,template-registry-entry!aurelia-templating-resources/if.html,text!aurelia-templating-resources/if.html_unnormalized3,text!aurelia-templating-resources/if.html
````

**Comment by caperavensoftware** [comment]
I am getting a 404 error on the same file. Think the issue is related.
```
Uncaught (in promise) Error: (SystemJS) XHR error (404 Not Found) loading http://127.0.0.1:8080/jspm_packages/npm/aurelia-templating-resources@1.5.0/if.html
```
This is a critical bug for us.

**Comment by StrahilKazlachev** [comment]
#312 duplicate
