### ISSUE TITLE
Allow the possibility to specify the cache type on the `if` attribute

### ISSUE THREAD

**Issue by homer0** [aurelia/templating-resources#320]
**I'm submitting a feature request**

* **Library Version:**
1.5.1

**Current behavior:**
This is a follow up for aurelia/framework#602.

A custom element doesn't get destroyed/re-constructed when used with `if` because the model it's being cached.

**Expected/desired behavior:**

After a lot of discussion, we agreed that the feature would be for the `if` to support the following syntaxis:

```
if="value.bind: someValue; cache: none"
```
That way you can specify if the model should be cached or not.

* **Notes:**
  - This can't be specified on the custom element definition because of the way the cache works: it doesn't check element by element, so in a big tree, it should now check one by one, which would be bad for performance.
  - It can't be done at an application level because if you use third party libraries, it would affect them, changing their implementations of the `if` and possibly causing them to malfunction.

**Comment by homer0** [comment]
@EisenbergEffect ping - Sorry to bother, but it has been a year, any news on this? Thanks.

**Comment by EisenbergEffect** [comment]
Apologies @homer0 The core team hasn't had an opportunity to address this yet and it's unlikely we'll be able to do it for vCurrent. We would be happy to take a PR from you to add this functionality though. Please feel free to submit one and /cc me and @bigopon for review. We'd love to get it in.

**Comment by homer0** [comment]
@EisenbergEffect No worries, I know you guys have been busy. Unfortunately, I don't know Aurelia that well yet, so I wouldn't know where to start in order to add the functionality myself.

The truth is that at the time I opened the issue, I kinda stopped using Aurelia for a while, things like this and the lack of support for SSR were deal breakers for the team. I started using it again like a month ago and I was amazed by how it evolved in just one year :D !!

Finally, kind of related and unrelated at the same time: Last time we discussed this issue, you corrected me when I proposed using a dictionary-like object to send the options for `if` as it wasn't HTML standard and that it should be a key value list separated by semicolon. Well, I was working on a custom attribute for switching classes on an element (exactly like the [`ng-class`](https://docs.angularjs.org/api/ng/directive/ngClass) on AngularJS) and I ended up using a dictionary; I wanted to change it to list format, but I wasn't sure if there was a utility or something on Aurelia that would help me convert that list into an object on the JS class, or if I had to do a couple of `split()`s.

I'm sorry I added that question here, if you believe it should be somewhere else, let me know, I'll move it and delete it from this comment.

Thanks!

**Comment by Sayan751** [comment]
@homer0 I won't say that I have understood the problem statement completely, but there is a [`class.bind`](https://aurelia.io/docs/binding/class-and-style#class) that you can use, instead of creating your own. If your use case is different, please ignore this comment.

**Comment by homer0** [comment]
@Sayan751 Thanks! but I wanted to avoid the ternary; it will look _ugly_ if I have, let's say, 3 _"conditional classes"_.

But my question was more about how to desing the custom attribute value... and after writing "value" I started to realize that changing from `my-attribute.bind="{ myClass: someTruthyValue }"` to `my-attribute="myClass: someTruthyValue; myClass1: someTruthyValue1;"` doesn't make a lot of sense as the syntax is not for the value of the attribute but for the different bindings it supports, so the only "easy" alternative would be to keep the object... but we are back to the syntax not being HTML standard... not sure what to do here.

Once again, sorry for adding unrelated things on the issue.

**Comment by Sayan751** [comment]
@homer0 
This is not a direct answer to your question. I am merely suggesting the already available stuffs in Aurelia that you can use, instead of creating something of your own.

For your specific use case of assigning multiple conditional classes to your element you can use tagged templates. It came out with the June 2018 release: https://aurelia.io/blog/2018/06/24/aurelia-release-notes-june-2018/ (search for "tagged template"). 

To give you an example:

```html
<!--view-->
<div class="${getConditionStyles`${myExpression}`} some-other classes-from ui-framework"></div>
```
```typescript
// view-model
/* For simplicity let's assume that our expression value is of enum type. 
    But, now your in your view-model so you may go crazy and create your custom logic as you want :) */
private getConditionStyles(_parts: string[], myExpressionValue: MyEnum) {
  let classes;
  switch (myExpressionValue) {
      case MyEnum.Val1:
        classes = `awesome-class-1 answer-to-life`;
        break;
      case MyEnum.Val2:
        classes = `awesome-class-2  the-universe`;
        break;
      case MyEnum.Val3:
        classes = `awesome-class-3  and-everything`;
        break;
     default:
        classes = "class-42";
        break;
  }
  return classes;
}
```

Hope this helps :)

**Comment by homer0** [comment]
@Sayan751 thank you so much for the answer, I wasn't aware of that, that's pretty interesting.

Buuuut.... I wouldn't use that for something like a `class`. I believe the view-model shouldn't never handle something like a CSS class, that's a resource it should only be handled by the view, as it's "part of it", IMO.

**Comment by Sayan751** [comment]
Though I have never used it, but custom attribute with dynamic options seems like a good candidate for your use case. https://aurelia.io/docs/templating/custom-attributes#dynamic-options-binding

Basically, in the observer, apply the 'name' as a class of the element if the 'new Value' is true (assuming you have boolean expressions).

**Comment by homer0** [comment]
@Sayan751 Yes! that's exactly what I wanted. Once again, thank you so much :D!

**Comment by Sayan751** [comment]
@homer0  You are welcome; Happy to help :)

**Comment by fracz** [comment]
Any chances for this getting merged in a near future? We are waiting over 2 year for this.

**Comment by bigopon** [comment]
pinging @EisenbergEffect 
It might not be too complex

**Comment by fracz** [comment]
If I understand correctly, it's all about adding `this.view = null` after [unbinding it](https://github.com/aurelia/templating-resources/blob/master/src/if-core.js#L82) if the `cache` has been set to false. Then, the view will be recreated during the next `_show`.

Am I right?

**Comment by bigopon** [comment]
yes, but also make sure it's the same thing in promise case too https://github.com/aurelia/templating-resources/blob/0b1424fd836a1e100225e865ba7730ecf584d814/src/if-core.js#L79
