### ISSUE TITLE
cleanup: replace oneWay with toView, add toView + fromView binding behavior

### ISSUE THREAD

**Issue by jdanyow** [aurelia/templating-resources#321]
We have some binding behaviors that set the binding mode. Now that we have toView and fromView binding modes we should add the corresponding binding behaviors:

https://github.com/aurelia/templating-resources/blob/0cef07a8cac8e99146d8e1c4b734491bb3dc4724/src/binding-mode-behaviors.js

Also need to standardize the internals on `toView` now that it has landed. We still need to support `oneWay` but the internals should use `toView` where possible.

related to https://github.com/aurelia/binding/issues/629 and https://github.com/aurelia/templating-binding/issues/118

**Comment by Alexander-Taran** [comment]
https://github.com/search?l=JavaScript&q=org%3Aaurelia+.one-way&type=Code
not that much to change.. I can get PRs for code and .md
