### ISSUE TITLE
Else CustomAttrbiute not having bindingContext set

### ISSUE THREAD

**Issue by fragsalat** [aurelia/templating-resources#322]
**I'm submitting a bug report**

* **Library Version:**
1.5.1

**Please tell us about your environment:**
* **Operating System:**
Linux (Ubuntu 17.10)

* **Node Version:**
8.4.0

* **NPM Version:**
5.4.2

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
The element having the else attribute has no binding context which leads to missing data when the initial condition is false.
Example:
https://gist.run/?id=371fa4bf53068f0dd4463684b165cb66

**Cause**
The cause for this problem might be that the `If.conditionChanged()` function is called when the if is bound. Since the if attribute appears mostly before the else attribute, the else attribute has no bindingContext yet.
https://github.com/aurelia/templating-resources/blob/master/src/if.js#L23

**Possible solution**
Call the conditionChanged function also when else is bound or just use the binding context of the if attribute.

**Comment by fragsalat** [comment]
Do you need support with this? I mean I can fix this but do you have time to review, merge, test and release the code?

**Comment by jdanyow** [comment]
@fragsalat we'd definitely take a PR for this

**Comment by huochunpeng** [comment]
I got exactly the same issue just now when I try the new `else` binding :-(
Just composed an almost identical gist-run.

Having additional binding inside a branch is a common use case. The else binding is a neat new feature, but it looks like it needs more test coverage before I can trust it in production.

**Comment by fragsalat** [comment]
@huochunpeng I fixed this now and it just has to get merged and released :)

**Comment by jods4** [comment]
This should be fixed in the current release, I think we can close this issue? 
@EisenbergEffect
