### ISSUE TITLE
Leaking (the new) if binding introduced in v1.5.2

### ISSUE THREAD

**Issue by huochunpeng** [aurelia/templating-resources#328]
**I'm submitting a bug report**

* **Library Version:**
1.5.2

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Node Version:**
8.5.0

* **NPM Version:**
5.5.1

* **JSPM OR Webpack AND Version**
CLI

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
https://github.com/huochunpeng/ifff

A leaking if binding behind nested if binding

Run the test app, just click next and next, all conditional DOM are not removed.

Pretty sure this is introduced by #324 which attempt to fix another issue on the new if/else implementation.

This issue doesn't exist on v1.5.1 before #324 fix.

**Expected/desired behavior:**

bring back old if.bind please...
The new if/else doesn't justify the pain...

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by huochunpeng** [comment]
@EisenbergEffect @jdanyow  @jods4 I am getting really really frustrated of this new if/else binding implementation. The new edge cases are really really hard to debug and repeat.

The new if/else implementation changed too much, created lots of new edge cases (just read through your issue list). The result is breaking everybody's production app. I have to say this is not a production ready feature.

Please please revert back to old if binding implementation. And put this new implementation into a beta/preview release for people to try.

I suggest to maintain a conservative Aurelia stable release, and only test experimental features on beta/preview release.

I am back to v1.4.0 again.

**Comment by EisenbergEffect** [comment]
Did you test out the version that was released last night? That fixed a number of issues.

**Comment by huochunpeng** [comment]
I am talking about v1.5.2 you just released.

**Comment by EisenbergEffect** [comment]
I see. Just confirmed that myself. Thanks.

**Comment by huochunpeng** [comment]
This is a new issue introduced by a fix.

**Comment by huochunpeng** [comment]
If you wonder what I mean by "Leading", it's a typo of "Leaking". Sorry about that.

**Comment by huochunpeng** [comment]
Update: confirmed this issue still occurs in latest v1.5.3.

**Comment by jods4** [comment]
@huochunpeng 1.5.3 was a PR for a problem with `else`, not `if`.
Sorry it's been that bad, I have had a good look at it and I think I have a proper fix ready in the PR above.

**Comment by huochunpeng** [comment]
Update: @jods4 your PR fixed this issue.

**Comment by jods4** [comment]
@huochunpeng Thanks for taking the time to try it! It's good to get confirmation before publishing.
