### ISSUE TITLE
signalBindingBehavior.bind has incorrect typings

### ISSUE THREAD

**Issue by tlawandi** [aurelia/templating-resources#338]
**I'm submitting a bug report**

* **Library Version:**
1.5.4

* **Operating System:**
10

* **Node Version:**
v6.11.2

* **Language**
TypeScript Version 2.5.1

**Current behavior:**
The Typings for SignalBindingBehavior.bind only takes 2 parameters.

**Expected/desired behavior:**
* **What is the expected behavior?**
Typing definitions should match the number of parameters the JavaScript code allows.

* **What is the motivation / use case for changing the behavior?**
I am using the signal binder to listen to culture changes on the application.

I am currently doing the following to get around the typing issue
        const behavior: any = this._signalBindingBehavior;
        behavior.bind(binding, source, "aurelia-translation-signal");

**Comment by Alexander-Taran** [comment]
Would you like to provide a pull request for it @tlawandi ?
Seems like a reasonable enhancement.
