### ISSUE TITLE
AMD modules need to be re-generated

### ISSUE THREAD

**Issue by kanvuduc** [aurelia/templating-resources#34]
Currently, the AMD modules are generated incorrectly. They need to be re-generated in order to work well with bower and other JS package manager.

Let's take an example from **if** module:

    exports.If = If = customAttribute('if')(If) || If;
    exports.If = If = templateController(If) || If;

It should be generated as below:

    If = _aureliaTemplating.customAttribute('if')(If) || If;
    If = _aureliaTemplating.templateController(If) || If;
**Note**: I get latest source code then run *gulp build-amd*.

**Comment by EisenbergEffect** [comment]
So, the compiler is generating incorrect code for AMD?

**Comment by kanvuduc** [comment]
No. It did generate incorrect code, I think, because the code in **dist/amd** folder is incorrect. So when developers use bower/jspm to install the package, they will get the wrong code.

If I use the gulp command, it generates the correct code.

**Comment by EisenbergEffect** [comment]
That very strange. I'll investigate and get this fixed soon.

**Comment by EisenbergEffect** [comment]
@kanvuduc Do you know what version of Babel yielded the correct code output? I think there may have been a bug in the version of the compiler that we used to build the release.

**Comment by kanvuduc** [comment]
@EisenbergEffect I just get the latest source code from GitHub then do the build, and I get the correct output :).

**Comment by EisenbergEffect** [comment]
Fixed in next release.
