### ISSUE TITLE
Debounce is not updating input correctly if value has been re-typed

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/templating-resources#341]
@GabrielMancik commented on [Mon Feb 12 2018](https://github.com/aurelia/binding/issues/666)

I'm submitting a bug report

Library Version:
1.6.0

NPM Version:
5.3.0

JSPM Version:
0.16.48

Browser:
Chrome 60.0.3112.113 (Official Build) (64-bit)

Language:
TypeScript 2.3.4

Current behavior:
Steps to reproduce:
Please use your own demo for testing (http://aurelia.io/docs/binding/binding-behaviors)

1. Enter "qwe" as first name
2. Quickly type "qwe" as value again
3. only "qw" remains in input (for a short time input correctly showed "qwe" but then "e" was removed)

I have also tested master branch whether **https://github.com/aurelia/templating-resources/pull/336** this has not fixed the problem, but it seems it did not.

Expected behaviour:
"qwe" typed in input

---

@bigopon commented on [Mon Feb 12 2018](https://github.com/aurelia/binding/issues/666#issuecomment-365090615)

@EisenbergEffect @jdanyow Can you move this to `templating-resources` ?

**Comment by huochunpeng** [comment]
@GabrielMancik I used to see this problem in my app, and I confirm #336 fixed it. I am using the fixed debounce locally.

Can you do a local test again?
To ensure you are running fixed version of debounce, copy the fixed debounce to your local `/src/resources/binding-behaviors/de-bounce.js` (plus rename the class to `export class DeBounceBindingBehavior`).

Then in your html file, try `<input value.bind="value & deBounce">`. If you want easy reproduce, try `deBounce:1000`.

**Comment by huochunpeng** [comment]
@GabrielMancik I can reproduce the exact issue you described with old debounce, but not with fixed debounce.

**Comment by Alexander-Taran** [comment]
can be closed
