### ISSUE TITLE
CircleCI keeps failing probably due to very old npm version

### ISSUE THREAD

**Issue by huochunpeng** [aurelia/templating-resources#342]
**I'm submitting a bug report**
* **Library Version:**
1.5.4
* **Operating System:**
Ubuntu on CircleCI
* **Node Version:**
4.2.6
* **NPM Version:**
2.14.12
* **JSPM OR Webpack AND Version**
NA
* **Browser:**
NA
* **Language:**
all | TypeScript X.X | ESNext

**Current behavior:**
CI test failed probably due to old npm version.

**Expected/desired behavior:**
Understand aurelia supports nodejs 4.x LTS, but you probably need to upgrade npm version in order to pass the test build.

* **What is the expected behavior?**
* **What is the motivation / use case for changing the behavior?**

**Comment by Alexander-Taran** [comment]
[![CircleCI](https://circleci.com/gh/aurelia/templating-resources.svg?style=shield)](https://circleci.com/gh/aurelia/templating-resources)

can be closed
