### ISSUE TITLE
`repeat.for` does not work over `router.navigation` when `<require>` tag is used on the same page

### ISSUE THREAD

**Issue by nenadvicentic** [aurelia/templating-resources#355]
**I'm submitting a bug report**

* **Library Version:**
1.7.1

aurelia-binding@2.1.1
aurelia-templating@1.8.1
aurelia-templating-binding@1.4.3
aurelia-templating-router@1.3.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.11.3

* **Yarn Version:**
1.7.0

* **Browser:**
all

* **Language:**
all

**Current behavior:**
When trying to render navigation using, for example:
```

  <p repeat.for="row of router.navigation">
    ${row.title}
  </p>

```
if HTML template also contains `<require>` tag in the footer, routes do not get rendered on the page.

**Expected/desired behavior:**

Navigation links should be rendered, regardless if HTML template contains `<require>` tag or not.

Reproduction code:
https://github.com/nenadvicentic/aurelia-router-navigation-repeat-broken

**Comment by bigopon** [comment]
Relevant discussion

* https://discourse.aurelia.io/t/using-require-breaks-router/1411/5
* https://github.com/aurelia/templating/issues/632

@nenadvicentic Can you try with the snippet mentioned at https://github.com/aurelia/templating/issues/632#issuecomment-404368423

**Comment by nenadvicentic** [comment]
@bigopon yes, this fixed the issue, when I dropped your code in `main.ts` file. However, I do not think this is Bluebird bug, since earlier versions of Aurelia did not have this issue with same version of Bluebird 3.5.1

**Comment by huochunpeng** [comment]
@nenadvicentic 
Explained here. This failure is the result of 2 bugs, not one.
https://discourse.aurelia.io/t/using-require-breaks-router/1411/23?u=huochunpeng

**Comment by roelplieger** [comment]
@EisenbergEffect we still seem to have this problem even with aurelia-templating 1.8.2, no navigation items visible. As a workaround I am now using an if.bind so the navigation is rendered after router.navigation is filled:

                <a class="bncMainNav__menuItem ${row.isActive ? 'bncMainNav__menuItem--active' : ''}"
                   if.bind="router.navigation.length"
                   repeat.for="row of router.navigation"
                   href.bind="row.href">
                    <span class="bncMainNav__menuItemIcon icon-custom-rss"></span>
                    <span class="bncMainNav__menuItemText">${row.config.name & t}</span>
                </a>

**Comment by huochunpeng** [comment]
@roelplieger be sure to test in Edge (and even IE if you want to support it), the repeat.for and if.bind will be executed in reversed order in Edge.

And for your issue itself, can you show some code to reproduce it in a gistrun?

**Comment by roelplieger** [comment]
@huochunpeng thanks for the tip, tested the workaround in both IE and Edge, it works :-)
I will try to reproduce the problem in a gistrun.

**Comment by huochunpeng** [comment]
@roelplieger sorry to ask, could you test IE and Edge without the workaround? Just to clean up some doubt.

**Comment by roelplieger** [comment]
@huochunpeng tested on IE, Edge, FF and Chrome, there's no menu without the workaround.

**Comment by huochunpeng** [comment]
@roelplieger thx!
Previous bug in 1.8.1 is an edge case when using with bluebird. When bluebird is not in use, the issue goes away.

Not sure about your issue. If your one is still related to bluebird, you wouldn’t be able to reproduce it in gistrun as our gistrun does not bundle blubird.

**Comment by roelplieger** [comment]
@huochunpeng ok, I now know what causes the problem, but it's hard to create a gistrun for it because of the complexity. I am using security, the user must login before menu and content are displayed. In app.html I have this:

    <div class="bncMainContainer"
         if.bind="currentUser.username">
        
        <bnc-menu class="bncMainContainer__menu"
                  router.bind="router"></bnc-menu>

        <div class="bncMainContainer__content jsMainContainer__content">
            <router-view class="bncDiv"></router-view>
        </div>
    </div>
So after logging in currentUser.username is set and the div becomes visible, but the menu is empty. But, if I change it to this:

    <div class="bncMainContainer">
        
        <bnc-menu class="bncMainContainer__menu"
                  if.bind="currentUser.username"
                  router.bind="router"></bnc-menu>

        <div class="bncMainContainer__content jsMainContainer__content"
             if.bind="currentUser.username">
            <router-view class="bncDiv"></router-view>
        </div>
    </div>

the menu shows! Seems something goes wrong in the order of binding and showing things in the DOM?

**Comment by huochunpeng** [comment]
@roelplieger I tried to use your html to reproduce, but could not find a way to reproduce. Wonder how you populate route config.map. Do you populate the routes map statically before login, or do you mutate the routes using `router.addRoute(...)` after login? Can you share the code of your app.js?

**Comment by roelplieger** [comment]
@huochunpeng ok, it's rather big :-)

import { inject, Container } from 'aurelia-framework';
import { Redirect } from 'aurelia-router';
import { FallbackRouteService } from 'components/bnc-menu';
import { NetworkingService } from 'bnc-networking';
import { SecurityService, LogoService } from 'components/usermanager';
import { BncActionService } from 'components/bnc-action-list/bnc-action-service';
import { BncI18n } from 'components/bnc-i18n/bnc-i18n';
import { EventAggregator } from 'aurelia-event-aggregator';
import { ApplicationResellersService } from 'applications/application-resellers-service';
import { ApplicationBus } from './events/application-bus';
import * as CrudEvents from 'components/bnc-crud/crud-events';
import environment from './environment';

@inject(FallbackRouteService, ApplicationBus, NetworkingService, SecurityService, LogoService, BncActionService, BncI18n, ApplicationResellersService, EventAggregator)
export class App {

    fullscreen = false;

    constructor(fallbackRouteService, applicationBus, networkingService, securityService, logoService, bncActionService, i18n, applicationResellersService, eventAggregator) {
        this._fallbackRouteService = fallbackRouteService;
        this._applicationBus = applicationBus;

        if (environment.mock) {
            networkingService.setBaseUrl("/mockusermanager/rest/v1");
        } else {
            networkingService.setBaseUrl("/usermanager/rest/v1");
        }

        this.currentUser = securityService.getCurrentUser();
        this._securityService = securityService;

        logoService.setLogoHeavy("User");
        logoService.setLogoLight("Manager");

        // gebruik de taalinstelling van de huidige gebruiker of die van de browser
        i18n.switchLanguage();

        $(window).on('scroll', function (e) {
            let top = $(window).scrollTop();
            e.scrollTop = top;

            eventAggregator.publish('scroll', e);
        });

        $(window).on('resize', function (e) {
            let width = window.outerWidth;
            let height = window.outerHeight;
            let customEvent = {};

            customEvent.width = width;
            customEvent.height = height;

            eventAggregator.publish('resize', customEvent);
        });

        eventAggregator.subscribe('scroll', event => {
            this.onScroll(event);
        });

        eventAggregator.subscribe('userProfileChanged', currentUser => {
            this.currentUser = currentUser;
        });

        bncActionService.addActions('reseller', {
            tooltip: 'SETTINGS',
            order: 0,
            iconClass: 'icon-custom-settings',
            type: 'extra-settings',
            action: function (event, config) {

                var meta = config.meta;
                let self = this;

                // het volgende is nodig als de view openstaat en deze moet worden hersteld na het sluiten van het settingsscherm   
                meta.oldTarget = meta.target;
                meta.oldBoxUrl = meta.boxUrl;

                eventAggregator.publish(CrudEvents.GO_EDIT, {
                    type: self.type,
                    view: 'reseller-settings/reseller-settings',
                    meta: meta
                });
            }
        });

        bncActionService.addActions('application', {
            tooltip: 'RESELLERS',
            order: 0,
            iconClass: 'icon-custom-settings',
            type: 'application-resellers',
            action: function (event, config) {

                let meta = config.meta;
                let self = this;

                // het volgende is nodig als de view openstaat en deze moet worden hersteld na het sluiten van het settingsscherm
                meta.oldTarget = meta.target;
                meta.oldBoxUrl = meta.boxUrl;

                applicationResellersService.getResellerUsagesForApplication(meta.model.id).then((response) => {
                    meta.model.resellerUsages = response.getData();
                    // send event to request editing of meta
                    eventAggregator.publish(CrudEvents.GO_EDIT, {
                        type: self.type,
                        view: 'applications/application-resellers',
                        meta: meta
                    });
                });

            }
        });


    }

    onScroll(e) {
        let $element = $('.bncInnerHeader');

        this.isFixedHeader = (e.scrollTop >= 30);

        if (this.isFixedHeader) {
            $element.addClass('bncInnerHeader--onScroll');
        } else {
            $element.removeClass('bncInnerHeader--onScroll');
        }
    }

    logout() {
        this._securityService.clearXAuthToken();
        location.reload(true);
    }

    configureRouter(config, router) {
        let routes = [{
            route: ['', 'dashboard'],
            name: 'DASHBOARD', // key voor vertaling
            moduleId: 'dashboard/dashboard',
            nav: true,
            settings: {
                roles: ['ROLE_ADMINS']
            }
        },
        {
            route: ['resellers'],
            name: 'RESELLERS', // key voor vertaling
            moduleId: 'resellers/reseller-list',
            nav: true,
            settings: {
                roles: ['ROLE_ADMINS']
            }
        },
        {
            route: ['applications'],
            name: 'APPLICATIONS', // key voor vertaling
            moduleId: 'applications/application-list',
            nav: true,
            settings: {
                roles: ['ROLE_ADMINS']
            }
        },
        {
            route: ['users'],
            name: 'USERS', // key voor vertaling
            moduleId: 'users/user-list',
            nav: true,
            settings: {
                roles: ['ROLE_ADMINS']
            }
        },
        {
            route: 'user-profile',
            name: 'USER_PROFILE',
            moduleId: 'user-profile/user-profile'
        },
        {
            route: 'login',
            name: 'LOGIN',
            moduleId: 'components/usermanager/security/login'
        },
        {
            route: 'login/forgot',
            name: 'FORGOT_PASSWORD',
            moduleId: 'components/usermanager/security/forgot_password'
        },
        {
            route: 'login/reset',
            name: 'RESET_PASSWORD',
            moduleId: 'components/usermanager/security/new_password'
        }

        ];

        this._fallbackRouteService.setRoutes(routes);
        this.router = router;
        config.title = 'Gebruikersbeheer';
        config.addAuthorizeStep(AuthorizeStep);
        config.fallbackRoute(this._fallbackRouteService.getFallbackRoute());
        config.map(routes);
    }
}

@inject(SecurityService)
export class AuthorizeStep {
    constructor(securityService) {
        this._securityService = securityService;
    }

    run(navigationInstruction, next) {
        let user = this._securityService.getCurrentUser();
        let requiredRoles = navigationInstruction.getAllInstructions().map(i => i.config.settings.roles)[0];

        if (requiredRoles && !user) {
            return next.cancel(new Redirect('login'));
        }

        let isUserPermited = requiredRoles ? requiredRoles.some(roleName => this._securityService.currentUserHasRole(roleName)) : true;

        if (isUserPermited) {
            return next();
        }

        return next.cancel();
    }
}

**Comment by huochunpeng** [comment]
@roelplieger I have no luck on reproducing it. If you can reduce your app into a minimum debug app, that will help.

You can reduce your features one by one, cut off your routes into one or two dummy pages, remove AuthorizeStep (it feels unlikely the cause)... In the end, it probably related to the timing of your userProfileChanged event, but this is only my wild guess.

Not sure if this helps to bypass the issue.

```
eventAggregator.subscribe('userProfileChanged', currentUser => {
   setTimeout(() => this.currentUser = currentUser);
});
```

**Comment by roelplieger** [comment]
@huochunpeng thanks for the tips, I will keep on using the workaround where I have if.bind="currentUser.username" on each div inside the bncMainContainer.
