### ISSUE TITLE
Repeater duplicating rendered items when pushing record(s) into an array

### ISSUE THREAD

**Issue by stefan505** [aurelia/templating-resources#358]
**I'm submitting a bug report**

* **Library Version:**
1.7.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.11.3

* **NPM Version:**
5.8.0

* **JSPM OR Webpack AND Version**
webpack 4.12.0

* **Browser:**
all

* **Language:**
TypeScript 2.9

**Current behavior:**
Performing a `repeat.for` with multi-element layout produces strange duplicate repeated elements rendered for each entry in the array.

**Expected/desired behavior:**
Only one element must be rendered for each entry in the array.

**Steps to reproduce:**
Property declared in ViewModel:

`public records: any[] = [];`

A button click in the ViewModel performs:

```
for (var i = 0; i < 5; i++)
{
    this.records.push({
        value: `value ${i}`
    });
 }
```

In the View:

```
<div repeat.for="r of records">
    <div class="d-flex p-2">
        <div class="mr-1">${r.value}</div>
        <div>####</div>
    </div>
</div>
```

Rendered as:

![image](https://user-images.githubusercontent.com/10812446/42819727-ac159858-89d4-11e8-9d8b-fcc25d2dcc14.png)

I've been noticing the behavior for a while now, but have gotten around it by hacking in a converter that simply returns the data, i.e. `<div repeat.for="r of records | hack">`.

**Comment by bigopon** [comment]
From the look of your workaround, I think the bug you described should already be resolved. Can you do a clean `npm install` (or equivalent) without lock ?

**Comment by stefan505** [comment]
@bigopon I've done that prior to submitting the bug to no avail. 

After digging deeper, I discovered the actual cause. There was an outdated `aurelia-i18n` dep that caused this issue. After upgrading from `2.2.0` to `2.3.1` it works fine. 

What puzzles me is that analysing the package-lock.json prior to the lib upgrade revealed not obvious oddities regarding dependency deduping, etc. Perhaps I missed something somewhere.

Happy to close the bug for now.
