### ISSUE TITLE
Compose with view-model class reference doesn't activate correctly

### ISSUE THREAD

**Issue by zakjan** [aurelia/templating-resources#359]
**I'm submitting a bug report**

* **Library Version:**
1.7.1

**Current behavior:**
When using compose with view-model class reference, it doesn't accept model. Activate method is not run.

Also getters don't work with data inherited from parent context.

Gist: https://gist.run/?id=5c2d55c58bb270bfab2f41026898cd23

**Expected/desired behavior:**
* **What is the expected behavior?**
It should be possible to pass data into compose with view-model class reference and use it in getters.

**Comment by StrahilKazlachev** [comment]
To use class reference in `<compose>` you'll need `>=aurelia-templating@1.8.0`, preferably `>=1.8.2`. The gist you've provided uses an older version.

**Comment by zakjan** [comment]
It's the official gist from the local issue template...

I'm having similar issues in a project with aurelia-templating 1.8.2

**Comment by StrahilKazlachev** [comment]
1. It may be from the issue template *but* it is not using the latest templating.
2. *Do* follow the issue template, it's there for a reason - are you using webpack, requirejs, systemjs, ...?
3. I created a new project with `aurelia-cli`(*requirejs*, babel) and I get all 4 columns with the same values, so it seems to work

When using a `class` for `view-model` and **not** providing the `view` in some way it falls back to using `Origin.get` - which may not play well with webpack. You can use the `view` bindable property, add a *static* `$view` property on the VM `class`, ...

**Comment by zakjan** [comment]
Sorry for thinking that the official gist is updated to the latest version. That's why I thought Webpack is irrelevant, same as OS is usually irrelevant. I'm closing this.

**Comment by StrahilKazlachev** [comment]
Did you resolve the issue?

**Comment by zakjan** [comment]
Yes, even after I updated aurelia-templating from 1.8.1 to 1.8.2, I forgot to update vendor webpack dll bundle. The old version was stuck there, causing #360.
