### ISSUE TITLE
Compose with class reference reuses the same class instance in repeat.for

### ISSUE THREAD

**Issue by zakjan** [aurelia/templating-resources#360]
**I'm submitting a bug report**

* **Library Version:**
1.7.1

**Please tell us about your environment:**
* **JSPM OR Webpack AND Version**
Webpack 4.16.2

**Current behavior:**
compose with class reference reuses the same class instance in repeat.for, leading to the last element from repeat.for being displayed everywhere

Demo: https://stackblitz.com/edit/aurelia-compose-activate-2

Note the console.warn messages.

**Expected/desired behavior:**
separate instances of the class for each repeat.for run

**Comment by zakjan** [comment]
on hold, still some issues with replicating

**Comment by huochunpeng** [comment]
If you only have issue in your app, but not in demo, have a look of aurelia/binding#702, there is a solution for fixing duplicated aurelia-binding which causes many weird bugs. It might be related.
