### ISSUE TITLE
Error in typings

### ISSUE THREAD

**Issue by jods4** [aurelia/templating-resources#362]
**I'm submitting a bug report**

**Library Version:** 1.7.0, related: `aurelia-binding@2.0.0`

**Current behavior:**
After I import something from this module directly, for example:
`import { BindingSignaler } from 'aurelia-templating-resources';`
Its definition file seems to be brought into the Typescript (3.0.3) compilation and creates errors:
```
ERROR in G:/proj/***/node_modules/aurelia-templating-resources/dist/aurelia-templating-resources.d.ts(28,3):
TS2305: Module ''aurelia-binding'' has no exported member 'EventSubscriber'.
ERROR in G:/proj/***/node_modules/aurelia-templating-resources/dist/aurelia-templating-resources.d.ts(33,3):
TS2305: Module ''aurelia-binding'' has no exported member 'targetContext'.
ERROR in G:/proj/***/node_modules/aurelia-templating-resources/dist/aurelia-templating-resources.d.ts(34,3):
TS2305: Module ''aurelia-binding'' has no exported member 'DataAttributeObserver'.
```

**Expected/desired behavior:**
No errors in TS type declarations.

**Comment by bigopon** [comment]
Resolved by #361
