### ISSUE TITLE
Is this a typo? 

### ISSUE THREAD

**Issue by netcorefactory** [aurelia/templating-resources#377]
https://github.com/aurelia/templating-resources/blob/38e4283f59a4d02f26722122615b722b267b82a2/dist/aurelia-templating-resources.d.ts#L595

Is this a typo? import is already done on top?
Our builds are broken by this issue. How to keep .d.ts files backwards compatible?

**Comment by bigopon** [comment]
@netcorefactory Sorry for this. It's fixed here https://github.com/aurelia/templating-resources/pull/376 and is waiting for a release by @EisenbergEffect

**Comment by EisenbergEffect** [comment]
Release coming soon.

**Comment by netcorefactory** [comment]
Cool but also my bad. We still use typings install in old project...
