### ISSUE TITLE
matcher.bind does not work inside of repeat

### ISSUE THREAD

**Issue by Ischca** [aurelia/templating-resources#378]
**I'm submitting a bug report**

* **Library Version:**
1.10.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
10..0

* **NPM Version:**
6.1.0

* **JSPM OR Webpack AND Version**
webpack 4.31.0

* **Browser:**
Chrome

* **Language:**
TypeScript

**Current behavior:**
matcher.bind does not work inside of repeat.
It works with no problem in 1.9.1.

**Expected/desired behavior:**

DEMO: https://codesandbox.io/s/objects-uc90f?fontsize=14&module=%2Fsrc%2Fapp.ts
Forked from the demo at https://aurelia.io/docs/binding/radios.
* **What is the expected behavior?**
The matcher works inside of repeat.

**Comment by bigopon** [comment]
@Ischca thanks for filing this issue
