### ISSUE TITLE
dynamic-behavior custom attribute

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/templating-resources#38]
Some 3rd party libraries, such as kendo, generate HTML on the fly based on an internal templating system. Users would like to be able to use these template to include Aurelia custom elements and attributes. However, today this doesn't work because the templating engine has already processed the static content. Create a custom attribute that can be placed on a view to tell Aurelia to watch the view (using a mutation observer) and dynamically activate any html elements, attributes or binding expressions that appear.

**Comment by capaj** [comment]
@EisenbergEffect  in the meantime, how can I trigger compilation on a DOM element manually? I have a DOM being inserted by leaflet.js map library and I would love to compile an aurelia element inside it by hand.

**Comment by EisenbergEffect** [comment]
See if this will work for you: https://github.com/gooy/aurelia-compiler

**Comment by capaj** [comment]
Tried, it did not. There was a typo and even after fixing that typo it didn't compile my DOM element.

**Comment by EisenbergEffect** [comment]
We now have an imperative api for this via `enhance`. It's not clear what the best way would be to make a declarative api...and might not be able to be done in a really useful or generic way. Since the core capability to accomplish this now exists in the templating engine, I'm closing this issue.
