### ISSUE TITLE
Capture and remove matcher binding breaks IE 11

### ISSUE THREAD

**Issue by AquilaSands** [aurelia/templating-resources#390]
**I'm submitting a bug report**

* **Library Version:**
1.12.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
12.3.1

* **NPM Version:**
6.9.0

* **JSPM OR Webpack AND Version**
Aurelia CLI 1.2.2 with requireJS

* **Browser:**
IE 11

* **Language:**
ESNext

**Current behavior:**
Commit a5796443016d2c87269dd05801c057fb45e5dc44 introduced a breaking change for IE 11 
lines https://github.com/aurelia/templating-resources/blob/d346a817157960d54098a9193fc58c264ceedca6/src/repeat.ts#L289
and https://github.com/aurelia/templating-resources/blob/d346a817157960d54098a9193fc58c264ceedca6/src/repeat.ts#L295
require polyfills for documentFragment.children and documentFragment.firstElementChild respectively.

Without them in my case this caused console errors and the app failed to load.
**Expected/desired behavior:**

* **What is the expected behavior?**
App runs in IE 11

* **What is the motivation / use case for changing the behavior?**
Maintain IE 11 compatibility

* **Additional Info**
For my app I added the polyfills from MDN:
https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/children
```
// Overwrites native 'children' prototype.
// Adds Document & DocumentFragment support for IE9 & Safari.
// Returns array instead of HTMLCollection.
;(function(constructor) {
  if (constructor &&
    constructor.prototype &&
    constructor.prototype.children == null) {
    Object.defineProperty(constructor.prototype, 'children', {
      get: function() {
        var i = 0, node, nodes = this.childNodes, children = [];
        while (node = nodes[i++]) {
          if (node.nodeType === 1) {
            children.push(node);
          }
        }
        return children;
      }
    });
  }
})(window.Node || window.Element);
```
https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/firstElementChild
```
// Overwrites native 'firstElementChild' prototype.
// Adds Document & DocumentFragment support for IE9 & Safari.
;(function(constructor) {
    if (constructor &&
        constructor.prototype &&
        constructor.prototype.firstElementChild == null) {
        Object.defineProperty(constructor.prototype, 'firstElementChild', {
            get: function() {
                var node, nodes = this.childNodes, i = 0;
                while (node = nodes[i++]) {
                    if (node.nodeType === 1) {
                        return node;
                    }
                }
                return null;
            }
        });
    }
})(window.Node || window.Element);
```

**Comment by bigopon** [comment]
Oops, i checked for IE11 compat without checking for document fragment. My bad. Sorry for this @AquilaSands it would be great if you could send a PR to fix this. Though im not sure what we qould do for this. Polyfill or simple utility fn?
Cc @EisenbergEffect @fkleuver
