### ISSUE TITLE
Memory leak when a slot contains a repeated element

### ISSUE THREAD

**Issue by thomas-darling** [aurelia/templating-resources#392]
**I'm submitting a bug report**

* **Library Version:**
aurelia-framework 1.3.1

* **Browser:**
Chrome 78, and probably all others

**Current behavior:**
When the slot of a custom element contains a repeated element, and the collection being repeated is cleared, the repeated elements are retained in memory as detached elements.

Essentially, doing this causes a memory leak:
```html
<custom-element>
    <div repeat.for="item of items"></div>
</custom-element>
```

Reproduction code and steps:
https://codesandbox.io/s/aurelia-typescript-sandbox-wxsco

**Expected/desired behavior:**

* **What is the expected behavior?**
No detached elements should be retained in memory after the collection is cleared or changed.

* **What is the motivation / use case for changing the behavior?**
This is a _huge_ memory leak, and a pretty crippling bug - in our case, we end up with hundreds of thousands of detached DOM nodes after a brief period of use, which eventually crashes the browser.

  Being unable to use repeat directly within a slot is _highly_ impractical, as we may, for styling purposes, need the repeated elements to be the direct children of the slot - and it's a bug that's so easy to run into, that it's basically impossible to avoid.

  Many developers won't realize what is happening here, or know how to properly debug this, so it really needs to be fixed. I'm guessing there are _lots_ of production apps suffering from this issue, and when users complain of slow and crashing apps, it becomes _really_ hard to make the case for using Aurelia for the next project. Therefore, this really need to be fixed before Aurelia 2...

**Comment by thomas-darling** [comment]
Ok, so I did some debugging, and those are my findings:

Here's the memory dump from our app.
It looks like `ShadowSlot` is retaining the references to detached elements.

![image](https://user-images.githubusercontent.com/6388663/72660191-319f6a80-3a05-11ea-8f88-70125acb450e.png)

Looking at `ShadowSlot` in https://github.com/aurelia/templating/blob/master/src/shadow-dom.js, and searching for `this.children`, it appears that nodes are added to the `children` array in the `addNode` method - _but there is no code anywhere that removes nodes from that array_.

That feels like it might be the bug - however, I'm not sure exactly how this is supposed to work 🤔 

I'm thinking, that since the `addNode` method is called from `ShadowDOM.distributeNodes`, which is called from `ShadowDOM.distributeView`, maybe a `removeNode` method should somehow be called from `ShadowDOM.undistributeView` and `ShadowDOM.undistributeAll`?

@EisenbergEffect, @bigopon Do you have any insights here?

**Comment by thomas-darling** [comment]
Based on initial testing, adding the following two lines **_appears_** to fix the issue.
However, I don't understand this code well enough to say whether this is a correct fix, or whether it breaks things elsewhere. I could really use some insight from the team here 🙂 

![image](https://user-images.githubusercontent.com/6388663/72661742-032b8a80-3a19-11ea-8d5a-41b80888d18f.png)

**Comment by bigopon** [comment]
@thomas-darling thanks for this issue and the effort put into resolving it. I think your analysis is correct. I'll be creating a PR based on your suggested changes, if you don't mind.

**Comment by thomas-darling** [comment]
Sounds good, thanks! 👍
