### ISSUE TITLE
iterating over an object's keys is unclear

### ISSUE THREAD

**Issue by mbroadst** [aurelia/templating-resources#41]
This does not work: 
```javascript
export class Class {
  data = {
    "first": {
      something: true
    },
    "second": {
      something: false
    }
  };

};

<div repeat.for="d of data">
  ${d.something}
</div>
```

while this does work:
```javascript
export class Class {
  data = {
    "first": {
      something: true
    },
    "second": {
      something: false
    }
  };
};

export class KeysValueConverter {
  toView(value){
    return Object.keys(value);
  }
}

<div repeat.for="d of data | keys">
    ${$parent.data[d].something}
</div>
```

It would be desirable to provide one of two alternative methods, as the solution provided is rather clunky:

   * ```<div repeat.for="(key, value) in data}>${key} = ${value}</div>```
   * ```<div repeat.for="d in data">${$key} = ${$value}</div>```

**Comment by martingust** [comment]
For the record from the Gitter conversation:

We could add the “in” syntax and just have it dynamically add a | keys converter on to the end of the expression….and then we could provide a keys converter out of the box. It will be a bit more complicated than that syntax-wise once we add binding behaviors, but we could do something like that I suppose.

**Comment by jdanyow** [comment]
Cool feature- what is the expected behavior when the object's properties are changed/deleted/added?

**Comment by mbroadst** [comment]
@jdanyow this was discussed in the gitter too, I think its expected that this a one-way bound operation. I'm familiar with the internals of your template binding, but I imagine two-way binding this would be non-trivial

**Comment by heruan** [comment]
:+1: I'm writing a plugin to build tables and forms reading a JSON schema and repeating over an object would be very useful to iterate over the `properties` objects of the schema.

**Comment by MarkHerhold** [comment]
This issue was opened a while ago, but still has a high Google rank.

Aurelia supports binding to ES6 Map objects, which likely accomplishes what most people want.
https://github.com/aurelia/framework/issues/90

**Comment by martingust** [comment]
The repeater is now pluggable, that means you can plug in different strategies to teach the repeater how to iterate different collections. In this case you could make the object iterable and the plug in an iterator strategy to the repeater.

Here is a full example:

```html
<template>
  <div repeat.for="[key, value] of data | iterable">
    ${key} ${value.something}
  </div>
</template>
```

```javascript
export class App {
  static inject = [RepeatStrategyLocator];

  data = {
    "first": {
      something: true
    },
    "second": {
      something: false
    }
  };

  constructor(repeatStrategyLocator) {
    repeatStrategyLocator.addStrategy(items => typeof items[Symbol.iterator] === 'function', new IteratorStrategy());
  }
}

export class IterableValueConverter {
  toView(value) {
    let index = 0;
    let propKeys = Reflect.ownKeys(value);
    return {
        [Symbol.iterator]() {
            return this;
        },
        next() {
            if (index < propKeys.length) {
                let key = propKeys[index];
                index++;
                return { value: [key, value[key]] };
            } else {
                return { done: true };
            }
        }
    };
  }
}

class IteratorStrategy {
  instanceChanged(repeat: Repeat, items: any): void {
    let index = 0;
    for(let [key, value] of items) {
      let overrideContext = createFullOverrideContext(repeat, value, index, undefined, key);
      let view = repeat.viewFactory.create();
      view.bind(overrideContext.bindingContext, overrideContext);
      repeat.viewSlot.add(view);
      ++index;
    }
  }
  instanceMutated(repeat: Repeat, items: any, changes: any): void {
  }
  getCollectionObserver(observerLocator: any, items: any): any {
  }
}
```

**Comment by jdanyow** [comment]
@martingust that is awesome ^^^

**Comment by EisenbergEffect** [comment]
I think we need that example for our advanced templating docs. Very cool
stuff...

**Comment by martingust** [comment]
I created a plugin for this https://github.com/martingust/aurelia-repeat-strategies

@EisenbergEffect Sure, I'll include that.

**Comment by alvarezmario** [comment]
@martingust @EisenbergEffect I wonder if is not a good idea to include this in the core. Is not much code and is something that many people needs. I mean, adding the plugin is also good, but I think that iterating an object is important enough as for adding this as a core feature.

**Comment by eliavmaman** [comment]
Hey guys, 
I was trying solve this problem with @martingust  plugin but got error from jspm.
**Thats how i solved the problem:**
 I've changed the itarableValueConvertor like that:
`export class IterableValueConverter {
    toView(value) {
        if (value) {
            let index = 0;
            let propKeys = Reflect.ownKeys(value);
            let newArr=[];
            
            for(var i=0; i<propKeys.length;i++){
                newArr.push({value: [propKeys[i], value[propKeys[i]]]});
            }
            
            return newArr;
            
        }
    }
}`

and the view is like:
`<div class="col-xs-3" repeat.for="val of tableInfo | iterable">
                                <div class="col w-150">
                                    <strong>${val.value[0]}</strong>
                                </div>
                                <div class="col w-150">
                                    <span>${val.value[1]}</span>
                                </div>
                            </div>
`

**Comment by eliavmaman** [comment]
@martingust , i was trying to use the itarableValueConvertor class you created without the plugin,
It fails on thr next() function, for that input: `['a','b','c']`.

**Comment by EisenbergEffect** [comment]
@martingust What is the status of this? Can we close this issue?

**Comment by martingust** [comment]
@EisenbergEffect Yes, I think best solutions is to plugin a strategy for this or use [this](https://github.com/martingust/aurelia-repeat-strategies) plugin. I'll add to my list to add this to the docs.

**Comment by khenderick** [comment]
Is something recently changed that breaks the mentioned plugin? As reported in martingust/aurelia-repeat-strategies#5, the plugin can't resolve module ```aurelia-templating-resources/repeat-utilities```

**Comment by eliavmaman** [comment]
@martingust hey just checking your solution.. and found out the `Reflect` is not supported on IE..
Any other solution mayb?

**Comment by EisenbergEffect** [comment]
We have polyfills for reflect in our polyfills library.

**Comment by Lux589** [comment]
I'm using npm to manage packages. how can I make this work without using jspm
