### ISSUE TITLE
Use a binding for compose view-model

### ISSUE THREAD

**Issue by tomasbonco** [aurelia/templating-resources#42]
Hello,
I'm getting this:
```
Potentially unhandled rejection [1] TypeError: Cannot read property 'moduleId' of undefined
    at HtmlBehaviorResource.load (http://localhost:9000/jspm_packages/github/aurelia/templating@0.10.3/html-behavior.js:134:59)
```

Here is Git: https://github.com/tomasbonco/aurelia-issue
Tested in aurelia 0.12.0 and 0.12.2.

Source code for quick code review:
`app.jade`
```
template

	compose( view-model.bind="components.dialog" view="./components/dialog/dialog" )
```

`app.js`
```
import {inject} from 'aurelia-framework'
import {Dialog} from 'components/dialog/dialog'

@inject( Dialog )
export class App
{
	constructor( dialog )
	{
		this.components = {}
		this.components.dialog = dialog
	}
}
```

Thanks for help!

**Comment by jdanyow** [comment]
If you set a breakpoint in the transpiled code is `Dialog` defined on the line that looks like this:

```javascript
  return {
    setters: [function (_aureliaFramework) {
      inject = _aureliaFramework.inject;
    }, function(_dialog) {
      Dialog = _dialog.Dialog;  // <--- here (it may not look exactly like this)
    }],
```

**Comment by tomasbonco** [comment]
I'm sorry, is that a question? Where exactly should I see it (and why)?
`dialog.js` is compiled into:
```
System.register([], function (_export) {
	var _classCallCheck, Dialog;

	return {
		setters: [],
		execute: function () {
			'use strict';

			_classCallCheck = function (instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError('Cannot call a class as a function'); } };

			Dialog = function Dialog() {
				_classCallCheck(this, Dialog);

				console.log('If I get penny for every time Im called ...');
			};

			_export('Dialog', Dialog);
		}
	};
});
```

And property `target` in `viewStrategy.moduleId = Origin.get(target).moduleId;` is:
```
function Dialog() {
	_classCallCheck(this, Dialog);

	console.log('If I get penny for every time Im called ...');
}
```

**Comment by jdanyow** [comment]
apologies- I wasn't very clear- what I meant was if you use the chrome debugging tools and set a breakpoint in app.js, is `Dialog` undefined?  I'm referring to `Dialog`, the constructor function/class- not `dialog` the variable/argument in your App constructor.

**Comment by tomasbonco** [comment]
No it's not:

![github-aurelia-bug](https://cloud.githubusercontent.com/assets/4013047/7337868/9eeef5ca-ec39-11e4-970e-a3889732dc0a.png)

**Comment by tomasbonco** [comment]
When examining originStorage, there is no Dialog. Do I have to do it manually?

**Comment by tomasbonco** [comment]
I updated repo, with html (so jade is no longer needed)

**Comment by CharlesPockert** [comment]
Looks like two issues here:

1. The module has not been `<require>`d. This results in what I assume to be the module cache trying to grab the module and assuming it's already been loaded. 

2. If the require is added I get another error: (getObserversLookup on undefined)

I've debugged this, I get down to the dynamic-element branch in composition-engine.js. This:

```
    metadata = new HtmlBehaviorResource();
    metadata.elementName = 'dynamic-element';
    doneLoading = metadata.load(childContainer, viewModel.constructor, instruction.view, true);
```

Sets up the metadata and then this:
```
 return doneLoading.then(function (viewFactory) {
                return metadata.create(childContainer, {
```
Tries to create behaviour.

The only place I can see the observerLocator property being added to the metadata is during `analyze` where it's grabbed from the DI container:

```
analyze(container, target){
    var proto = target.prototype,
        properties = this.properties,
        attributeName = this.attributeName,
        i, ii, current;

    // Here:
    this.observerLocator = container.get(ObserverLocator);
```

So without being pushed through the analyze pipeline the locator is never set

Without being a JS guru or knowing much about the framework (yet!) it looks like analyze sets up the metadata by looking at the view/viewmodel and inspecting what options are set, in which case the below causes that to happen on dynamic elements

```
    metadata = new HtmlBehaviorResource();
    metadata.elementName = 'dynamic-element';
  
    if(viewModel)
        metadata.analyze(childContainer, viewModel.constructor);
  
    doneLoading = metadata.load(childContainer, viewModel.constructor, instruction.view, true);
```

Which results in it all working properly
