### ISSUE TITLE
[Bug] compose ActivationStrategy.Replace not replacing the VM

### ISSUE THREAD

**Issue by avrahamcool** [aurelia/templating-resources#428]
**Library Version:**
1.14.3

as we can see from this PR https://github.com/aurelia/templating-resources/pull/382
we have the ability to control the activation strategy of the `<compose />`  element in two ways.
* by passing a bindable property
* by implementing `determineActivationStrategy` hook on the VM.

**Current behavior:**
* using `replace` as the activation strategy doesn't actualy replace the current VM.

here is a simple example (thanks @yosefbuskila) demonstrating how the same VM is being reused.
https://github.com/yosefbuskila/test-compose
it's enough to notice that the constructor is called only once.
and that the lifecycle hooks of the same instance of the VM are called in the wrong order.

**Expected/desired behavior:**
* when using `ActivationStrategy.Replace` - the `<compose />` element should create a new VM when changes occures in the passed `model`. and should onvoke all the desired lifecycles on both the leaving VM and the new VM.

I'll be working in the near future on a PR for this.

**Comment by bigopon** [comment]
Released in 1.5.1. Thanks @avrahamcool

**Comment by avrahamcool** [comment]
@bigopon thanks.
you meant in 1.15.1

**Comment by bigopon** [comment]
Yes 1.15.1
