### ISSUE TITLE
Bug into amd module sanitize-html

### ISSUE THREAD

**Issue by luboid** [aurelia/templating-resources#43]
Hi,

valueConverter is undefined

**Comment by jdanyow** [comment]
@luboid could you provide some more info on this issue?  I tried reproducing it in the Aurelia plunkr:

http://plnkr.co/edit/Atjl971xjH3ozJdy8LAX?p=preview

**Comment by luboid** [comment]
Hi,

Here is example:

https://github.com/luboid/aurelia-bundle

I used to bundle Aurelia with 

https://github.com/luboid/aurelia-typescript/tree/master/aurelia-require-bundle

such thing occur to me with compose module, row :

exports.Compose = Compose = customElement('compose')(Compose) || Compose;

symbol customElement

**Comment by luboid** [comment]
Is that enough for you?

**Comment by EisenbergEffect** [comment]
Fixed in next release.
