### ISSUE TITLE
repeat.for="i of 5" does not work

### ISSUE THREAD

**Issue by Aaike** [aurelia/templating-resources#50]
`<div repeat.for="i of 5">${i}</div>`
does not work to repeat something x number of times.

I think this syntax should work as `for(i of 5)` works fine in ES6.

**Comment by EisenbergEffect** [comment]
@Aaike You just have to go and make things complicated :smile: Right now we support arrays and maps. We don't actually support generic iterables because it's hard to know how to observe that. We could special case this though. The question would be, what is the cost of this. @martingust Can you look into this. Obviously, no observation needs to be done here. Not sure off the top of my head what would be the easiest way to make this happen.

**Comment by martingust** [comment]
@Aaike @EisenbergEffect I like it! It would be fairly easy and not much cost in implementing. I will see if I can get this in tonight.

**Comment by Aaike** [comment]
Thx for adding that so quickly @martingust !

**Comment by davismj** [comment]
@Aaike I actually had a use case for this as well and wrote my own, python style:
```javascript

range(n) {
	var arr = [];
	while (n > 0) {
		arr.unshift(--n);
	}
	return arr;
}
```
so 
`repeat.for="i of range(5)"`

@martingust Thanks so much, dude, this is awesome!

**Comment by Aaike** [comment]
Did this update also allow for variables to be used ?
```
<div repeat.for="i of total">${i}-${total}</div>
```
where `total` would be a variable on the VM with a number ?
i gave it a quick go but it didn't seem to work.

**Comment by davismj** [comment]
It did.

**Comment by Aaike** [comment]
it does work ! thx @davismj 
```
<div repeat.for="i of total">${i}-${$parent.total}</div>
```

**Comment by Aaike** [comment]
it does work ! thx @davismj 
```
<div repeat.for="i of total">${i}-${$parent.total}</div>
```

**Comment by tkiethanom** [comment]
Using "x of count" is still sort of broken. The DOM elements aren't actually bound to the count variable when used this way, so if count was originally 2 but you incremented the count to 3 on the back end you will end up with 5 repeated elements. Instead of the expected 3.

**Comment by jdanyow** [comment]
@tkiethanom https://github.com/aurelia/templating-resources/issues/81

**Comment by tednyberg** [comment]
This was excellent when having to iterate over a **FileList** collection, since it's not iterable in itself:

```
<li repeat.for="i of files.length">
   ${files.item(i).name}
</li>
```
