### ISSUE TITLE
create custom attribute to put focus on a field once a model view is loaded

### ISSUE THREAD

**Issue by rharing** [aurelia/templating-resources#53]
If a view is loaded it would be nice to indicate a field to be directly focussed. Using normal javascript this could be done by selecting the element and then calling the focus method on it. Hopefully Aurelia can create an attribute for this.

**Comment by martingust** [comment]
@rharing You can bind to the `autofocus` attribute:

```
<input type="text" autofocus.bind="hasFocus" />
```

**Comment by rharing** [comment]
yes that would indeed be what I was looking for, thanks for the info
