### ISSUE TITLE
Crash using `repeat`

### ISSUE THREAD

**Issue by stoffeastrom** [aurelia/templating-resources#54]
After latest upgrade my plugin started to crash in `view-slot` coming from `repeat` `handleSplices`. It tries to do `view.insertNodesBefore` but the view is a `promise`:).
Goto http://oribella.github.io/aurelia-sortable/#/flickr. Start dragging an image and turn on break on expections and you will see the problem.

**Comment by EisenbergEffect** [comment]
@martingust I know you are messing around in there already. Would you mind taking a look at this please?

**Comment by martingust** [comment]
@stoffeastrom When dragging an image I get `Cannot read property 'classList' of null` from `animator.css` is that what you get as well?

**Comment by stoffeastrom** [comment]
@martingust No I don't get that. Are you running it locally?

**Comment by martingust** [comment]
@stoffeastrom Ok, in Firefox I can see this and in Chrome the above. Will look into it.

**Comment by martingust** [comment]
This is due the `removeAt()` function in `view-slot` now returns a Promise instead of the actual view when the view is animated. Working to find a solution to this, hang in there.
