### ISSUE TITLE
TypeError when repeat is shown for first time using if.bind

### ISSUE THREAD

**Issue by CharlesPockert** [aurelia/templating-resources#56]
I've managed to reproduce this in skeleton, which can be seen here:

https://github.com/CharlesPockert/skeleton-navigation/tree/master/src

Basically, I've created a custom element which is a collapsible panel and I was messing about with showing/hiding it using `if.bind`. I found that If I nest a `repeat.for` inside an element and use an `if.bind` attribute on it, when the bound property is truthy and it previously was not, the element throws a TypeError:

`Uncaught TypeError: Cannot read property '__observers__' of undefined`

In the demo app I've simply provided an array of ints to repeat over and a button to toggle the bound property (`showItems`). Click the button to see the error.

This appears to work fine if I use show.bind (I assume the elements are already in the DOM with `show`).

It breaks if I use `if.bind` on any parent element.

**Comment by martingust** [comment]
Yes, problem seems to be using `if.bind` inside of a `CustomElement`, when `if` sets to true it creates a new view with `executionContext` null and bindings inside `if` gets no scope. In `behavior-instance` the instructions for the bindings inside the `if.bind` are missing. Possible soulution is to update these during `bind`. Honestly I'm not sure how this can be implemented and would need someone else to take a look at this or give me hint in right direction and I'll happily get the fix in.

**Comment by Mordred** [comment]
Is there any progress with this?

**Comment by EisenbergEffect** [comment]
Not  yet. There are a few other templating issues that need to be addressed first.
