### ISSUE TITLE
feature request: convenience binding for composition without view-model

### ISSUE THREAD

**Issue by mbroadst** [aurelia/templating-resources#58]
It would be very convenient in some cases to be able to make the binding context of a composed view using this syntax:
    ```<compose view="/path/to/template.html" model.bind="anObject"></compose>```

Not only would this save boilerplate in very simple cases, but it would also allow an easy mental modeling for the composed view such that you could use properties of the bound model directly in the template.

For example:
**app.js:**
```
constructor() {
   this.items = [{name:"first"}, {name:"second"};
}
```

**app.html:**
```
<div repeat.for="item of items">
    <compose view="my-template.html" model.bind="item"></compose>
</div>
```

**my-template.html:**
```
<template>
    ${name}
</template>
```

relevant example: http://plnkr.co/edit/2qX6YJxxKORTXgP2VV8L

**Comment by mbroadst** [comment]
it's worth noting that this feature might be reimagined as replacing ```model.bind="item"``` above with ```view-model="item"```, but that might violate expectations (and generally be somewhat confusing to users)

**Comment by EisenbergEffect** [comment]
Use `view-model.bind="item"` :)
