### ISSUE TITLE
repeated items cannot be styled with last-child

### ISSUE THREAD

**Issue by Aaike** [aurelia/templating-resources#63]
When using a repeat it always leaves a <template> tag after the repeated elements. it's been like that for a while. 

Here is a screenshot from the repeat on the flickr page in the skeleton nav that shows the template tag:
![screenshot from 2015-05-25 00 21 08](https://cloud.githubusercontent.com/assets/378772/7788924/58bb6084-0278-11e5-8acc-e25bee7bb8c2.png)

Just wondering if there are plants to fix/change this ?
it prevents the `last-child` selector from being used in the css.

if i have something like this:
```
<ul class="myList">
   <li class="item" repeat.for="item of items"></li>
</ul>
```

i would like to be able to style it with:
```
.myList .item:last-child{...}
```

**Comment by joelkinzel** [comment]
I'll piggy-back since it is related, but when using the "compose" feature, it leaves the compose element in the HTML as well. Example below:

```
<form-toolbox class="au-target"><!--<view>-->
    <!--<view>--><div>
        <h3>textbox</h3>
        <compose view="widgets/${item.type}" class="au-target"><!--<view>-->
    <input type="text">
<!--</view>--></compose>
    </div><!--</view>--><!--<view>--><div>
        <h3>button</h3>
        <compose view="widgets/${item.type}" class="au-target"><!--<view>-->
    <button type="button" class="btn success">Test Button</button>
<!--</view>--></compose>
    </div><!--</view>--><!--<view>--><div>
        <h3>select</h3>
        <compose view="widgets/${item.type}" class="au-target"><!--<view>-->
    <select>
        <option>Select Test</option>
    </select>
<!--</view>--></compose>
    </div><!--</view>--><template class="au-target"></template>
<!--</view>--></form-toolbox>
```

While you can work around it, it would be nice if Aurelia would just inject the view from the HTML file (minus the `<template>` tag).

**Comment by bastienJS** [comment]
I can just second that behavior: use a bootstrap button-group with 3 buttons. The last button has no rounded corners.

You can fix that with a workaround:

```
#button-group .btn:nth-last-child(2){
  border-top-right-radius:5px;
  border-bottom-right-radius:5px;
}
```

Instead of :last-child use the nth-last-child(2) which formats the element before the last element :P

**Comment by EisenbergEffect** [comment]
This is two different issues here. The first is how we handle maintaining anchors for view injection. We've been using a template element, but obviously that affects the last-child scenario. I think we could switch to using a comment anchor. I'm going to investigate this tomorrow.

The second scenario relates to "containerless" composition. In other words, rendering the custom element without it's container. I have an issue and think we can address that as well. I'll probably deal with that after the above templating anchor issue.
