### ISSUE TITLE
compose 'done' event

### ISSUE THREAD

**Issue by Aaike** [aurelia/templating-resources#64]
I'm currently in a situation where i would need to know when the compose element is done with processing the instruction.

I would like to be able to do something like:
```
<compose done.delegate="composeDone()"></compose>
```

The `composeDone` function would get called when everything is loaded and the element is displayed.
It would allow me to show a loading indicator while some compose elements on the page are still loading.

I am seeing a not insignificant FOUC when paginating through a repeat that has a `<compose>` within it.
So i would like to hide the repeat or show a loading until the compose is finished with it.

The fix would be quite easy , it would just be dispatching an event in this function : 
https://github.com/aurelia/templating-resources/blob/master/src/compose.js#L131

So it would be :
```
function processInstruction(composer, instruction){
  composer.currentInstruction = null;
  composer.compositionEngine.compose(instruction).then(next => {
    composer.currentBehavior = next;
    composer.currentViewModel = next ? next.executionContext : null;
    composer.element.dispatchEvent(new Event("done"));
  });
}
```

I've tested it, it works great, and I would love to submit a PR for it.
just wanted to get an opinion on the naming of the event.
I've named it `done` now, any suggestions for a different name ? or is `done` ok ?

**Comment by Aaike** [comment]
Actually what would also be good is to have a start event so i can detect when a compose is going to start loading and show a loader until it is done, and it would be good to know where each event is coming from.

So this would be better :

```
function processInstruction(composer, instruction){
  if(composer.element) composer.element.dispatchEvent(new CustomEvent("start",{"detail":this}));
  composer.currentInstruction = null;
  composer.compositionEngine.compose(instruction).then(next => {
    composer.currentBehavior = next;
    composer.currentViewModel = next ? next.executionContext : null;
    if(composer.element) composer.element.dispatchEvent(new CustomEvent("done",{"detail":this}));
  });
}
```

Again not sure about the naming of `start` and `done`.

**Comment by jdanyow** [comment]
@Aaike have you had a chance to try this solution out?  I remember something like this coming up in the gitter in the past.

What would be the behavior when there is nested composition- ie the template being composed has it's own compose element, or a repeat, and so-on.

**Comment by Aaike** [comment]
Correct, it is when using compose inside a repeat.
 
I have created a `list-composer` and a `paginator` that you can use to paginate through the total items of the repeat. the repeat has a compose in it that pulls in other VMs.

So every time i switch a page it composes 12 items.
When doing that there is about 1-2 seconds where you only see the grid's container , no items within. And that is because the compose is still working.

With the adjustment i showed above i can hide the grid while the compose is still working and show a preloader.
I have it working in a website that i'm making but haven't abstracted it to a skeleton nav so the bug can be shown.

**Comment by EisenbergEffect** [comment]
We could probably add these events. The naming probably needs to be more specific though. Maybe "compose-start" and "compose-complete" perhaps? Also, there are some other improvements I'd like to add to composition in the future that are somewhat related, but this might be a decent temporary solution. I need to think on it a bit more.

**Comment by tochoromero** [comment]
I think I'm having the same problem. There is some code that I need to run when everything is loaded. So I just hooked up to the attached() method. But it seems this method is called before the composed views are actually loaded.

So I guess having a way for the 'parent' model to know when all the composed views are already rendered would be really nice. For now I will just workaround it by having the html inline instead of using <compose view.../>

**Comment by andrevlins** [comment]
any update on this?

I have a repeat.for with compose element inside and need to wait until all compose elements activate.

**Comment by EisenbergEffect** [comment]
We are planning some improvements for this for Beta 2. I really want to get it done sooner than later, but it will probably be a few weeks out.

**Comment by sickboy** [comment]
@Aaike my workaround for this is adding a compose.ref="composer"
and then using this on a loader element:
~~~
if.bind="composer.currentController || !composer.currentController.isBound"
~~~

**Comment by gregdouglas** [comment]
Does the latest aurelia release help with this issue?

**Comment by bebor** [comment]
so can we expect the events "compose-start" and "compose-complete" to be implemented?

**Comment by EisenbergEffect** [comment]
Liefcycle is as follows:

* ctor
* created
* bind

(wait for asynchronous binding/composition to complete)

* attached

(wait for something to remove the component)

* detached
* unbind

**Comment by blkbltjns** [comment]
@EisenbergEffect I'm not sure I understand how that lifecycle helps with this problem? I am in the same boat where I need to know when a repeat.for over compose elements is done with attaching the DOM elements. Is there still no way to do this (except maybe using a bindable notifier in the composed elements that runs on attached)?

**Comment by EisenbergEffect** [comment]
There are a couple of approaches you could take. Can you show some sample markup?

**Comment by blkbltjns** [comment]
<b>parent.html</b>
```
<template>
  <div id="container">
    <div repeat.for="item of items">
      <compose repeat.for="item of items" view-mode="${item.viewModelPath}">
      </compose>
    </div>
  </div>
</template>
```

I want the parent component to know when all of the compose elements have attached and are in the DOM so I can do things like measure the height of the #container element.

**Comment by EisenbergEffect** [comment]
What would you expect happen if you added/removed items from the array at a later point in time?

**Comment by blkbltjns** [comment]
@EisenbergEffect 

Probably some kind of changed event would fire, maybe something like a repeat.for.change delegate. My first attempt at dealing with this whole issue was flushing the microtaskqueue, which I expected to work. If this worked the way I expected, I could use it for the initial collection load as well as any changes.

**Comment by len-ro** [comment]
Any plans to implement this? Or any other way to implement this other than chaining queueTask's until the modelView in the compose is available?

**Comment by Mobe91** [comment]
I also require a solution for this.
I have a modal dialog that looks something like this:
```html
<div class="dialog">
  <compose view-model="./my-compose" model.bind="myData"></compose>
</div>
```
The `my-compose` view peforms some asynchronous loading on `activate` based on the passed `myData`. I need a way in the parent component to wait until the loading is done before I display the dialog.

**Comment by StrahilKazlachev** [comment]
@EisenbergEffect I can take it. If you think this is not redundant just reopen the issue.
