### ISSUE TITLE
Replace `$parent` with `$super`

### ISSUE THREAD

**Issue by akircher** [aurelia/templating-resources#67]
Given Aurelia's focus on ES6 syntax, I think that `$super` would be a better name than `$parent`

**Comment by EisenbergEffect** [comment]
It's not really inheritance at work here per se, so I'm not sure that $super makes sense. That aside, we plan to lift the need to use $parent at all in a future iteration so that the variable scopes work in the templating engine the same as they would in JavaScript itself.

**Comment by capaj** [comment]
@EisenbergEffect I agree, also $parent will always be natural for people coming from Angular.
