### ISSUE TITLE
focus

### ISSUE THREAD

**Issue by flieks** [aurelia/templating-resources#70]
i don't know if the focus works.. I added it to index.js (of templating resources).
it binds, it stops in focus.js but in blurlistener/focuslistener, the value variable is the text value of my input and not a boolean

**Comment by martingust** [comment]
I just tested and it works for me. Would you mind share your VM/View? Also what browser are you using?

**Comment by flieks** [comment]
i'm using chrome.
my view:
```
<input id="inputSearch" class="validate" type="text" value.bind="searchText" placeholder="placeholder" focus.bind="hasFocus"> 
<div show.bind="showCalc" > </div>
```
VM:
```javascript
@customElement('auto-complete')
export class AutoComplete {
    hasFocus = false;
    searchString = '';
    get searchText() {
        return this.searchString;
    }
    set searchText(newValue) {
    }
   get showCalc()
    {
       return ((this.searchString.length > 0) && this.hasFocus);
    }
)
```
this is a customElement.

Thanks
Felix

**Comment by martingust** [comment]
That works as well. Have you tested with the latest release from yesterday? If possible could you put together a repo that replicates the issue?

**Comment by flieks** [comment]
this works now perfectly with the new release. Thanks alot
