### ISSUE TITLE
recursive templating not working (in new release)

### ISSUE THREAD

**Issue by flieks** [aurelia/templating-resources#72]
when you have a custom element: 
tree-view.html:
```html
<template>
   <require from='./tree-view'></require>
    test
</template>
```
app.html:
```html
<template>
    <require from='./tree-view'></require>
    <tree-view></tree-view>
</template>
```

that doesn't work anymore (i tested in a fresh skeleton app. And then updated it to new release). navigation doesn't end:
chrome output:
```
INFO [aurelia] Aurelia Started
index.js:41 DEBUG [templating] importing resources for app.html ["nav-bar", "tree-view"]
index.js:41 DEBUG [templating] importing resources for nav-bar.html []
index.js:41 DEBUG [templating] importing resources for tree-view.html ["tree-view"]
```

**Comment by jdanyow** [comment]
@flieks does it work in the latest aurelia build if you remove the `require` elements and use `globalizeResources`?  (search for "globalizeResources" in the [docs](http://aurelia.io/docs.html), it's mentioned a few times)

**Comment by EisenbergEffect** [comment]
I think it should work if you just remove the `require` element since the own element is always available to itself. No need to globalize. Still, there is a bug here as it shouldn't stop working, so I will look into that.

**Comment by flieks** [comment]
thanks , that worked.
i have a new related issue now [here](https://github.com/aurelia/templating/issues/92)

**Comment by EisenbergEffect** [comment]
This needs to stay open. I'd like to see if I can fix this.

**Comment by EisenbergEffect** [comment]
Patch release for templating coming in just a few minutes. Hang on...

**Comment by JoshMcCullough** [comment]
I just ran into this issue using Aurelia 1.0.0-beta.1.2.1 (templating). Remove the `require` from its self fixed it.
