### ISSUE TITLE
Add animation-move for the repeater

### ISSUE THREAD

**Issue by martingust** [aurelia/templating-resources#74]
The base animator defines an interface called move https://github.com/aurelia/templating/blob/master/src/animator.js 
This one is supposed to be called when an existing element changes it's position in the DOM tree most of the times this happens in repeaters ... imagine where you could resort a list. 

(words stolen from @zewa666)

**Comment by martingust** [comment]
@zewa666 Today the repeater doesn't track what view are moved in a way to make this implementation easy without having to rewrite the splice handling logic. When `view caching` gets implemented a lot of this logic is going to be moved from the `repeat` to `templating`. It might be a good idea to wait for that and implemented this at the same time?

@EisenbergEffect Thoughts?

**Comment by zewa666** [comment]
Good idea, thx for creating the issue to track this

**Comment by stoffeastrom** [comment]
This would be a nice feature! :+1:

**Comment by EisenbergEffect** [comment]
Not sure if we need this or want it.
