### ISSUE TITLE
"show.bind" with initial value of null/undefined

### ISSUE THREAD

**Issue by grlscz** [aurelia/templating-resources#79]
Not sure if it is a `show` issue of binding engine issue. If the initial value of binding expression is `null`/`undefined`, then `valueChanged` call doen't happen, and the element remains visible.

Demo: http://plnkr.co/edit/6puQ2FLJc9gNF8MiQIAZ?p=preview

**Comment by jdanyow** [comment]
This will be fixed by https://github.com/aurelia/templating/pull/103 and https://github.com/aurelia/templating-resources/pull/78

**Comment by jdanyow** [comment]
closing- fixes for this issue have been released
