### ISSUE TITLE
Bundling issue 

### ISSUE THREAD

**Issue by jdeux** [aurelia/templating-resources#80]
When following the post [**Bundling an Aurelia Application**](http://blog.durandal.io/2015/06/23/bundling-an-aurelia-application/) under **Bundling JavaScript** an error prevents "app-bundle.js" from being generated:

```
$ aurelia bundle
info: Using Aureliafile: c:\Users\me\Projects\Aurelia\navigation-app\aureliafile.js
info: Creating bundle ...
Potentially unhandled rejection [6] Error: Error loading "github:aurelia/templating-resources@0.12.1" at file:c:/Users/me/Projects/Aurelia/navigation-app/jsp
m_packages/github/aurelia/templating-resources@0.12.1.js
ENOENT, open 'c:\Users\me\Projects\Aurelia\navigation-app\jspm_packages\github\aurelia\templating-resources@0.12.1.js'
    at Error (native)
```

When removing templating-resources from the "aureliafile.js" then "app-bundle.js" is successfully generated.

```
$ aurelia bundle
info: Using Aureliafile: c:\Users\me\Projects\Aurelia\navigation-app\aureliafile.js
info: Creating bundle ...
```

**Comment by EisenbergEffect** [comment]
Please check to make sure that versions in your bundle config match what is actually installed in your project. We will be fixing this so that is't not necessary in the future. @ahmedshuhel Please track the version issue here.

**Comment by ahmedshuhel** [comment]
OK, I am working on this feature currently.

**Comment by ahmedshuhel** [comment]
v0.3.0 release that we have pushed already should fix this problem.
