### ISSUE TITLE
repeat.for="x of count" duplicates views when count changes

### ISSUE THREAD

**Issue by jdanyow** [aurelia/templating-resources#81]
[plunkr](http://plnkr.co/edit/ZSBB0ErlbDjfQ5LKuSDC?p=preview) (click on the "increment" link to see the issue)

```javascript
export class App {
  count = 3;
  
  increment() {
     this.count++;
  }
}
```
```html
<template>
  Count=${count} <a click.trigger="increment()" href="#">Increment</a>
  
  <ul>
    <li repeat.for="x of count">${x}</li>
  </ul>
</template>
```

**Comment by tkiethanom** [comment]
Reopened then closed. Does this mean it was verified as fixed?

**Comment by jdanyow** [comment]
Initially checked in our plunkr (where it's broken) but confirmed it's fixed in the latest version of the skeleton-navigation project.  Do you have latest?

**Comment by tkiethanom** [comment]
Working correctly after jspm update to get the latest version.
