### ISSUE TITLE
Clearing list stops repeat.for working

### ISSUE THREAD

**Issue by RalfJan** [aurelia/templating-resources#83]
We are trying to make a UL list that can be refreshed with new data. 
We got so far that we can generate the list of 'units' like this:

< div class="row au-stagger">
            &nbsp;< ul class="list-group">
                &nbsp;&nbsp;< li class="list-group-item" repeat.for="unit of units" ">
                    &nbsp;&nbsp;&nbsp;.....
                &nbsp;&nbsp;< /li>
            &nbsp;< /ul>
        < /div>

The viewmodel basically looks like this to refresh the list with new data:

 if (this.units.length > 0) {
            this.units.splice(0,this.units.length);
        }
var i=0;
 for (var unit of sourceOfUnits) {
                this.units[i++] = unit; 
            }

Problem for us starts when we try update the 'units' array in the viewmodel. We can clear the units array and that removes the list in the view, but when a add new data to the Array, the list remain empty. Have we missed something in the binding or is this a bug?

**Comment by jdanyow** [comment]
What happens if you use `this.units.push(unit)` instead of `this.units[i++] = unit;` ?

Is this issue reproducible in both Chrome and Internet Explorer or just IE?

**Comment by RalfJan** [comment]
I have only tried it so far in IE. But your sugestion above seem to have help, the list is now updated.

**Comment by RalfJan** [comment]
Hi Jeremy,

 

Yes, I tried that and seemed to have fixed the problem we had.

 

Thank you, and thank you for the swift reply!

 

Best Regards,

Ralf
