### ISSUE TITLE
Get reference to view model with compose 

### ISSUE THREAD

**Issue by olanod** [aurelia/templating-resources#90]
I have a composed view `<compose view-model="app/some/nice-view"></compose>` and I'd like to reference the inner view model form a sibling element of the compose or from the js code.
I'd like to do something like this:
```
<button click.delegate="foo.jump()">Click Me</button>
<compose view-model.ref="foo" view-model="app/some/nice-view"></compose>
```
```
export class NiceView {
    ...
    jump(){...}
}
```

**Comment by EisenbergEffect** [comment]
Well, you can get a hold of the compose's view model with `compose.ref="foo"`. From there you can probably get at the composed view model instance.

**Comment by olanod** [comment]
Well the view model instance would be `foo.currentViewModel`, but there's a timing issue. If I want to assign this view model to my current view model there's no clean way to do it because that property(`currentViewModel`) only exists when the composed element is attached(bound?) and that happens after the callbacks of my current view model are called.

**Comment by EisenbergEffect** [comment]
Did you try doing `<button click.delegate="foo.currentViewModel.jump()">Click Me</button>` ?

**Comment by olanod** [comment]
That should work, but I which there was a simpler/prettier way because I have to access that more than once, and that's just an example, I actually have to use it in one place like this `this.$parent.$parent.foo.currentViewModel.otherThing.someMethod()`(btw it would be nice to get this $parent reference in nested routes automatically).  
As you see it's getting ugly. Some other thing that could help is if the view model is injectable somehow.

**Comment by EisenbergEffect** [comment]
It can't be injectible because it can dynamically change at any time if it's bound. We could add an event to the compose element that fires whenever a composition completes.

**Comment by jdanyow** [comment]
@olanod can this be closed?  This week's release eliminates the need to use $parent.

**Comment by jdanyow** [comment]
closing- @olanod please re-open if you're still having trouble with this.

**Comment by timfish** [comment]
I'm trying to use `compose.ref` but `currentViewModel` doesn't appear to exist in any TypeScript definitions.  Does this means its not in the public API?

**Comment by timfish** [comment]
I'm trying to use `compose.ref` with typescript but the `currentViewModel` doesn't exist in any definitions. Does that means it's not a public API or are the definitions incomplete?

**Comment by eamodio** [comment]
@jdanyow I had the same question as @timfish -- can `currentViewModel` safely be used?
