### ISSUE TITLE
repeat updates executionContext on items too early if au-animate

### ISSUE THREAD

**Issue by benib** [aurelia/templating-resources#94]
If there is `au-animate` on the repeated element, when splicing the Array the execution context gets updated too early here: https://github.com/aurelia/templating-resources/blob/master/src/repeat.js#L283-L292. There are still all children in the viewSlot as their removal is delayed by the Animator here: https://github.com/aurelia/templating/blob/master/src/view-slot.js#L137-L140

Therefore the execution context is wrong after the elements got finally removed (e.g. $index is wrong)

The repeater should wait there if the Element is animatable. I tried to implement it but was not sure how to best get all the leave promises of the animatable children here: https://github.com/aurelia/templating-resources/blob/master/src/repeat.js#L283

I'd appreciate any hints how to get these promises best and would happily help with  sending in a PR or with testing or whatnot.

**Comment by EisenbergEffect** [comment]
@martingust Can you look into this?

**Comment by martingust** [comment]
@EisenbergEffect Got this reproduced, will look into a fix.

**Comment by benib** [comment]
Thank you for your hard work guys! I really appreciate it.
