### ISSUE TITLE
compose Cannot read property 'router' of null

### ISSUE THREAD

**Issue by erikaspl** [aurelia/templating-resources#97]
Before the last update to aurelia framework I used to be able to replace 
  `<nav-bar router.bind="router"></nav-bar>`
with
  `<compose view-model="./nav-bar" model.bind="router"></compose>`
in app.html of skeleton-navigation

This doesn't work anymore. In fact, none of my compose work with upgraded aurelia. Is there a problem with compose at the moment?

**Comment by jdanyow** [comment]
@erikaspl have the latest aurelia releases fixed this for you?  If not, could you provide some more info on how to reproduce this so we can get it fixed before the beta?
