### ISSUE TITLE
Strange path when bootstrapping templating-resources lib

### ISSUE THREAD

**Issue by RalfJan** [aurelia/templating-resources#99]
Having made a new installation of Aurelia files we get this strange behavior for just one of the libraries during bootstrap, the templating-resources@0.12.0. As the log below shows, please note the extra .js insterted to the folder name when it it tries to load the compose.js file.

DEBUG [aurelia] Loading plugin http://localhost:51927/FrontEnd/jspm_packages/github/aurelia/event-aggregator@0.5.0.js.DEBUG [aurelia] Configured plugin http://localhost:51927/FrontEnd/jspm_packages/github/aurelia/event-aggregator@0.5.0.js.
DEBUG [aurelia] Loading plugin aurelia-animator-css.
DEBUG [aurelia] Configured plugin aurelia-animator-css.
Unhandled promise rejection Error: XHR error (404 Not Found) loading http://localhost:51927/FrontEnd/jspm_packages/github/aurelia/templating-resources@0.12.0.js/compose.js

We are using SystemJS v0.18.9.

Other libraries of the framwork are found without any problem.

**Comment by EisenbergEffect** [comment]
Make sure you are using the latest release of jspm and make sure your configuration is set up like the nav skeleton.

**Comment by RalfJan** [comment]
Thank you for you Swift reply!

By the way how can we get some kind of support license for Aurelia?

**Comment by EisenbergEffect** [comment]
We haven't yet published our official support plans. However, we can work something out custom with you. Please email me at rob at durandal dot io and we can discuss the specifics. Thank you!
